import { Feather } from '@expo/vector-icons';
import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';

const voiceData = [{ name: 'Aarav', language: 'English · India', size: '42 MB', installed: true, accent: '#55E6C1' }, { name: 'Priya', language: 'हिन्दी · India', size: '38 MB', installed: true, accent: '#5B5DE6' }, { name: 'Sofia', language: 'English · US', size: '44 MB', installed: false, accent: '#4AA7F5' }];
export default function VoicesScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const [voices, setVoices] = useState(voiceData); const [downloading, setDownloading] = useState<string | null>(null);
  const download = (name: string) => { setDownloading(name); setTimeout(() => { setVoices((current) => current.map((voice) => voice.name === name ? { ...voice, installed: true } : voice)); setDownloading(null); }, 900); };
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={{ paddingTop: insets.top + 18, paddingBottom: insets.bottom + 30 }}><View style={styles.heading}><Text style={[styles.kicker, { color: colors.primary }]}>VOICE LIBRARY</Text><Text style={[styles.title, { color: colors.foreground }]}>Find your voice.</Text><Text style={[styles.sub, { color: colors.mutedForeground }]}>Open-source voices, downloaded once, ready whenever you are.</Text></View><View style={[styles.info, { backgroundColor: colors.secondary }]}><Feather name="wifi-off" size={18} color={colors.primary} /><Text style={[styles.infoText, { color: colors.secondaryForeground }]}>Downloads are stored on your device. Playback works offline.</Text></View><Text style={[styles.label, { color: colors.mutedForeground }]}>AVAILABLE VOICES</Text>{voices.map((voice) => <View key={voice.name} style={[styles.voice, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: `${voice.accent}25` }]}><Text style={[styles.avatarText, { color: voice.accent }]}>{voice.name[0]}</Text></View><View style={styles.voiceCopy}><Text style={[styles.voiceName, { color: colors.foreground }]}>{voice.name}</Text><Text style={[styles.voiceMeta, { color: colors.mutedForeground }]}>{voice.language} · {voice.size}</Text><View style={styles.tag}><Text style={[styles.tagText, { color: voice.installed ? colors.primary : colors.mutedForeground }]}>{voice.installed ? 'READY OFFLINE' : 'OPEN-SOURCE MODEL'}</Text></View></View>{voice.installed ? <View style={styles.ready}><Feather name="check" size={17} color={colors.primary} /></View> : <Pressable accessibilityRole="button" accessibilityLabel={`Download ${voice.name} voice`} onPress={() => download(voice.name)} style={[styles.download, { borderColor: colors.primary }]}>{downloading === voice.name ? <ActivityIndicator size="small" color={colors.primary} /> : <><Feather name="download" size={15} color={colors.primary} /><Text style={[styles.downloadText, { color: colors.primary }]}>Get</Text></>}</Pressable>}</View>)}<View style={[styles.note, { borderColor: colors.border }]}><Feather name="search" size={17} color={colors.accent} /><Text style={[styles.noteText, { color: colors.mutedForeground }]}>Voice discovery will keep expanding with new Piper and ONNX models.</Text></View></ScrollView>;
}
const styles = StyleSheet.create({ heading: { paddingHorizontal: 20, marginBottom: 21 }, kicker: { fontSize: 11, letterSpacing: 1.8, fontFamily: 'Inter_700Bold', marginBottom: 10 }, title: { fontSize: 30, fontFamily: 'Inter_700Bold', marginBottom: 7 }, sub: { fontSize: 14, lineHeight: 20, fontFamily: 'Inter_400Regular' }, info: { marginHorizontal: 20, padding: 14, borderRadius: 15, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 27 }, infoText: { flex: 1, fontSize: 12, lineHeight: 18, fontFamily: 'Inter_500Medium' }, label: { marginHorizontal: 20, fontSize: 11, letterSpacing: 1.5, fontFamily: 'Inter_700Bold', marginBottom: 9 }, voice: { marginHorizontal: 20, borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: 'row', alignItems: 'center', marginBottom: 10 }, avatar: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 21, fontFamily: 'Inter_700Bold' }, voiceCopy: { flex: 1, marginLeft: 12 }, voiceName: { fontSize: 15, fontFamily: 'Inter_600SemiBold', marginBottom: 4 }, voiceMeta: { fontSize: 11, fontFamily: 'Inter_400Regular', marginBottom: 7 }, tag: { alignSelf: 'flex-start' }, tagText: { fontSize: 9, letterSpacing: 1, fontFamily: 'Inter_700Bold' }, ready: { width: 37, height: 37, borderRadius: 19, backgroundColor: '#55E6C120', alignItems: 'center', justifyContent: 'center' }, download: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: 11, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 5 }, downloadText: { fontSize: 12, fontFamily: 'Inter_700Bold' }, note: { margin: 20, paddingTop: 16, borderTopWidth: 1, flexDirection: 'row', gap: 9 }, noteText: { flex: 1, fontSize: 12, lineHeight: 18, fontFamily: 'Inter_400Regular' } });