export type VoiceGender = 'female' | 'male';
export type VoiceQuality = 'high' | 'medium';

export type VoiceCatalogItem = {
  id: string;
  name: string;
  language: string;
  languageName: string;
  gender: VoiceGender;
  quality: VoiceQuality;
  modelUrl: string;
  configUrl: string;
  modelSizeBytes?: number;
  configSizeBytes?: number;
  sha256?: string;
  downloadable: boolean;
};

/**
 * Model URLs are intentionally configuration-driven. Large TTS assets are
 * downloaded after installation and never bundled in the APK.
 *
 * The catalog is extensible: add more voices without changing Reader logic.
 * Users may install any number of these voices concurrently.
 */
export const VOICE_CATALOG: VoiceCatalogItem[] = [
  { id: 'en-us-lessac-medium', name: 'Lessac Medium', language: 'en-US', languageName: 'English (US)', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx.json?download=true', modelSizeBytes: 63201294, downloadable: true },
  { id: 'en-us-ryan-medium', name: 'Ryan Medium', language: 'en-US', languageName: 'English (US)', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx.json?download=true', downloadable: true },
  { id: 'en-us-amy-medium', name: 'Amy Medium', language: 'en-US', languageName: 'English (US)', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx.json?download=true', downloadable: true },
  { id: 'en-gb-alan-medium', name: 'Alan Medium', language: 'en-GB', languageName: 'English (UK)', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/en_GB-alan-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/en_GB-alan-medium.onnx.json?download=true', downloadable: true },
  { id: 'en-gb-southern-medium', name: 'Southern English', language: 'en-GB', languageName: 'English (UK)', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/southern_english_female/medium/en_GB-southern_english_female-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/southern_english_female/medium/en_GB-southern_english_female-medium.onnx.json?download=true', downloadable: true },
  { id: 'en-in-rohan-medium', name: 'Rohan Medium', language: 'en-IN', languageName: 'English (India)', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_IN/rohan/medium/en_IN-rohan-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_IN/rohan/medium/en_IN-rohan-medium.onnx.json?download=true', downloadable: true },
  { id: 'en-in-priyanka-medium', name: 'Priyanka Medium', language: 'en-IN', languageName: 'English (India)', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_IN/priyanka/medium/en_IN-priyanka-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_IN/priyanka/medium/en_IN-priyanka-medium.onnx.json?download=true', downloadable: true },
  { id: 'hi-in-priyamvada-medium', name: 'Priyamvada Medium', language: 'hi-IN', languageName: 'Hindi', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/hi/hi_IN/priyamvada/medium/hi_IN-priyamvada-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/hi/hi_IN/priyamvada/medium/hi_IN-priyamvada-medium.onnx.json?download=true', modelSizeBytes: 63516050, downloadable: true },
  { id: 'hi-in-vikas-medium', name: 'Vikas Medium', language: 'hi-IN', languageName: 'Hindi', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/hi/hi_IN/vikas/medium/hi_IN-vikas-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/hi/hi_IN/vikas/medium/hi_IN-vikas-medium.onnx.json?download=true', downloadable: true },
  { id: 'es-es-sharvard-medium', name: 'Sharvard Medium', language: 'es-ES', languageName: 'Spanish', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/sharvard/medium/es_ES-sharvard-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/sharvard/medium/es_ES-sharvard-medium.onnx.json?download=true', downloadable: true },
  { id: 'es-mx-ald-medium', name: 'Ald Medium', language: 'es-MX', languageName: 'Spanish (Mexico)', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/ald/medium/es_MX-ald-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/ald/medium/es_MX-ald-medium.onnx.json?download=true', downloadable: true },
  { id: 'fr-fr-siwis-medium', name: 'Siwis Medium', language: 'fr-FR', languageName: 'French', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx.json?download=true', downloadable: true },
  { id: 'de-de-thorsten-medium', name: 'Thorsten Medium', language: 'de-DE', languageName: 'German', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/medium/de_DE-thorsten-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/medium/de_DE-thorsten-medium.onnx.json?download=true', downloadable: true },
  { id: 'it-it-paola-medium', name: 'Paola Medium', language: 'it-IT', languageName: 'Italian', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/paola/medium/it_IT-paola-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/paola/medium/it_IT-paola-medium.onnx.json?download=true', downloadable: true },
  { id: 'pt-br-faber-medium', name: 'Faber Medium', language: 'pt-BR', languageName: 'Portuguese (Brazil)', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx.json?download=true', downloadable: true },
  { id: 'nl-nl-rdh-medium', name: 'RDH Medium', language: 'nl-NL', languageName: 'Dutch', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/rdh/medium/nl_NL-rdh-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/rdh/medium/nl_NL-rdh-medium.onnx.json?download=true', downloadable: true },
  { id: 'sv-se-nst-medium', name: 'NST Medium', language: 'sv-SE', languageName: 'Swedish', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx.json?download=true', downloadable: true },
  { id: 'da-dk-tales-medium', name: 'Tales Medium', language: 'da-DK', languageName: 'Danish', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/da/da_DK/tales/medium/da_DK-tales-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/da/da_DK/tales/medium/da_DK-tales-medium.onnx.json?download=true', downloadable: true },
  { id: 'no-no-tales-medium', name: 'Tales Medium', language: 'no-NO', languageName: 'Norwegian', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/no/no_NO/tales/medium/no_NO-tales-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/no/no_NO/tales/medium/no_NO-tales-medium.onnx.json?download=true', downloadable: true },
  { id: 'fi-fi-harri-medium', name: 'Harri Medium', language: 'fi-FI', languageName: 'Finnish', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/fi/fi_FI/harri/medium/fi_FI-harri-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/fi/fi_FI/harri/medium/fi_FI-harri-medium.onnx.json?download=true', downloadable: true },
  { id: 'pl-pl-darkman-medium', name: 'Darkman Medium', language: 'pl-PL', languageName: 'Polish', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/darkman/medium/pl_PL-darkman-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/darkman/medium/pl_PL-darkman-medium.onnx.json?download=true', downloadable: true },
  { id: 'cs-cz-jirka-medium', name: 'Jirka Medium', language: 'cs-CZ', languageName: 'Czech', gender: 'male', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/cs/cs_CZ/jirka/medium/cs_CZ-jirka-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/cs/cs_CZ/jirka/medium/cs_CZ-jirka-medium.onnx.json?download=true', downloadable: true },
  { id: 'uk-ua-ukrainian-medium', name: 'Ukrainian Medium', language: 'uk-UA', languageName: 'Ukrainian', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/ukrainian/medium/uk_UA-ukrainian-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/ukrainian/medium/uk_UA-ukrainian-medium.onnx.json?download=true', downloadable: true },
  { id: 'ru-ru-irina-medium', name: 'Irina Medium', language: 'ru-RU', languageName: 'Russian', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx.json?download=true', downloadable: true },
  { id: 'tr-tr-dfki-medium', name: 'DFKI Medium', language: 'tr-TR', languageName: 'Turkish', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx.json?download=true', downloadable: true },
  { id: 'vi-vn-vivos-medium', name: 'VIVOS Medium', language: 'vi-VN', languageName: 'Vietnamese', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vivos/medium/vi_VN-vivos-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vivos/medium/vi_VN-vivos-medium.onnx.json?download=true', downloadable: true },
  { id: 'ko-kr-kss-medium', name: 'KSS Medium', language: 'ko-KR', languageName: 'Korean', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/ko/ko_KR/kss/medium/ko_KR-kss-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/ko/ko_KR/kss/medium/ko_KR-kss-medium.onnx.json?download=true', downloadable: true },
  { id: 'ja-jp-tsukuyomi-medium', name: 'Tsukuyomi Medium', language: 'ja-JP', languageName: 'Japanese', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/ja/ja_JP/tsukuyomi/medium/ja_JP-tsukuyomi-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/ja/ja_JP/tsukuyomi/medium/ja_JP-tsukuyomi-medium.onnx.json?download=true', downloadable: true },
  { id: 'zh-cn-huayan-medium', name: 'Huayan Medium', language: 'zh-CN', languageName: 'Chinese (Mandarin)', gender: 'female', quality: 'high', modelUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/zh/zh_CN/huayan/medium/zh_CN-huayan-medium.onnx?download=true', configUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/zh/zh_CN/huayan/medium/zh_CN-huayan-medium.onnx.json?download=true', downloadable: true },
];

export const VOICE_CATALOG_COUNT = VOICE_CATALOG.length;
