import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useState } from 'react';
import { useColors } from '@/hooks/useColors';

function SettingRow({ icon, title, detail, onPress, right }: { icon: React.ComponentProps<typeof Feather>['name']; title: string; detail: string; onPress?: () => void; right?: React.ReactNode }) {
  const colors = useColors();
  return <Pressable accessibilityRole={onPress ? 'button' : undefined} onPress={onPress} style={({ pressed }) => [styles.row, { borderBottomColor: colors.border }, pressed && onPress && { opacity: 0.7 }]}><View style={[styles.rowIcon, { backgroundColor: colors.secondary }]}><Feather name={icon} size={18} color={colors.primary} /></View><View style={styles.rowCopy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.rowDetail, { color: colors.mutedForeground }]}>{detail}</Text></View>{right ?? <Feather name="chevron-right" size={18} color={colors.mutedForeground} />}</Pressable>;
}

export default function SettingsScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const [autoSwitch, setAutoSwitch] = useState(true);
  const [skipSymbols, setSkipSymbols] = useState(true);
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={{ paddingTop: insets.top + 18, paddingBottom: insets.bottom + 110 }}><View style={styles.heading}><Text style={[styles.kicker, { color: colors.primary }]}>CONTROL CENTER</Text><Text style={[styles.title, { color: colors.foreground }]}>Settings</Text><Text style={[styles.sub, { color: colors.mutedForeground }]}>Make Nexus Plus sound and feel like yours.</Text></View><Text style={[styles.group, { color: colors.mutedForeground }]}>VOICE & READING</Text><View style={[styles.groupBox, { backgroundColor: colors.card, borderColor: colors.border }]}><SettingRow icon="volume-2" title="Voice library" detail="2 offline voices ready" onPress={() => router.push('/voices')} /><SettingRow icon="repeat" title="Auto language switching" detail="Hindi ↔ English" right={<Switch value={autoSwitch} onValueChange={setAutoSwitch} trackColor={{ false: colors.secondary, true: colors.primary }} thumbColor={colors.foreground} accessibilityLabel="Auto language switching" />} /><SettingRow icon="slash" title="Skip symbols & URLs" detail="Cleaner speech" right={<Switch value={skipSymbols} onValueChange={setSkipSymbols} trackColor={{ false: colors.secondary, true: colors.primary }} thumbColor={colors.foreground} accessibilityLabel="Skip symbols and URLs" />} /></View><Text style={[styles.group, { color: colors.mutedForeground }]}>ABOUT</Text><View style={[styles.groupBox, { backgroundColor: colors.card, borderColor: colors.border }]}><SettingRow icon="info" title="About Nexus Plus" detail="Version 1.0.0" onPress={() => router.push('/about')} /><SettingRow icon="mail" title="Support" detail="kuldeepky538@gmail.com" onPress={() => router.push('/about')} /><SettingRow icon="shield" title="Privacy & terms" detail="Zero data collection" onPress={() => router.push('/about')} /></View><View style={styles.brand}><Text style={[styles.brandMark, { color: colors.primary }]}>N+</Text><Text style={[styles.brandText, { color: colors.mutedForeground }]}>Built for access. Built for listening.</Text></View></ScrollView>;
}
const styles = StyleSheet.create({ heading: { paddingHorizontal: 20, marginBottom: 28 }, kicker: { fontSize: 11, letterSpacing: 2, fontFamily: 'Inter_700Bold', marginBottom: 10 }, title: { fontSize: 30, fontFamily: 'Inter_700Bold', marginBottom: 7 }, sub: { fontSize: 14, fontFamily: 'Inter_400Regular' }, group: { paddingHorizontal: 20, fontSize: 11, letterSpacing: 1.5, fontFamily: 'Inter_700Bold', marginBottom: 9 }, groupBox: { marginHorizontal: 20, borderRadius: 18, borderWidth: 1, overflow: 'hidden', marginBottom: 26 }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, borderBottomWidth: 1 }, rowIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, rowCopy: { flex: 1, marginLeft: 12 }, rowTitle: { fontSize: 14, fontFamily: 'Inter_600SemiBold', marginBottom: 4 }, rowDetail: { fontSize: 12, fontFamily: 'Inter_400Regular' }, brand: { alignItems: 'center', marginTop: 7 }, brandMark: { fontSize: 30, fontFamily: 'Inter_700Bold', marginBottom: 5 }, brandText: { fontSize: 12, fontFamily: 'Inter_400Regular' } });