import { useCallback,useEffect,useState } from 'react';
import { Feather } from '@expo/vector-icons';
import { Alert,Linking,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { createPaymentOrder,getActiveAiCreditPlans,getActivePremiumPlans,getMyPremiumEntitlement,getPaymentSettings ,type AiCreditPlan,type PaymentSettings,type PremiumCatalogPlan,type PremiumEntitlement } from '@/features/premium/premiumRepository';

export default function BuyPremiumScreen(){
 const colors=useColors(); const router=useRouter(); const insets=useSafeAreaInsets();
 const [plans,setPlans]=useState<PremiumCatalogPlan[]>([]); const [creditPlans,setCreditPlans]=useState<AiCreditPlan[]>([]); const [entitlement,setEntitlement]=useState<PremiumEntitlement|null>(null); const [payment,setPayment]=useState<PaymentSettings|null>(null); const [loading,setLoading]=useState(true); const [waiting,setWaiting]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const [p,c,e,s]=await Promise.all([getActivePremiumPlans(),getActiveAiCreditPlans(),getMyPremiumEntitlement().catch(()=>null),getPaymentSettings()]);setPlans(p);setCreditPlans(c);setEntitlement(e);setPayment(s);}catch{Alert.alert('Premium','Plans or payment settings could not be loaded right now.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const start=async(type:'PREMIUM'|'AI_CREDITS',code:string)=>{try{const o=await createPaymentOrder(type,code);setWaiting(true);const url='upi://pay?pa='+encodeURIComponent(o.upiId)+'&pn='+encodeURIComponent(o.receiverName)+'&am='+encodeURIComponent(String(o.amountInr))+'&cu=INR&tn='+encodeURIComponent('Nexus Plus '+code);const ok=await Linking.canOpenURL(url);if(ok){await Linking.openURL(url);Alert.alert('Payment started','Complete the UPI payment. Nexus Plus will verify the payment notification automatically after the bank confirms the credit.');}else{setWaiting(false);Alert.alert('UPI payment','No UPI app is available.');}}catch{setWaiting(false);Alert.alert('Payment','Could not create the payment request. Please try again.');}};
 return <View style={[styles.root,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={{paddingTop:insets.top+8,paddingBottom:insets.bottom+32}}>
  <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>router.back()} style={styles.iconButton}><Feather name="arrow-left" size={22} color={colors.foreground}/></Pressable><Text accessibilityRole="header" style={[styles.headerTitle,{color:colors.foreground}]}>Nexus Plus Premium</Text><Pressable accessibilityRole="button" accessibilityLabel="Refresh" onPress={()=>void load()} style={styles.iconButton}><Feather name="refresh-cw" size={19} color={colors.foreground}/></Pressable></View>
  {entitlement?.unlocksPremiumFeatures&&<View style={[styles.activeCard,{backgroundColor:colors.secondary,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.foreground}]}>Premium is active</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>Tier {entitlement.tierLevel} • Expires {entitlement.expiresAt?new Date(entitlement.expiresAt).toLocaleDateString():'soon'}</Text></View>}
  <View style={styles.hero}><View style={[styles.icon,{backgroundColor:colors.secondary}]}><Feather name="zap" size={25} color={colors.primary}/></View><Text style={[styles.title,{color:colors.foreground}]}>Premium tools for Nexus Plus</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>Free tools and spiritual features stay free. Premium access applies only to the features configured as Premium in the live Supabase catalog.</Text></View>
  {payment&&<View style={[styles.upiCard,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.foreground}]}>Pay with UPI</Text><Text selectable style={[styles.upi,{color:colors.primary}]}>{payment.upiId}</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>{payment.instructions}</Text></View>}
  <Text style={[styles.sectionTitle,{color:colors.foreground}]}>Membership</Text>
  {plans.map(p=><View key={p.id} style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><View style={styles.row}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:colors.foreground}]}>{p.name}</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>{p.description}</Text></View><Text style={[styles.price,{color:colors.primary}]}>₹{p.amount}</Text></View><Text style={[styles.meta,{color:colors.mutedForeground}]}>{p.durationDays} days • Tier {p.tierLevel}</Text><Pressable accessibilityRole="button" onPress={()=>void start('PREMIUM',p.code)} style={[styles.button,{backgroundColor:colors.primary}]}><Text style={styles.buttonText}>Pay ₹{p.amount} with UPI</Text></Pressable></View>)}
  <Text style={[styles.sectionTitle,{color:colors.foreground}]}>AI Credits</Text>
  {creditPlans.map(p=><View key={p.id} style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><View style={styles.row}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:colors.foreground}]}>{p.name}</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>{p.tagline}</Text></View><Text style={[styles.price,{color:colors.primary}]}>₹{p.amount}</Text></View><Text style={[styles.meta,{color:colors.mutedForeground}]}>{p.credits.toLocaleString()} AI credits</Text><Pressable accessibilityRole="button" onPress={()=>void start('AI_CREDITS',p.code)} style={[styles.button,{backgroundColor:colors.secondary,borderColor:colors.border,borderWidth:1}]}><Text style={[styles.buttonText,{color:colors.foreground}]}>Pay ₹{p.amount} with UPI</Text></Pressable></View>)}
  {waiting&&<View style={[styles.waitingCard,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.foreground}]}>Payment verification in progress</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>No UTR is required. Nexus Plus will wait for a bank/payment notification and activate your purchase only after the received amount matches the selected plan.</Text></View>}{loading&&<Text style={[styles.loading,{color:colors.mutedForeground}]}>Loading…</Text>}
 </ScrollView></View>;
}
const styles=StyleSheet.create({root:{flex:1},header:{minHeight:52,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},iconButton:{width:44,height:44,alignItems:'center',justifyContent:'center'},headerTitle:{fontSize:18,fontFamily:'Inter_700Bold'},hero:{alignItems:'center',paddingHorizontal:22,paddingTop:24,paddingBottom:18},icon:{width:60,height:60,borderRadius:18,alignItems:'center',justifyContent:'center',marginBottom:14},title:{fontSize:23,lineHeight:30,fontFamily:'Inter_700Bold',textAlign:'center'},body:{fontSize:12,lineHeight:18,marginTop:7},sectionTitle:{fontSize:15,fontFamily:'Inter_700Bold',marginHorizontal:16,marginTop:12,marginBottom:9},card:{marginHorizontal:16,marginBottom:10,borderWidth:1,borderRadius:16,padding:15},activeCard:{marginHorizontal:16,marginBottom:8,borderWidth:1,borderRadius:16,padding:15},upiCard:{marginHorizontal:16,marginBottom:10,borderWidth:1,borderRadius:16,padding:15},cardTitle:{fontSize:15,fontFamily:'Inter_700Bold',marginBottom:4},row:{flexDirection:'row',alignItems:'flex-start',gap:10},price:{fontSize:18,fontFamily:'Inter_700Bold'},meta:{fontSize:11,marginTop:8},upi:{fontSize:18,fontFamily:'Inter_700Bold',marginTop:4},button:{minHeight:46,borderRadius:13,marginTop:12,alignItems:'center',justifyContent:'center',paddingHorizontal:12},buttonText:{color:'#fff',fontSize:12,fontFamily:'Inter_700Bold'},waitingCard:{marginHorizontal:16,marginBottom:10,borderWidth:1,borderRadius:16,padding:15},loading:{textAlign:'center',marginTop:18,fontSize:12}});
