import { Feather } from '@expo/vector-icons';
import * as Speech from 'expo-speech';
import { router, Stack } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { calculateAge, calculateDiscount, calculateElectricity, calculateEmi, calculateFixedDeposit, calculatePercentage, calculateTipBill, evaluateStandard, type CalculatorMode } from '@/features/calculator/calculatorEngine';

const MODES: Array<{ id: CalculatorMode; label: string; icon: string }> = [
  { id: 'standard', label: 'Normal', icon: 'hash' }, { id: 'age', label: 'Age', icon: 'user' }, { id: 'tip-bill', label: 'Tip & Bill', icon: 'users' },
  { id: 'electricity', label: 'Electricity', icon: 'zap' }, { id: 'fixed-deposit', label: 'Fixed Deposit', icon: 'briefcase' }, { id: 'emi', label: 'EMI', icon: 'credit-card' },
  { id: 'discount', label: 'Discount', icon: 'tag' }, { id: 'percentage', label: 'Percent', icon: 'percent' },
];
function useAnnouncer() { return (text: string) => { void Speech.stop().then(() => Speech.speak(text, { rate: 0.9 })); }; }
export default function CalculatorScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const [mode, setMode] = useState<CalculatorMode>('standard'); const announce = useAnnouncer();
  const [expression, setExpression] = useState(''); const [fields, setFields] = useState<Record<string, string>>({}); const [result, setResult] = useState('');
  const update = (key: string, value: string) => setFields((current) => ({ ...current, [key]: value })); const value = (key: string) => fields[key] ?? '';
  const speakResult = (text: string) => { setResult(text); announce(text); };
  const standardButtons = useMemo(() => [['7','8','9','÷'],['4','5','6','×'],['1','2','3','-'],['0','.','%','+']], []);
  const onStandard = (key: string) => {
    if (key === '=') { try { speakResult(formatNumber(evaluateStandard(expression))); } catch (error) { const message = error instanceof Error ? error.message : 'Calculation error.'; Alert.alert('Calculator', message); announce(message); } return; }
    if (key === 'C') { setExpression(''); setResult(''); announce('Cleared'); return; } if (key === '⌫') { setExpression((current) => current.slice(0, -1)); return; }
    setExpression((current) => `${current}${key}`); announce(key === '÷' ? 'divide' : key === '×' ? 'multiply' : key);
  };
  const calculate = () => {
    try { let spoken = '';
      switch (mode) {
        case 'age': { const [y,m,d] = value('dob').split('-').map(Number); if (![y,m,d].every(Number.isFinite)) throw new Error('Enter date as YYYY-MM-DD.'); const a = calculateAge(new Date(y, m - 1, d)); spoken = `${a.years} years, ${a.months} months, ${a.days} days`; break; }
        case 'tip-bill': { const r = calculateTipBill(Number(value('bill')), Number(value('tip')), Number(value('people'))); spoken = `Tip ${formatNumber(r.tip)}, total ${formatNumber(r.total)}, each person ${formatNumber(r.perPerson)}`; break; }
        case 'electricity': { const r = calculateElectricity(Number(value('units')), Number(value('fixed')), Number(value('rate')), Number(value('surcharge'))); spoken = `Energy ${formatNumber(r.energy)}, surcharge ${formatNumber(r.surcharge)}, total ${formatNumber(r.total)}`; break; }
        case 'fixed-deposit': { const r = calculateFixedDeposit(Number(value('principal')), Number(value('rate')), Number(value('years')), Number(value('compound') || '4')); spoken = `Interest ${formatNumber(r.interest)}, maturity ${formatNumber(r.maturity)}`; break; }
        case 'emi': { const r = calculateEmi(Number(value('loan')), Number(value('rate')), Number(value('months'))); spoken = `Monthly EMI ${formatNumber(r.emi)}, total interest ${formatNumber(r.interest)}, total payment ${formatNumber(r.totalPayment)}`; break; }
        case 'discount': { const r = calculateDiscount(Number(value('price')), Number(value('discount')), Number(value('tax'))); spoken = `Discount ${formatNumber(r.discount)}, tax ${formatNumber(r.tax)}, final price ${formatNumber(r.finalPrice)}`; break; }
        case 'percentage': { const r = calculatePercentage(Number(value('number')), Number(value('percent'))); spoken = `${formatNumber(value('percent'))} percent of ${formatNumber(value('number'))} is ${formatNumber(r)}`; break; }
        default: break;
      } speakResult(spoken);
    } catch (error) { const message = error instanceof Error ? error.message : 'Check your values.'; Alert.alert('Calculator', message); announce(message); }
  };
  const field = (key: string, label: string, placeholder: string) => <View style={styles.field}><Text style={[styles.label, { color: colors.foreground }]}>{label}</Text><TextInput accessibilityLabel={label} value={value(key)} onChangeText={(v) => update(key, v)} keyboardType={mode === 'age' ? 'numbers-and-punctuation' : 'decimal-pad'} placeholder={placeholder} placeholderTextColor={colors.mutedForeground} style={[styles.input, { backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} /></View>;
  return <View style={[styles.root, { backgroundColor: colors.background }]}>
    <Stack.Screen options={{ title: 'Talking Calculator' }} />
    <ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 8, paddingBottom: insets.bottom + 30 }]}>
      <Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>Talking Calculator</Text>
      <Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Accessible calculations with spoken results, screen-reader controls and Nexus Assistant help.</Text>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs} accessibilityLabel="Calculator modes">
        {MODES.map((item) => <Pressable key={item.id} accessibilityRole="tab" accessibilityState={{ selected: mode === item.id }} accessibilityLabel={`${item.label} calculator`} onPress={() => { setMode(item.id); setResult(''); }} style={[styles.tab, { backgroundColor: mode === item.id ? colors.primary : colors.card, borderColor: mode === item.id ? colors.primary : colors.border }]}><Feather name={item.icon as never} size={16} color={mode === item.id ? colors.primaryForeground : colors.foreground} /><Text style={[styles.tabText, { color: mode === item.id ? colors.primaryForeground : colors.foreground }]}>{item.label}</Text></Pressable>)}
      </ScrollView>
      {mode === 'standard' ? <View><View accessibilityLiveRegion="polite" accessible accessibilityRole="summary" accessibilityLabel={`Result ${result || 'Ready'}, expression ${expression || 'empty'}`} style={[styles.display, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.expression, { color: colors.mutedForeground }]}>{expression || '0'}</Text><Text style={[styles.result, { color: colors.foreground }]}>{result || 'Ready'}</Text></View><View style={styles.pad}>{standardButtons.flat().map((key) => <Key key={key} label={key} onPress={() => onStandard(key)} colors={colors} />)}<Key label="C" onPress={() => onStandard('C')} colors={colors} wide /><Key label="⌫" onPress={() => onStandard('⌫')} colors={colors} /><Key label="=" onPress={() => onStandard('=')} colors={colors} /></View></View> : <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>
        {mode === 'age' && field('dob','Date of birth','YYYY-MM-DD')}{mode === 'tip-bill' && <>{field('bill','Bill amount','1000')}{field('tip','Tip percentage','10')}{field('people','Number of people','2')}</>}{mode === 'electricity' && <>{field('units','Units consumed','120')}{field('fixed','Fixed charge','100')}{field('rate','Energy rate per unit','8')}{field('surcharge','Surcharge percentage','0')}</>}{mode === 'fixed-deposit' && <>{field('principal','Principal','100000')}{field('rate','Annual interest rate','7')}{field('years','Tenure in years','5')}{field('compound','Compounds per year','4')}</>}{mode === 'emi' && <>{field('loan','Loan amount','500000')}{field('rate','Annual interest rate','9')}{field('months','Tenure in months','60')}</>}{mode === 'discount' && <>{field('price','Marked price','2000')}{field('discount','Discount percentage','15')}{field('tax','Tax percentage','18')}</>}{mode === 'percentage' && <>{field('number','Number','500')}{field('percent','Percentage','12')}</>}
        <Pressable accessibilityRole="button" accessibilityLabel="Calculate and speak result" onPress={calculate} style={[styles.calculateButton, { backgroundColor: colors.primary }]}><Feather name="volume-2" size={18} color={colors.primaryForeground} /><Text style={[styles.calculateText, { color: colors.primaryForeground }]}>Calculate & Speak</Text></Pressable>
      </View>}
      {result && mode !== 'standard' ? <View accessibilityLiveRegion="polite" accessible accessibilityRole="summary" style={[styles.answer, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.answerLabel, { color: colors.primary }]}>RESULT</Text><Text style={[styles.answerText, { color: colors.foreground }]}>{result}</Text></View> : null}
      <Pressable accessibilityRole="button" accessibilityLabel="Ask Nexus Assistant for calculator help" onPress={() => router.push('/nexus-assistant')} style={[styles.aiCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.aiIcon, { backgroundColor: colors.secondary }]}><Feather name="cpu" size={21} color={colors.primary} /></View><View style={styles.aiCopy}><Text style={[styles.aiTitle, { color: colors.foreground }]}>Ask Nexus Assistant</Text><Text style={[styles.aiText, { color: colors.mutedForeground }]}>Explain a result, compare scenarios, or choose the right calculator. The calculation engine remains deterministic.</Text></View><Feather name="chevron-right" size={18} color={colors.mutedForeground} /></Pressable>
    </ScrollView>
  </View>;
}
function Key({ label, onPress, colors, wide = false }: { label: string; onPress: () => void; colors: ReturnType<typeof useColors>; wide?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={label === '×' ? 'multiply' : label === '÷' ? 'divide' : label} onPress={onPress} style={[styles.key, wide && styles.keyWide, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.keyText, { color: colors.foreground }]}>{label}</Text></Pressable>; }
function formatNumber(value: number | string) { const n = typeof value === 'number' ? value : Number(value); if (!Number.isFinite(n)) throw new Error('Invalid number.'); return Number(n.toFixed(2)).toLocaleString('en-IN'); }
const styles = StyleSheet.create({ root: { flex: 1 }, content: { paddingHorizontal: 18, gap: 14 }, title: { fontSize: 25, fontFamily: 'Inter_700Bold' }, subtitle: { fontSize: 11, lineHeight: 17 }, tabs: { gap: 8, paddingVertical: 2 }, tab: { minHeight: 44, paddingHorizontal: 13, borderRadius: 14, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 6 }, tabText: { fontSize: 11, fontFamily: 'Inter_700Bold' }, display: { minHeight: 150, borderRadius: 18, borderWidth: 1, padding: 16, justifyContent: 'flex-end', alignItems: 'flex-end' }, expression: { fontSize: 18 }, result: { fontSize: 30, fontFamily: 'Inter_700Bold', marginTop: 8 }, pad: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 12 }, key: { width: '22%', minHeight: 58, borderRadius: 15, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, keyWide: { width: '47%' }, keyText: { fontSize: 19, fontFamily: 'Inter_700Bold' }, form: { borderWidth: 1, borderRadius: 18, padding: 14, gap: 11 }, field: { gap: 6 }, label: { fontSize: 11, fontFamily: 'Inter_700Bold' }, input: { minHeight: 48, borderWidth: 1, borderRadius: 13, paddingHorizontal: 13, fontSize: 13 }, calculateButton: { minHeight: 50, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 2 }, calculateText: { fontSize: 12, fontFamily: 'Inter_700Bold' }, answer: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 5 }, answerLabel: { fontSize: 9, letterSpacing: 1.5, fontFamily: 'Inter_700Bold' }, answerText: { fontSize: 16, lineHeight: 23, fontFamily: 'Inter_700Bold' }, aiCard: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: 'row', alignItems: 'center' }, aiIcon: { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, aiCopy: { flex: 1, marginHorizontal: 11 }, aiTitle: { fontSize: 13, fontFamily: 'Inter_700Bold' }, aiText: { fontSize: 10.5, lineHeight: 16, marginTop: 3 } });
