import { Feather } from '@expo/vector-icons';
import * as Speech from 'expo-speech';
import { router, Stack } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { calculateAge, calculateDiscount, calculateElectricity, calculateEmi, calculateFixedDeposit, calculatePercentage, calculateTipBill, evaluateStandard, type CalculatorMode } from '@/features/calculator/calculatorEngine';
import { buildAnalysisRows, calculateCagr, calculateGst, calculateLumpsum, calculateLoanRiskReward, calculateSalaryGrossToNet, calculateSip, calculateTradePnl, detectCalculatorIntent, formatIndianNumber, type CalculatorIntent, type CurrencyQuote, type MarketQuote } from '@/features/calculator/advancedCalculatorEngine';
import { loadCachedLiveData, refreshLiveData } from '@/features/calculator/liveCalculatorData';

const MODES: Array<{ id: CalculatorMode; label: string; icon: string }> = [
  { id: 'standard', label: 'Math', icon: 'hash' }, { id: 'age', label: 'Age', icon: 'user' }, { id: 'tip-bill', label: 'Tip & Bill', icon: 'users' },
  { id: 'electricity', label: 'Electricity', icon: 'zap' }, { id: 'fixed-deposit', label: 'FD', icon: 'briefcase' }, { id: 'emi', label: 'EMI', icon: 'credit-card' },
  { id: 'discount', label: 'Discount', icon: 'tag' }, { id: 'percentage', label: 'Percent', icon: 'percent' },
];
const ADVANCED_TABS: Array<{ id: string; label: string }> = [
  { id: 'smart', label: 'Smart AI' }, { id: 'market', label: 'Market' }, { id: 'investment', label: 'Investment' }, { id: 'salary', label: 'Salary' }, { id: 'currency', label: 'Currency' }, { id: 'tax', label: 'GST & Tax' },
];
function useAnnouncer() { return (text: string) => { void Speech.stop().then(() => Speech.speak(text, { rate: 0.9 })); }; }

export default function CalculatorScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const announce = useAnnouncer();
  const [mode, setMode] = useState<CalculatorMode>('standard'); const [advancedTab, setAdvancedTab] = useState('smart'); const [expression, setExpression] = useState('');
  const [fields, setFields] = useState<Record<string, string>>({}); const [result, setResult] = useState(''); const [analysis, setAnalysis] = useState<Array<{ label: string; value: string }>>([]);
  const [intent, setIntent] = useState<CalculatorIntent>('unknown'); const [currency, setCurrency] = useState<CurrencyQuote | null>(null); const [market, setMarket] = useState<MarketQuote | null>(null); const [liveBusy, setLiveBusy] = useState(false); const [liveStatus, setLiveStatus] = useState('Live feeds are optional and Gateway-backed.');
  const update = (key: string, value: string) => setFields((current) => ({ ...current, [key]: value })); const value = (key: string) => fields[key] ?? '';
  const speak = (text: string) => { setResult(text); announce(text); };
  const standardButtons = useMemo(() => [['7','8','9','÷'],['4','5','6','×'],['1','2','3','-'],['0','.','%','+']], []);

  useEffect(() => { void loadCachedLiveData().then((data) => { setCurrency(data.currency); setMarket(data.market); if (data.fetchedAt) setLiveStatus(`Cached live data from ${new Date(data.fetchedAt).toLocaleString('en-IN')}.`); }); }, []);

  const calculate = () => {
    try {
      let spoken = '';
      let primary = 0;
      switch (mode) {
        case 'standard': primary = evaluateStandard(expression); spoken = formatIndianNumber(primary); break;
        case 'age': { const parts = value('dob').split('-').map(Number); if (parts.length !== 3 || parts.some((n) => !Number.isFinite(n))) throw new Error('Enter date as YYYY-MM-DD.'); const d = new Date(parts[0], parts[1] - 1, parts[2]); if (d.getFullYear() !== parts[0] || d.getMonth() !== parts[1] - 1 || d.getDate() !== parts[2]) throw new Error('Enter a valid date.'); const a = calculateAge(d); spoken = `${a.years} years, ${a.months} months, ${a.days} days`; break; }
        case 'tip-bill': { const r = calculateTipBill(Number(value('bill')), Number(value('tip')), Number(value('people'))); primary = r.total; spoken = `Tip ${formatIndianNumber(r.tip)}, total ${formatIndianNumber(r.total)}, each person ${formatIndianNumber(r.perPerson)}`; break; }
        case 'electricity': { const r = calculateElectricity(Number(value('units')), Number(value('fixed')), Number(value('rate')), Number(value('surcharge'))); primary = r.total; spoken = `Energy ${formatIndianNumber(r.energy)}, surcharge ${formatIndianNumber(r.surcharge)}, total ${formatIndianNumber(r.total)}`; break; }
        case 'fixed-deposit': { const r = calculateFixedDeposit(Number(value('principal')), Number(value('rate')), Number(value('years')), Number(value('compound') || '4')); primary = r.maturity; spoken = `Interest ${formatIndianNumber(r.interest)}, maturity ${formatIndianNumber(r.maturity)}`; break; }
        case 'emi': { const r = calculateEmi(Number(value('loan')), Number(value('rate')), Number(value('months'))); primary = r.emi; spoken = `Monthly EMI ${formatIndianNumber(r.emi)}, total interest ${formatIndianNumber(r.interest)}, total payment ${formatIndianNumber(r.totalPayment)}`; break; }
        case 'discount': { const r = calculateDiscount(Number(value('price')), Number(value('discount')), Number(value('tax'))); primary = r.finalPrice; spoken = `Discount ${formatIndianNumber(r.discount)}, tax ${formatIndianNumber(r.tax)}, final price ${formatIndianNumber(r.finalPrice)}`; break; }
        case 'percentage': { primary = calculatePercentage(Number(value('number')), Number(value('percent'))); spoken = `${formatIndianNumber(value('percent'))} percent of ${formatIndianNumber(value('number'))} is ${formatIndianNumber(primary)}`; break; }
        default: break;
      }
      setAnalysis(primary ? buildAnalysisRows({ result: primary, principal: mode === 'fixed-deposit' ? Number(value('principal')) : undefined, years: mode === 'fixed-deposit' ? Number(value('years')) : undefined, annualInflationPercent: mode === 'fixed-deposit' ? Number(value('inflation') || '6') : undefined }) : []);
      speak(spoken);
    } catch (error) { const message = error instanceof Error ? error.message : 'Check your values.'; Alert.alert('AI Calculator', message); announce(message); }
  };

  const runAdvanced = () => {
    try {
      let spoken = ''; let rows: Array<{ label: string; value: string }> = [];
      if (advancedTab === 'market') { const r = calculateLoanRiskReward(Number(value('entry')), Number(value('stop')), Number(value('target')), Number(value('qty') || '1')); const p = calculateTradePnl(Number(value('entry')), Number(value('exit') || value('target')), Number(value('qty') || '1'), value('side') === 'sell' ? 'sell' : 'buy'); spoken = `Risk ${formatIndianNumber(r.risk)}, reward ${formatIndianNumber(r.reward)}, risk reward ${r.ratio.toFixed(2)} to 1, PNL ${formatIndianNumber(p.pnl)}`; rows = [{ label: 'Risk', value: formatIndianNumber(r.risk) }, { label: 'Reward', value: formatIndianNumber(r.reward) }, { label: 'Risk to reward', value: `${r.ratio.toFixed(2)} to 1` }, { label: 'PNL', value: formatIndianNumber(p.pnl) }]; }
      else if (advancedTab === 'investment') { const kind = value('investmentKind') || 'sip'; if (kind === 'sip') { const r = calculateSip(Number(value('monthly')), Number(value('return')), Number(value('months')), Number(value('stepUp') || '0')); spoken = `Invested ${formatIndianNumber(r.invested)}, gains ${formatIndianNumber(r.gains)}, maturity ${formatIndianNumber(r.maturity)}`; rows = [{ label: 'Invested', value: formatIndianNumber(r.invested) }, { label: 'Gains', value: formatIndianNumber(r.gains) }, { label: 'Maturity', value: formatIndianNumber(r.maturity) }]; } else if (kind === 'cagr') { const r = calculateCagr(Number(value('initial')), Number(value('final')), Number(value('years'))); spoken = `CAGR ${r.toFixed(2)} percent`; rows = [{ label: 'CAGR', value: `${r.toFixed(2)}%` }]; } else { const r = calculateLumpsum(Number(value('initial')), Number(value('return')), Number(value('years'))); spoken = `Invested ${formatIndianNumber(r.invested)}, gains ${formatIndianNumber(r.gains)}, maturity ${formatIndianNumber(r.maturity)}`; rows = [{ label: 'Invested', value: formatIndianNumber(r.invested) }, { label: 'Gains', value: formatIndianNumber(r.gains) }, { label: 'Maturity', value: formatIndianNumber(r.maturity) }]; } }
      else if (advancedTab === 'salary') { const r = calculateSalaryGrossToNet(Number(value('gross')), Number(value('tax')), Number(value('pf')), Number(value('deductions') || '0'), Number(value('employer') || '0')); spoken = `Net monthly ${formatIndianNumber(r.netMonthly)}, annual net ${formatIndianNumber(r.netAnnual)}, annual CTC ${formatIndianNumber(r.annualCtc)}`; rows = [{ label: 'Net monthly', value: formatIndianNumber(r.netMonthly) }, { label: 'Annual net', value: formatIndianNumber(r.netAnnual) }, { label: 'Annual CTC', value: formatIndianNumber(r.annualCtc) }]; }
      else if (advancedTab === 'currency') { const amount = Number(value('amount') || '1'); if (!currency) throw new Error('Refresh live currency data first.'); const converted = amount * currency.rate; spoken = `${formatIndianNumber(amount)} ${currency.base} equals ${formatIndianNumber(converted)} ${currency.quote}`; rows = [{ label: 'Rate', value: `${currency.rate}` }, { label: 'Converted', value: `${formatIndianNumber(converted)} ${currency.quote}` }, { label: 'As of', value: currency.asOf }]; }
      else if (advancedTab === 'tax') { const r = calculateGst(Number(value('taxable')), Number(value('gst')), value('inclusive') === 'yes'); spoken = `Taxable ${formatIndianNumber(r.taxable)}, GST ${formatIndianNumber(r.gst)}, total ${formatIndianNumber(r.total)}`; rows = [{ label: 'Taxable', value: formatIndianNumber(r.taxable) }, { label: 'GST', value: formatIndianNumber(r.gst) }, { label: 'Total', value: formatIndianNumber(r.total) }]; }
      else { const detected = detectCalculatorIntent(value('naturalLanguage')); setIntent(detected); spoken = `Detected module: ${detected}. Use Nexus Assistant to explain, compare scenarios, or process a natural-language calculation.`; rows = [{ label: 'Detected module', value: detected }, { label: 'AI role', value: 'Intent, explanation and what-if analysis' }]; }
      setAnalysis(rows); speak(spoken);
    } catch (error) { const message = error instanceof Error ? error.message : 'Check your advanced inputs.'; Alert.alert('AI Calculator', message); announce(message); }
  };

  const refreshLive = async () => { setLiveBusy(true); setLiveStatus('Refreshing Gateway-backed live feeds…'); try { const data = await refreshLiveData(value('base') || 'USD', value('quote') || 'INR', value('symbol')); setCurrency(data.currency); setMarket(data.market); setLiveStatus(data.error ? `Live refresh partial: ${data.error}` : `Live feeds refreshed at ${new Date().toLocaleTimeString('en-IN')}.`); } finally { setLiveBusy(false); } };
  const field = (key: string, label: string, placeholder: string) => <View style={styles.field}><Text style={[styles.label, { color: colors.foreground }]}>{label}</Text><TextInput accessibilityLabel={label} value={value(key)} onChangeText={(v) => update(key, v)} keyboardType="decimal-pad" placeholder={placeholder} placeholderTextColor={colors.mutedForeground} style={[styles.input, { backgroundColor: colors.card, borderColor: colors.border, color: colors.foreground }]} /></View>;
  const aiContext = JSON.stringify({ mode, advancedTab, result, intent, analysis, currency, market });

  return <View style={[styles.root, { backgroundColor: colors.background }]}>
    <Stack.Screen options={{ title: 'AI Calculator' }} />
    <ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 8, paddingBottom: insets.bottom + 30 }]}>
      <Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>AI Calculator</Text>
      <Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Multi-stage math, market, investment, salary, currency and tax engine. Deterministic formulas stay authoritative; AI explains and explores scenarios.</Text>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs} accessibilityLabel="Calculator modules">
        {ADVANCED_TABS.map((item) => <Pressable key={item.id} accessibilityRole="tab" accessibilityState={{ selected: advancedTab === item.id }} onPress={() => { setAdvancedTab(item.id); setResult(''); setAnalysis([]); }} style={[styles.tab, { backgroundColor: advancedTab === item.id ? colors.primary : colors.card, borderColor: advancedTab === item.id ? colors.primary : colors.border }]}><Text style={[styles.tabText, { color: advancedTab === item.id ? colors.primaryForeground : colors.foreground }]}>{item.label}</Text></Pressable>)}
      </ScrollView>

      <View style={[styles.liveCard, { backgroundColor: colors.card, borderColor: colors.border }]}>
        <View style={styles.row}><View style={styles.copy}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Live data</Text><Text accessibilityLiveRegion="polite" style={[styles.note, { color: colors.mutedForeground }]}>{liveStatus}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Refresh live currency and market data" onPress={refreshLive} disabled={liveBusy} style={[styles.refresh, { backgroundColor: colors.primary }]}><Feather name="refresh-cw" size={16} color={colors.primaryForeground} /></Pressable></View>
        <View style={styles.statusGrid}><Text style={[styles.note, { color: colors.foreground }]}>Currency: {currency ? `${currency.base}/${currency.quote} ${currency.rate}` : 'Not connected'}</Text><Text style={[styles.note, { color: colors.foreground }]}>Market: {market ? `${market.symbol} ${formatIndianNumber(market.price)} (${market.changePercent}%)` : 'Optional'}</Text></View>
      </View>

      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs} accessibilityLabel="Standard calculator tabs">
        {MODES.map((item) => <Pressable key={item.id} accessibilityRole="tab" accessibilityState={{ selected: mode === item.id }} onPress={() => { setMode(item.id); setResult(''); setAnalysis([]); }} style={[styles.tab, { backgroundColor: mode === item.id ? colors.secondary : colors.card, borderColor: mode === item.id ? colors.primary : colors.border }]}><Feather name={item.icon as never} size={16} color={colors.foreground} /><Text style={[styles.tabText, { color: colors.foreground }]}>{item.label}</Text></Pressable>)}
      </ScrollView>

      {mode === 'standard' ? <View><View accessibilityLiveRegion="polite" accessible accessibilityRole="summary" accessibilityLabel={`Result ${result || 'Ready'}, expression ${expression || 'empty'}`} style={[styles.display, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.expression, { color: colors.mutedForeground }]}>{expression || '0'}</Text><Text style={[styles.result, { color: colors.foreground }]}>{result || 'Ready'}</Text></View><View style={styles.pad}>{standardButtons.flat().map((key) => <Key key={key} label={key} onPress={() => { if (key === 'C') { setExpression(''); setResult(''); return; } if (key === '⌫') { setExpression((v) => v.slice(0, -1)); return; } setExpression((v) => `${v}${key}`); announce(key === '÷' ? 'divide' : key === '×' ? 'multiply' : key); }} colors={colors} />)}<Key label="C" onPress={() => { setExpression(''); setResult(''); }} colors={colors} wide /><Key label="⌫" onPress={() => setExpression((v) => v.slice(0, -1))} colors={colors} /><Key label="=" onPress={calculate} colors={colors} /></View></View> : <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{mode === 'age' && field('dob','Date of birth','YYYY-MM-DD')}{mode === 'tip-bill' && <>{field('bill','Bill amount','1000')}{field('tip','Tip percentage','10')}{field('people','Number of people','2')}</>}{mode === 'electricity' && <>{field('units','Units consumed','120')}{field('fixed','Fixed charge','100')}{field('rate','Energy rate per unit','8')}{field('surcharge','Surcharge percentage','0')}</>}{mode === 'fixed-deposit' && <>{field('principal','Principal','100000')}{field('rate','Annual interest rate','7')}{field('years','Tenure in years','5')}{field('compound','Compounds per year','4')}{field('inflation','Inflation assumption','6')}</>}{mode === 'emi' && <>{field('loan','Loan amount','500000')}{field('rate','Annual interest rate','9')}{field('months','Tenure in months','60')}</>}{mode === 'discount' && <>{field('price','Marked price','2000')}{field('discount','Discount percentage','15')}{field('tax','Tax percentage','18')}</>}{mode === 'percentage' && <>{field('number','Number','500')}{field('percent','Percentage','12')}</>}
        <Pressable accessibilityRole="button" onPress={calculate} style={[styles.calculateButton, { backgroundColor: colors.primary }]}><Feather name="volume-2" size={18} color={colors.primaryForeground} /><Text style={[styles.calculateText, { color: colors.primaryForeground }]}>Calculate & Speak</Text></Pressable>
      </View>}

      {advancedTab === 'market' && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{field('entry','Entry price','100')}{field('stop','Stop loss','95')}{field('target','Target','115')}{field('qty','Quantity','10')}{field('exit','Exit price (optional)','115')}{field('side','Side: buy/sell','buy')}<Pressable accessibilityRole="button" onPress={runAdvanced} style={[styles.calculateButton, { backgroundColor: colors.primary }]}><Text style={[styles.calculateText, { color: colors.primaryForeground }]}>Analyze Trade</Text></Pressable></View>}
      {advancedTab === 'investment' && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{field('investmentKind','Type: sip/lumpsum/cagr','sip')}{field('monthly','Monthly SIP','5000')}{field('stepUp','Step-up percentage','10')}{field('initial','Initial value','100000')}{field('final','Final value','180000')}{field('return','Annual return','12')}{field('years','Years','10')}{field('months','Months','120')}<Pressable accessibilityRole="button" onPress={runAdvanced} style={[styles.calculateButton, { backgroundColor: colors.primary }]}><Text style={[styles.calculateText, { color: colors.primaryForeground }]}>Analyze Investment</Text></Pressable></View>}
      {advancedTab === 'salary' && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{field('gross','Monthly gross','100000')}{field('tax','Monthly tax','10000')}{field('pf','Employee PF','5000')}{field('deductions','Other deductions','1000')}{field('employer','Employer contributions','5000')}<Pressable accessibilityRole="button" onPress={runAdvanced} style={[styles.calculateButton, { backgroundColor: colors.primary }]}><Text style={[styles.calculateText, { color: colors.primaryForeground }]}>Track Salary</Text></Pressable></View>}
      {advancedTab === 'currency' && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{field('base','Base currency','USD')}{field('quote','Quote currency','INR')}{field('amount','Amount','1')}<Pressable accessibilityRole="button" onPress={runAdvanced} style={[styles.calculateButton, { backgroundColor: colors.primary }]}><Text style={[styles.calculateText, { color: colors.primaryForeground }]}>Convert Live</Text></Pressable></View>}
      {advancedTab === 'tax' && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{field('taxable','Taxable amount','1000')}{field('gst','GST percentage','18')}{field('inclusive','GST inclusive? yes/no','no')}<Pressable accessibilityRole="button" onPress={runAdvanced} style={[styles.calculateButton, { backgroundColor: colors.primary }]}><Text style={[styles.calculateText, { color: colors.primaryForeground }]}>Calculate GST</Text></Pressable></View>}
      {advancedTab === 'smart' && <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>{field('naturalLanguage','Ask in natural language','Convert 100 USD to INR') }<Pressable accessibilityRole="button" onPress={runAdvanced} style={[styles.calculateButton, { backgroundColor: colors.primary }]}><Feather name="cpu" size={18} color={colors.primaryForeground} /><Text style={[styles.calculateText, { color: colors.primaryForeground }]}>AI Detect & Analyze</Text></Pressable></View>}

      {result ? <View accessibilityLiveRegion="polite" accessible accessibilityRole="summary" style={[styles.answer, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.answerLabel, { color: colors.primary }]}>EXACT ANSWER</Text><Text style={[styles.answerText, { color: colors.foreground }]}>{result}</Text></View> : null}
      {analysis.length ? <View style={[styles.analysis, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Smart analysis</Text>{analysis.map((row) => <View key={row.label} style={styles.analysisRow}><Text style={[styles.note, { color: colors.mutedForeground }]}>{row.label}</Text><Text style={[styles.analysisValue, { color: colors.foreground }]}>{row.value}</Text></View>)}<Text style={[styles.suggestion, { color: colors.mutedForeground }]}>AI suggestions: verify live-source timestamp before financial decisions; compare at least two what-if scenarios before acting.</Text></View> : null}

      <Pressable accessibilityRole="button" accessibilityLabel="Ask Nexus Assistant with current calculator context" onPress={() => router.push({ pathname: '/nexus-assistant', params: { calculatorContext: aiContext } })} style={[styles.aiCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.aiIcon, { backgroundColor: colors.secondary }]}><Feather name="cpu" size={21} color={colors.primary} /></View><View style={styles.aiCopy}><Text style={[styles.aiTitle, { color: colors.foreground }]}>Nexus AI analysis</Text><Text style={[styles.aiText, { color: colors.mutedForeground }]}>Explain this result, compare what-if scenarios, identify the right module, and keep deterministic numbers authoritative.</Text></View><Feather name="chevron-right" size={18} color={colors.mutedForeground} /></Pressable>
    </ScrollView>
  </View>;
}
function Key({ label, onPress, colors, wide = false }: { label: string; onPress: () => void; colors: ReturnType<typeof useColors>; wide?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={label === '×' ? 'multiply' : label === '÷' ? 'divide' : label} onPress={onPress} style={[styles.key, wide && styles.keyWide, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.keyText, { color: colors.foreground }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ root: { flex: 1 }, content: { paddingHorizontal: 18, gap: 14 }, title: { fontSize: 25, fontFamily: 'Inter_700Bold' }, subtitle: { fontSize: 11, lineHeight: 17 }, tabs: { gap: 8, paddingVertical: 2 }, tab: { minHeight: 44, paddingHorizontal: 13, borderRadius: 14, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 6 }, tabText: { fontSize: 11, fontFamily: 'Inter_700Bold' }, liveCard: { borderRadius: 18, borderWidth: 1, padding: 14, gap: 9 }, row: { flexDirection: 'row', alignItems: 'center' }, copy: { flex: 1 }, sectionTitle: { fontSize: 13, fontFamily: 'Inter_700Bold' }, note: { fontSize: 10.5, lineHeight: 16 }, refresh: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, statusGrid: { gap: 4 }, display: { minHeight: 150, borderRadius: 18, borderWidth: 1, padding: 16, justifyContent: 'flex-end', alignItems: 'flex-end' }, expression: { fontSize: 18 }, result: { fontSize: 30, fontFamily: 'Inter_700Bold', marginTop: 8 }, pad: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 12 }, key: { width: '22%', minHeight: 58, borderRadius: 15, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, keyWide: { width: '47%' }, keyText: { fontSize: 19, fontFamily: 'Inter_700Bold' }, form: { borderWidth: 1, borderRadius: 18, padding: 14, gap: 11 }, field: { gap: 6 }, label: { fontSize: 11, fontFamily: 'Inter_700Bold' }, input: { minHeight: 48, borderWidth: 1, borderRadius: 13, paddingHorizontal: 13, fontSize: 13 }, calculateButton: { minHeight: 50, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 2 }, calculateText: { fontSize: 12, fontFamily: 'Inter_700Bold' }, answer: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 5 }, answerLabel: { fontSize: 9, letterSpacing: 1.5, fontFamily: 'Inter_700Bold' }, answerText: { fontSize: 16, lineHeight: 23, fontFamily: 'Inter_700Bold' }, analysis: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 9 }, analysisRow: { gap: 2 }, analysisValue: { fontSize: 14, fontFamily: 'Inter_700Bold' }, suggestion: { marginTop: 5, fontSize: 10.5, lineHeight: 16 }, aiCard: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: 'row', alignItems: 'center' }, aiIcon: { width: 44, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, aiCopy: { flex: 1, marginHorizontal: 11 }, aiTitle: { fontSize: 13, fontFamily: 'Inter_700Bold' }, aiText: { fontSize: 10.5, lineHeight: 16, marginTop: 3 } });
