import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import * as DocumentPicker from 'expo-document-picker';
import { Stack, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, BackHandler, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { PdfNativeBridge } from '@/features/pdf-native/PdfNativeBridge';
import { preparePdfOutputPath } from '@/features/pdf-native/pdfPageOperations';
import { PdfToolResultPanel } from '@/features/pdf-native/PdfToolResultPanel';

type Pdf = { uri: string; name: string };
function safeBaseName(name: string): string { return name.replace(/\.pdf$/i, '').replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 128) || 'document'; }

export default function CompressPdfScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets();
  const [pdf, setPdf] = useState<Pdf | null>(null); const [result, setResult] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [status, setStatus] = useState('');
  async function pickPdf() { const picked = await DocumentPicker.getDocumentAsync({ type: 'application/pdf', multiple: false, copyToCacheDirectory: true }); if (picked.canceled || !picked.assets?.[0]) return; setPdf({ uri: picked.assets[0].uri, name: picked.assets[0].name || 'document.pdf' }); setResult(null); setStatus('PDF selected.'); }
  async function compress() { if (!pdf) { setStatus('Select a PDF first.'); return; } setBusy(true); setResult(null); setStatus('Compressing PDF…'); try { const output = await preparePdfOutputPath('Compress PDFs', `${safeBaseName(pdf.name)}-compressed.pdf`); const uri = await PdfNativeBridge.compress(pdf.uri, output, 75); setResult(uri); setStatus('PDF compression completed and the file was saved.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not compress this PDF.'); } finally { setBusy(false); } }
  function reset() { setPdf(null); setResult(null); setStatus(''); }
  useFocusEffect(useCallback(() => { const sub = BackHandler.addEventListener('hardwareBackPress', () => { if (!pdf && !result && !busy) return false; reset(); return false; }); return () => sub.remove(); }, [busy, pdf, result]));
  return <View style={[styles.root, { backgroundColor: colors.background }]}><Stack.Screen options={{ title: 'Compress PDF' }} />{busy ? <View style={styles.loading}><ActivityIndicator size="large" color={colors.primary} /><Text accessibilityRole="header" style={[styles.loadingTitle, { color: colors.foreground }]}>Compressing PDF</Text><Text accessibilityLiveRegion="polite" style={[styles.loadingText, { color: colors.mutedForeground }]}>{status}</Text></View> : <ScrollView contentContainerStyle={{ paddingTop: insets.top + 18, paddingBottom: insets.bottom + 40 }} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={[styles.icon, { backgroundColor: colors.secondary }]}><MaterialCommunityIcons name="file-move-outline" size={28} color={colors.primary} /></View><View style={styles.copy}><Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>Compress PDF</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Create a smaller copy of a PDF and save it to Nexus Plus.</Text></View></View>
    <Pressable accessibilityRole="button" accessibilityLabel={pdf ? `Selected PDF ${pdf.name}` : 'Choose PDF'} onPress={() => void pickPdf()} style={({ pressed }) => [styles.pick, { backgroundColor: colors.card, borderColor: colors.border }, pressed && styles.pressed]}><Feather name="file-plus" size={20} color={colors.primary} /><View style={styles.pickCopy}><Text style={[styles.pickTitle, { color: colors.foreground }]}>{pdf ? pdf.name : 'Choose PDF'}</Text><Text style={[styles.pickDetail, { color: colors.mutedForeground }]}>{pdf ? 'Ready to compress' : 'Select a local PDF file'}</Text></View><Feather name="chevron-right" size={18} color={colors.mutedForeground} /></Pressable>
    {!result && <Pressable accessibilityRole="button" accessibilityLabel="Compress PDF" onPress={() => void compress()} disabled={!pdf} style={({ pressed }) => [styles.primary, { backgroundColor: colors.primary }, (pressed || !pdf) && styles.disabled]}><MaterialCommunityIcons name="arrow-collapse" size={19} color={colors.primaryForeground} /><Text style={[styles.primaryText, { color: colors.primaryForeground }]}>Compress PDF</Text></Pressable>}
    {!!status && <Text accessibilityLiveRegion="polite" style={[styles.status, { color: status.includes('completed') ? colors.primary : colors.mutedForeground }]}>{status}</Text>}
    <PdfToolResultPanel resultUri={result} filename={result ? `${safeBaseName(pdf?.name ?? 'document')}-compressed.pdf` : undefined} onClose={reset} onReset={reset} title="Compression completed" />
  </ScrollView>}</View>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, marginBottom: 22 }, icon: { width: 54, height: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, marginLeft: 13 }, title: { fontSize: 28, fontFamily: 'Inter_700Bold', marginBottom: 5 }, subtitle: { fontSize: 12, lineHeight: 18 }, pick: { marginHorizontal: 20, minHeight: 72, borderWidth: 1, borderRadius: 16, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' }, pickCopy: { flex: 1, marginHorizontal: 12 }, pickTitle: { fontSize: 13, fontFamily: 'Inter_700Bold', marginBottom: 4 }, pickDetail: { fontSize: 11 }, primary: { marginHorizontal: 20, marginTop: 16, minHeight: 52, borderRadius: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, primaryText: { fontSize: 14, fontFamily: 'Inter_700Bold' }, status: { marginHorizontal: 20, marginTop: 16, fontSize: 11, lineHeight: 17 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 30 }, loadingTitle: { fontSize: 22, fontFamily: 'Inter_700Bold', marginTop: 22, marginBottom: 8 }, loadingText: { fontSize: 13, lineHeight: 19, textAlign: 'center' }, pressed: { opacity: 0.75 }, disabled: { opacity: 0.5 } });