import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { Stack, useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { convertOfficeDocumentWithExistingGotenberg } from '@/features/pdf-word/pdfWordConversion';
import { saveDocumentRecord } from '@/features/document-studio/documentStore';
import { documentIdFor, sanitizeDocumentName } from '@/features/document-studio/documentTypes';
import { documentHaptic } from '@/features/document-studio/documentFeedback';

export default function DocumentCreatorScreen(){
 const colors=useColors(),insets=useSafeAreaInsets(),router=useRouter();
 const [title,setTitle]=useState('Untitled Document'),[body,setBody]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[savedUri,setSavedUri]=useState<string|null>(null);
 const saveText=async()=>{if(!title.trim()||!body.trim()){setStatus('Enter a title and document text first.');return;}setBusy(true);try{const dir=FileSystem.documentDirectory+'Document Studio/';await FileSystem.makeDirectoryAsync(dir,{intermediates:true});const uri=dir+sanitizeDocumentName(title)+'.txt';await FileSystem.writeAsStringAsync(uri,title.trim()+'\n\n'+body.trim());await saveDocumentRecord({id:documentIdFor(uri,title),title:title.trim(),uri,mimeType:'text/plain',format:'txt',source:'created',textPreview:body.trim().slice(0,2000),createdAt:Date.now(),updatedAt:Date.now()});setSavedUri(uri);setStatus('Document saved automatically to Document Studio.');await documentHaptic('success');}catch(e){setStatus(e instanceof Error?e.message:'Document could not be saved.');await documentHaptic('error')}finally{setBusy(false)}};
 const exportPdf=async()=>{if(!title.trim()||!body.trim()){setStatus('Enter a title and document text first.');return;}setBusy(true);try{const dir=FileSystem.documentDirectory+'Document Studio/';await FileSystem.makeDirectoryAsync(dir,{intermediates:true});const safe=sanitizeDocumentName(title);const html=dir+safe+'.html';await FileSystem.writeAsStringAsync(html,'<!doctype html><html><body><h1>'+title.trim().replace(/[&<>]/g,'')+'</h1><p>'+body.trim().replace(/[&<>]/g,'').replace(/\n/g,'<br/>')+'</p></body></html>');const pdf=await convertOfficeDocumentWithExistingGotenberg(html,safe+'.pdf','text/html');await saveDocumentRecord({id:documentIdFor(pdf,title),title:title.trim()+'.pdf',uri:pdf,mimeType:'application/pdf',format:'pdf',source:'converted',createdAt:Date.now(),updatedAt:Date.now()});setSavedUri(pdf);setStatus('PDF created and saved to Document Studio.');await documentHaptic('success');}catch(e){setStatus(e instanceof Error?e.message:'PDF export failed.');await documentHaptic('error')}finally{setBusy(false)}};
 const share=async()=>{if(!savedUri)return;if(!(await Sharing.isAvailableAsync())){setStatus('Sharing is not available on this device.');return;}await Sharing.shareAsync(savedUri)};
 return <View style={[styles.root,{backgroundColor:colors.background}]}><Stack.Screen options={{title:'Document Creator'}}/><ScrollView contentContainerStyle={{paddingTop:insets.top+12,paddingBottom:insets.bottom+36,paddingHorizontal:20}}><Text accessibilityRole="header" style={[styles.title,{color:colors.foreground}]}>Document Creator</Text><Text style={[styles.subtitle,{color:colors.mutedForeground}]}>Create, automatically save, share and send the document to Reader tools.</Text><Text style={[styles.label,{color:colors.foreground}]}>Title</Text><TextInput value={title} onChangeText={setTitle} editable={!busy} style={[styles.input,{color:colors.foreground,backgroundColor:colors.card,borderColor:colors.border}]}/><Text style={[styles.label,{color:colors.foreground}]}>Content</Text><TextInput value={body} onChangeText={setBody} multiline textAlignVertical="top" editable={!busy} style={[styles.editor,{color:colors.foreground,backgroundColor:colors.card,borderColor:colors.border}]}/><Pressable disabled={busy} onPress={()=>void saveText()} style={[styles.primary,{backgroundColor:colors.primary}] }><Feather name="save" size={18} color={colors.primaryForeground}/><Text style={{color:colors.primaryForeground,fontFamily:'Inter_700Bold'}}>Save Document</Text></Pressable><Pressable disabled={busy} onPress={()=>void exportPdf()} style={[styles.secondary,{borderColor:colors.border}]}><MaterialCommunityIcons name="file-pdf-box" size={19} color={colors.foreground}/><Text style={{color:colors.foreground,fontFamily:'Inter_700Bold'}}>Create PDF</Text></Pressable>{savedUri&&<><Pressable onPress={()=>router.push({pathname:'/document-reader',params:{documentId:documentIdFor(savedUri,title)}})} style={[styles.secondary,{borderColor:colors.border}]}><Feather name="book-open" size={18} color={colors.foreground}/><Text style={{color:colors.foreground,fontFamily:'Inter_700Bold'}}>Open in Document Reader</Text></Pressable><Pressable onPress={share} style={[styles.secondary,{borderColor:colors.border}]}><Feather name="share-2" size={18} color={colors.foreground}/><Text style={{color:colors.foreground,fontFamily:'Inter_700Bold'}}>Share</Text></Pressable></>}{!!status&&<Text accessibilityLiveRegion="polite" style={[styles.status,{color:colors.mutedForeground}]}>{status}</Text>}</ScrollView></View>
}
const styles=StyleSheet.create({root:{flex:1},title:{fontSize:27,fontFamily:'Inter_700Bold',marginBottom:6},subtitle:{fontSize:12,lineHeight:18,marginBottom:18},label:{fontSize:12,fontFamily:'Inter_700Bold',marginTop:12,marginBottom:7},input:{minHeight:50,borderWidth:1,borderRadius:14,paddingHorizontal:13},editor:{minHeight:260,borderWidth:1,borderRadius:16,padding:14,lineHeight:20},primary:{minHeight:50,borderRadius:14,marginTop:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},secondary:{minHeight:50,borderRadius:14,borderWidth:1,marginTop:10,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},status:{marginTop:14,fontSize:11,lineHeight:17}});