import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { useAudioPlayer } from 'expo-audio';
import * as FileSystem from 'expo-file-system/legacy';
import { Stack, useRouter } from 'expo-router';
import { useRef, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { PdfNativeBridge } from '@/features/pdf-native/PdfNativeBridge';
import { saveDocumentRecord } from '@/features/document-studio/documentStore';
import { documentIdFor, sanitizeDocumentName } from '@/features/document-studio/documentTypes';
import { documentHaptic } from '@/features/document-studio/documentFeedback';

const SCAN_SOUND = require('../assets/audio/document processing.mp3');

export default function DocumentScannerScreen(){
 const colors=useColors(),insets=useSafeAreaInsets(),router=useRouter(),player=useAudioPlayer(SCAN_SOUND);
 const cameraRef=useRef<CameraView|null>(null),[permission,requestPermission]=useCameraPermissions();
 const [pages,setPages]=useState<string[]>([]),[scanning,setScanning]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 const feedback=async(kind:'tap'|'success'|'error')=>{try{player.seekTo(0);player.play()}catch{};await documentHaptic(kind)};
 const start=async()=>{if(!permission?.granted){const next=await requestPermission();if(!next.granted){setStatus('Camera permission is required.');await feedback('error');return}}setScanning(true);await feedback('tap')};
 const capture=async()=>{setBusy(true);try{const photo=await cameraRef.current?.takePictureAsync({quality:1,skipProcessing:false});if(!photo?.uri)throw new Error('Camera did not return an image.');setPages(p=>[...p,photo.uri]);setStatus('Page captured. Add another page or finish the scan.');await feedback('success')}catch(e){setStatus(e instanceof Error?e.message:'Page capture failed.');await feedback('error')}finally{setBusy(false)}};
 const finish=async()=>{if(!pages.length){setStatus('Capture at least one page first.');return}setBusy(true);try{const dir=FileSystem.cacheDirectory+'nexus-scan-'+Date.now()+'/';await FileSystem.makeDirectoryAsync(dir,{intermediates:true});const copies:string[]=[];for(let i=0;i<pages.length;i++){const p=dir+'page-'+String(i+1).padStart(3,'0')+'.jpg';await FileSystem.copyAsync({from:pages[i],to:p});copies.push(p)}const output=FileSystem.documentDirectory+'Document Studio/Scans/scan-'+Date.now()+'.pdf';await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory+'Document Studio/Scans/',{intermediates:true});const pdf=await PdfNativeBridge.imageToPdf(copies,output,90);const record={id:documentIdFor(pdf,'Scan '+new Date().toLocaleString()),title:'Scanned Document '+new Date().toLocaleString(),uri:pdf,mimeType:'application/pdf',format:'pdf',source:'scanned' as const,createdAt:Date.now(),updatedAt:Date.now()};await saveDocumentRecord(record);setStatus('Scan saved as a multi-page PDF and added to Document Studio.');await feedback('success');setScanning(false);setPages([]);router.push({pathname:'/document-reader',params:{documentId:record.id}})}catch(e){setStatus(e instanceof Error?e.message:'Could not create scanned PDF.');await feedback('error')}finally{setBusy(false)}};
 return <View style={[styles.root,{backgroundColor:colors.background}]}><Stack.Screen options={{title:'Document Scanner'}}/><ScrollView contentContainerStyle={{paddingTop:insets.top+12,paddingBottom:insets.bottom+36}}>{scanning?<View style={styles.card}><View style={styles.preview}><CameraView ref={v=>{cameraRef.current=v}} style={StyleSheet.absoluteFill} facing="back"/><View pointerEvents="none" style={styles.frame}/></View><Pressable disabled={busy} onPress={()=>void capture()} style={[styles.primary,{backgroundColor:colors.primary}]}>{busy?<ActivityIndicator color={colors.primaryForeground}/>:<MaterialCommunityIcons name="camera-outline" size={20} color={colors.primaryForeground}/>}<Text style={{color:colors.primaryForeground,fontFamily:'Inter_700Bold'}}>Capture Page</Text></Pressable><Pressable disabled={busy||!pages.length} onPress={()=>void finish()} style={[styles.secondary,{borderColor:colors.border}]}><Feather name="check" size={18} color={colors.foreground}/><Text style={{color:colors.foreground,fontFamily:'Inter_700Bold'}}>Finish & Save PDF ({pages.length})</Text></Pressable></View>:<View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><MaterialCommunityIcons name="scanner" size={54} color={colors.primary}/><Text style={[styles.title,{color:colors.foreground}]}>Document Scanner</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>Capture multiple pages and save one real PDF in Document Studio. The result is linked to Reader, Summarizer and Translator.</Text><Pressable onPress={()=>void start()} style={[styles.primary,{backgroundColor:colors.primary}]}><Feather name="camera" size={18} color={colors.primaryForeground}/><Text style={{color:colors.primaryForeground,fontFamily:'Inter_700Bold'}}>Start Scanner</Text></Pressable></View>}{!!pages.length&&!scanning&&<Text style={[styles.body,{color:colors.mutedForeground}]}>{pages.length} pages captured.</Text>}{!!status&&<Text accessibilityLiveRegion="polite" style={[styles.status,{color:colors.mutedForeground}]}>{status}</Text>}</ScrollView></View>}
const styles=StyleSheet.create({root:{flex:1},card:{margin:20,borderWidth:1,borderRadius:20,padding:14,alignItems:'center'},preview:{width:'100%',aspectRatio:.75,overflow:'hidden',borderRadius:16,backgroundColor:'#222',position:'relative'},frame:{position:'absolute',left:'9%',top:'10%',width:'82%',height:'78%',borderWidth:2,borderColor:'#fff',borderRadius:12},primary:{minHeight:50,borderRadius:14,marginTop:12,width:'100%',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},secondary:{minHeight:50,borderRadius:14,marginTop:10,width:'100%',borderWidth:1,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},title:{fontSize:25,fontFamily:'Inter_700Bold',marginTop:10},body:{fontSize:12,lineHeight:19,marginTop:8,textAlign:'center'},status:{margin:20,fontSize:11,lineHeight:17}});
