import { Feather } from '@expo/vector-icons';
import * as DocumentPicker from 'expo-document-picker';
import { Stack, useRouter, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { getDocumentRecord, saveDocumentRecord } from '@/features/document-studio/documentStore';
import { ensureDocumentText } from '@/features/document-studio/documentText';
import { shareDocument } from '@/features/document-studio/documentActions';
import { documentIdFor } from '@/features/document-studio/documentTypes';
import { describeDocument } from '@/features/document-reader/documentReaderFormat';

export default function DocumentReaderScreen(){
 const colors=useColors(),insets=useSafeAreaInsets(),router=useRouter(),params=useLocalSearchParams<{documentId?:string}>();
 const [doc,setDoc]=useState<any>(null),[text,setText]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const load=async(d?:any)=>{const next=d|| (params.documentId?await getDocumentRecord(String(params.documentId)):null);if(next){setDoc(next);setBusy(true);try{setText((await ensureDocumentText(next)).slice(0,120000));}catch(e){setStatus(e instanceof Error?e.message:'Unable to read this document.')}finally{setBusy(false)}}};
 useEffect(()=>{void load()},[params.documentId]);
 const pick=async()=>{const p=await DocumentPicker.getDocumentAsync({multiple:false,copyToCacheDirectory:true,type:['application/pdf','application/epub+zip','text/plain','text/markdown','text/html','application/rtf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.oasis.opendocument.text']});if(p.canceled||!p.assets?.[0])return;const a=p.assets[0],d=describeDocument(a.uri,a.name||'document',a.mimeType,a.size),record={id:documentIdFor(a.uri,a.name||'document'),title:a.name||'document',uri:a.uri,mimeType:a.mimeType||'application/octet-stream',format:d.format,sizeBytes:a.size,source:'imported' as const,createdAt:Date.now(),updatedAt:Date.now()};await saveDocumentRecord(record);router.replace({pathname:'/document-reader',params:{documentId:record.id}})};
 return <View style={[styles.root,{backgroundColor:colors.background}]}><Stack.Screen options={{title:'Document Reader'}}/><ScrollView contentContainerStyle={{paddingTop:insets.top+12,paddingBottom:insets.bottom+36,paddingHorizontal:20}}><Text accessibilityRole="header" style={[styles.title,{color:colors.foreground}]}>Document Reader</Text><Text style={[styles.subtitle,{color:colors.mutedForeground}]}>Read the selected document text and move directly to other document tools.</Text><Pressable onPress={()=>void pick()} style={[styles.secondary,{borderColor:colors.border}]}><Feather name="upload" size={18} color={colors.foreground}/><Text style={{color:colors.foreground,fontFamily:'Inter_700Bold'}}>Open another document</Text></Pressable>{doc&&<Text style={[styles.docTitle,{color:colors.foreground}]}>{doc.title}</Text>}{busy?<View style={styles.loading}><ActivityIndicator color={colors.primary}/><Text style={[styles.body,{color:colors.mutedForeground}]}>Reading document…</Text></View>:<Text selectable accessibilityLabel="Document text" style={[styles.body,{color:colors.foreground}]}>{text||status||'No readable text was found.'}</Text>}<View style={styles.actions}>{doc&&<><Pressable onPress={()=>void shareDocument(doc).catch(e=>setStatus(e instanceof Error?e.message:'Share failed'))} style={[styles.action,{backgroundColor:colors.primary}]}><Feather name="share-2" size={17} color={colors.primaryForeground}/><Text style={{color:colors.primaryForeground}}>Share</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/document-summarizer',params:{documentId:doc.id}})} style={[styles.action,{borderColor:colors.border}]}><Feather name="file-text" size={17} color={colors.primary}/><Text style={{color:colors.foreground}}>Summarize</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/document-translator',params:{documentId:doc.id}})} style={[styles.action,{borderColor:colors.border}]}><Feather name="globe" size={17} color={colors.primary}/><Text style={{color:colors.foreground}}>Translate</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/document-book-reader',params:{documentId:doc.id}})} style={[styles.action,{borderColor:colors.border}]}><Feather name="volume-2" size={17} color={colors.primary}/><Text style={{color:colors.foreground}}>Read with Book Reader</Text></Pressable></>}</View>{!!status&&<Text accessibilityLiveRegion="polite" style={[styles.status,{color:colors.mutedForeground}]}>{status}</Text>}</ScrollView></View>}
const styles=StyleSheet.create({root:{flex:1},title:{paddingHorizontal:0,fontSize:27,fontFamily:'Inter_700Bold'},subtitle:{fontSize:12,lineHeight:18,marginTop:5,marginBottom:14},secondary:{minHeight:48,borderWidth:1,borderRadius:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},docTitle:{fontSize:18,fontFamily:'Inter_700Bold',marginTop:18,marginBottom:9},body:{fontSize:13,lineHeight:21},loading:{alignItems:'center',gap:8,padding:20},actions:{gap:9,marginTop:17},action:{minHeight:48,borderRadius:13,borderWidth:1,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},status:{marginTop:12,fontSize:11,lineHeight:17}});
