import { Feather } from '@expo/vector-icons';
import * as FileSystem from 'expo-file-system/legacy';
import { Stack, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { getDocumentRecord } from '@/features/document-studio/documentStore';
import { ensureDocumentText } from '@/features/document-studio/documentText';

type NativeTranslation = { getAvailableLanguages?:()=>Promise<string[]>; downloadModel:(source:string,target:string)=>Promise<void>; translate:(text:string,source:string,target:string)=>Promise<string> };
function bridge():NativeTranslation|undefined{return (globalThis as typeof globalThis & { NexusTranslation?: NativeTranslation }).NexusTranslation}
export default function DocumentTranslatorScreen(){
 const colors=useColors(),params=useLocalSearchParams<{documentId?:string}>();const [doc,setDoc]=useState<any>(null),[text,setText]=useState(''),[translated,setTranslated]=useState(''),[source,setSource]=useState('auto'),[target,setTarget]=useState('en'),[langs,setLangs]=useState<string[]>(['en','hi']),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{(async()=>{if(!params.documentId)return;const d=await getDocumentRecord(String(params.documentId));if(!d)return;setDoc(d);try{setText((await ensureDocumentText(d)).slice(0,50000))}catch(e){setStatus(e instanceof Error?e.message:'Unable to load document text.')}const b=bridge();if(b?.getAvailableLanguages){try{const list=await b.getAvailableLanguages();if(list.length)setLangs(list)}catch{}}})()},[params.documentId]);
 const targets=useMemo(()=>langs.filter(l=>l!==source),[langs,source]);
 const translate=async()=>{if(!text.trim())return;const b=bridge();if(!b){setStatus('On-device translation engine is not included in this build yet. No remote translation is used as a fallback.');return;}setBusy(true);try{const src=source==='auto'?'en':source;await b.downloadModel(src,target);setTranslated(await b.translate(text,src,target))}catch(e){setStatus(e instanceof Error?e.message:'On-device translation failed.')}finally{setBusy(false)}};
 return <View style={[styles.root,{backgroundColor:colors.background}]}><Stack.Screen options={{title:'Document Translator'}}/><ScrollView contentContainerStyle={styles.content}><Text accessibilityRole="header" style={[styles.title,{color:colors.foreground}]}>Document Translator</Text><Text style={[styles.subtitle,{color:colors.mutedForeground}]}>Uses the on-device translation bridge and downloaded device language models. No remote translation fallback is used.</Text><Text style={[styles.label,{color:colors.foreground}]}>Source language</Text><TextInput value={source} onChangeText={setSource} style={[styles.input,{color:colors.foreground,borderColor:colors.border,backgroundColor:colors.card}]} accessibilityLabel="Source language code"/><Text style={[styles.label,{color:colors.foreground}]}>Target language</Text><View style={styles.langs}>{targets.slice(0,8).map(l=><Pressable key={l} onPress={()=>setTarget(l)} style={[styles.lang,{backgroundColor:l===target?colors.primary:colors.card,borderColor:colors.border}]}><Text style={{color:l===target?colors.primaryForeground:colors.foreground}}>{l}</Text></Pressable>)}</View><Pressable onPress={translate} disabled={busy||!text} style={[styles.button,{backgroundColor:colors.primary}]}>{busy?<ActivityIndicator color={colors.primaryForeground}/>:<Feather name="globe" size={18} color={colors.primaryForeground}/>}<Text style={{color:colors.primaryForeground,fontFamily:'Inter_700Bold'}}>Translate Document</Text></Pressable><TextInput value={text} onChangeText={setText} multiline style={[styles.editor,{color:colors.foreground,borderColor:colors.border,backgroundColor:colors.card}]} accessibilityLabel="Source document text"/>{translated?<Text selectable style={[styles.output,{color:colors.foreground}]}>{translated}</Text>:null}<Text style={[styles.status,{color:colors.mutedForeground}]}>{status}</Text></ScrollView></View>}
const styles=StyleSheet.create({root:{flex:1},content:{padding:20},title:{fontSize:26,fontFamily:'Inter_700Bold'},subtitle:{fontSize:12,lineHeight:18,marginTop:5},label:{fontSize:12,fontFamily:'Inter_700Bold',marginTop:15,marginBottom:7},input:{minHeight:46,borderWidth:1,borderRadius:12,paddingHorizontal:12},langs:{flexDirection:'row',flexWrap:'wrap',gap:8},lang:{minHeight:40,borderWidth:1,borderRadius:10,paddingHorizontal:12,alignItems:'center',justifyContent:'center'},button:{minHeight:50,borderRadius:13,marginTop:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},editor:{minHeight:220,borderWidth:1,borderRadius:14,padding:12,marginTop:16},output:{fontSize:14,lineHeight:22,marginTop:16},status:{fontSize:11,lineHeight:17,marginTop:12}});
