import { Feather } from '@expo/vector-icons';
import { Stack, useRouter } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { getAssistantModelPreference, setAssistantModelPreference, type AssistantModelId } from '@/features/nexus-assistant/aiModelPreferences';
import { getAssistantVoicePreference, setAssistantVoicePreference, type AssistantVoiceMode } from '@/features/nexus-assistant/assistantVoicePreferences';
import { getInstalledVoices, downloadVoice, type InstalledVoice } from '@/features/voice-library/voiceStore';
import { UNIQUE_VOICE_CATALOG } from '@/features/voice-library/voiceCatalog';
import { getHistoryEnabled, setHistoryEnabled } from '@/features/nexus-assistant/assistantStore';

const MODELS = [
  {id:'gemini',name:'Gemini',cost:'1 credit'},
  {id:'openai',name:'OpenAI',cost:'4 credits'},
  {id:'anthropic',name:'Claude',cost:'6 credits'},
] as const;

export default function NexusAiSettingsScreen(){
 const colors=useColors(); const router=useRouter(); const insets=useSafeAreaInsets();
 const [selected,setSelected]=useState<AssistantModelId>('gemini');
 const [voiceId,setVoiceId]=useState('en-us-amy-medium');
 const [voiceMode,setVoiceMode]=useState<AssistantVoiceMode>('local');
 const [installed,setInstalled]=useState<InstalledVoice[]>([]);
 const [historyEnabled,setHistoryEnabledState]=useState(true);
 const [loading,setLoading]=useState(true);
 const [downloading,setDownloading]=useState<string|null>(null);
 const localVoices=useMemo(()=>UNIQUE_VOICE_CATALOG.filter(v=>v.roles?.includes('live-call')||v.roles?.includes('assistant')),[]);

 const refreshVoices=async()=>setInstalled(await getInstalledVoices());
 useEffect(()=>{void (async()=>{const model=await getAssistantModelPreference();const voice=await getAssistantVoicePreference();const history=await getHistoryEnabled();setSelected(model.selectedModel);setVoiceId(voice.voiceId);setVoiceMode(voice.mode);setHistoryEnabledState(history);await refreshVoices();setLoading(false);})();},[]);

 const chooseVoice=async(id:string)=>{setVoiceId(id);setVoiceMode('local');await setAssistantVoicePreference({voiceId:id,mode:'local'});};
 const useDevice=async()=>{setVoiceMode('device');await setAssistantVoicePreference({voiceId,mode:'device'});};
 const downloadSelected=async(id:string)=>{const item=UNIQUE_VOICE_CATALOG.find(v=>v.id===id);if(!item)return;setDownloading(id);try{await downloadVoice(item);await refreshVoices();setVoiceMode('local');await setAssistantVoicePreference({voiceId:id,mode:'local'});}catch{Alert.alert('Voice download','The voice could not be downloaded right now. You can use your device voice instead.');}finally{setDownloading(null);}};
 const selectedInstalled=installed.some(v=>v.id===voiceId);
 const toggleHistory=async()=>{const next=!historyEnabled;setHistoryEnabledState(next);await setHistoryEnabled(next);};

 return <ScrollView style={[styles.root,{backgroundColor:colors.background}]} contentContainerStyle={{padding:18,paddingTop:insets.top+10,paddingBottom:insets.bottom+30}}>
  <Stack.Screen options={{title:'Nexus Assistant Settings'}}/>
  <View style={styles.header}><Pressable accessibilityRole='button' accessibilityLabel='Back' onPress={()=>router.back()} style={[styles.back,{backgroundColor:colors.card,borderColor:colors.border}]}><Feather name='arrow-left' size={19} color={colors.foreground}/></Pressable><View style={styles.copy}><Text accessibilityRole='header' style={[styles.title,{color:colors.foreground}]}>Nexus Assistant Settings</Text><Text style={[styles.subtitle,{color:colors.mutedForeground}]}>Settings for Nexus Assistant only.</Text></View></View>

  <View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[styles.section,{color:colors.foreground}]}>Select Model</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>Choose the model Nexus Assistant uses for cloud answers.</Text><View style={styles.list}>{MODELS.map(model=><Pressable key={model.id} accessibilityRole='radio' accessibilityState={{selected:selected===model.id}} onPress={async()=>{setSelected(model.id);await setAssistantModelPreference(model.id);}} style={[styles.item,{borderColor:selected===model.id?colors.primary:colors.border,backgroundColor:selected===model.id?colors.secondary:colors.background}]}><View style={[styles.radio,{borderColor:selected===model.id?colors.primary:colors.mutedForeground}]}>{selected===model.id?<View style={[styles.dot,{backgroundColor:colors.primary}]}/>:null}</View><View style={styles.copy}><Text style={[styles.name,{color:colors.foreground}]}>{model.name}</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>{model.cost} per cloud request</Text></View>{selected===model.id?<Feather name='check-circle' size={18} color={colors.primary}/>:null}</Pressable>)}</View></View>

  <View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[styles.section,{color:colors.foreground}]}>Select Voice</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>Only local Nexus voices are used here. ElevenLabs stays in the TTS settings.</Text>{loading?<ActivityIndicator color={colors.primary}/>:<View style={styles.list}>{localVoices.map(voice=>{const active=voice.id===voiceId;const ready=installed.some(v=>v.id===voice.id);return <View key={voice.id} style={[styles.voiceBlock,{borderColor:active?colors.primary:colors.border,backgroundColor:active?colors.secondary:colors.background}]}><Pressable accessibilityRole='radio' accessibilityState={{selected:active}} onPress={()=>void chooseVoice(voice.id)} style={styles.voiceRow}><Feather name='volume-2' size={18} color={colors.primary}/><View style={styles.copy}><Text style={[styles.name,{color:colors.foreground}]}>{voice.name}</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>{voice.languageName} • {voice.gender === 'female' ? 'Female' : 'Male'}</Text></View>{active?<Feather name='check-circle' size={18} color={colors.primary}/>:null}</Pressable>{active&&!ready&&voiceMode==='local'?<Pressable accessibilityRole='button' disabled={downloading===voice.id} onPress={()=>void downloadSelected(voice.id)} style={[styles.smallButton,{borderColor:colors.primary}]}>{downloading===voice.id?<ActivityIndicator color={colors.primary}/>:<><Feather name='download' size={15} color={colors.primary}/><Text style={[styles.smallButtonText,{color:colors.primary}]}>Download Voice</Text></>}</Pressable>:null}</View>})}</View>}<Pressable accessibilityRole='button' accessibilityState={{selected:voiceMode==='device'}} onPress={()=>void useDevice()} style={[styles.deviceRow,{borderColor:voiceMode==='device'?colors.primary:colors.border,backgroundColor:voiceMode==='device'?colors.secondary:colors.background}]}><Feather name='smartphone' size={18} color={colors.primary}/><View style={styles.copy}><Text style={[styles.name,{color:colors.foreground}]}>Use Device TTS</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>Use the voice engine already installed on Android.</Text></View>{voiceMode==='device'?<Feather name='check-circle' size={18} color={colors.primary}/>:null}</Pressable>{voiceMode==='local'&&!selectedInstalled?<Text style={[styles.hint,{color:colors.mutedForeground}]}>Download the selected voice to use it. Device TTS is available without downloading.</Text>:null}</View>

  <View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[styles.section,{color:colors.foreground}]}>History</Text><Pressable accessibilityRole='switch' accessibilityState={{checked:historyEnabled}} onPress={()=>void toggleHistory()} style={[styles.deviceRow,{borderColor:colors.border,backgroundColor:colors.background}]}><Feather name={historyEnabled?'clock':'slash'} size={18} color={colors.primary}/><View style={styles.copy}><Text style={[styles.name,{color:colors.foreground}]}>Save chat history</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>When off, new Assistant chats are not saved.</Text></View><Text style={[styles.state,{color:colors.primary}]}>{historyEnabled?'On':'Off'}</Text></Pressable><Pressable accessibilityRole='button' onPress={()=>router.push('/my-history')} style={[styles.deviceRow,{borderColor:colors.border,backgroundColor:colors.background}]}><Feather name='clock' size={18} color={colors.primary}/><View style={styles.copy}><Text style={[styles.name,{color:colors.foreground}]}>My History</Text><Text style={[styles.body,{color:colors.mutedForeground}]}>View or delete saved conversations.</Text></View><Feather name='chevron-right' size={18} color={colors.mutedForeground}/></Pressable></View>
 </ScrollView>;
}

const styles=StyleSheet.create({root:{flex:1},header:{flexDirection:'row',alignItems:'center',marginBottom:14},back:{width:44,height:44,borderRadius:13,borderWidth:1,alignItems:'center',justifyContent:'center'},copy:{flex:1,marginLeft:12},title:{fontSize:24,fontFamily:'Inter_700Bold'},subtitle:{fontSize:10.5,lineHeight:16,marginTop:3},card:{borderWidth:1,borderRadius:18,padding:14,marginBottom:12},section:{fontSize:15,fontFamily:'Inter_700Bold',marginBottom:6},body:{fontSize:10.8,lineHeight:16},list:{gap:8,marginTop:10},item:{minHeight:68,borderWidth:1,borderRadius:14,padding:11,flexDirection:'row',alignItems:'center'},radio:{width:22,height:22,borderRadius:11,borderWidth:2,alignItems:'center',justifyContent:'center'},dot:{width:10,height:10,borderRadius:5},name:{fontSize:12.5,fontFamily:'Inter_700Bold'},voiceBlock:{borderWidth:1,borderRadius:14,padding:10},voiceRow:{minHeight:48,flexDirection:'row',alignItems:'center'},smallButton:{minHeight:42,borderWidth:1,borderRadius:12,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',marginTop:6},smallButtonText:{fontSize:11,fontFamily:'Inter_700Bold'},deviceRow:{minHeight:58,borderWidth:1,borderRadius:14,padding:11,flexDirection:'row',alignItems:'center',marginTop:8},hint:{fontSize:10.5,lineHeight:16,marginTop:10},state:{fontSize:11,fontFamily:'Inter_700Bold'}});
