import { LegalDocumentScreen } from '@/features/app-shell/LegalDocumentScreen';

const sections = [
  { title: '1. Overview', body: 'Last Updated: September 21, 2026\n\nNexus Plus is a multi-utility Android application developed by Nexus Wave Technologies. It includes productivity, document/PDF, media/audio, accessibility, security, finance-assistance, content-discovery, AI, file-transfer, remote-control,  television-control, camera/CCTV and other device-connected features. Each feature is intended to process only the information reasonably necessary for the operation you choose. This policy describes what information may be processed, why it is processed, where it may be stored, and the controls available to you.' },
  { title: '2. Account and Authentication Data', body: 'When you create or use a Nexus Plus account, the app may process your email address, display name, profile image, authentication identifiers, account status, provider information and session tokens. Email/password and Google sign-in are handled through the configured Supabase authentication flow. Session credentials are stored using protected device storage. We do not ask you to send passwords, recovery codes or authentication secrets to us by email.' },
  { title: '3. Privacy Policy and Terms Consent', body: 'Before the first authenticated use, Nexus Plus presents an in-app acceptance control for the Privacy Policy and Terms and Conditions. Some sensitive features may require an additional, feature-specific disclosure and affirmative consent immediately before the relevant Android permission or sensitive API is requested. Privacy Policy acceptance does not replace a required runtime permission or a separate sensitive-feature disclosure.' },
  { title: '4. Local Storage and Protected Data', body: 'Feature data can be stored locally on your Android device, including notes, documents, generated files, settings, reminders, app preferences, audio/video outputs, and other records you create. Security-sensitive information can use Android protected storage, Android Keystore-backed encryption, biometric/device authentication and encrypted local envelopes. Local storage and encryption reduce exposure but cannot guarantee security if the device, account or operating system is compromised.' },
  { title: '5. Password Manager and Secure Vault', body: 'The Password Manager/Secure Vault can store credentials, secure notes, identity information and other secrets you intentionally add. Vault data is encrypted before storage and protected by Android Keystore and authentication controls where supported. Password generation is performed locally using a cryptographically secure random source where available. When a sensitive field is revealed or copied, the app may require biometric/device re-authentication according to your Vault settings. Clipboard contents may be cleared after a security timeout where the feature supports automatic clearing. We do not intentionally transmit Vault plaintext to advertising networks or analytics providers.' },
  { title: '6. Google Drive Backup and Cloud Sync', body: 'When Google Drive capability is configured and you explicitly authorize it, Nexus Plus uses the Google Drive application-data area (appDataFolder) rather than browsing ordinary Drive folders. Cloud-sync payloads are encrypted by the app before upload. The intended cloud format is encrypted application data rather than readable note/password/document plaintext. Drive OAuth credentials are stored in protected device storage. If the required production Drive configuration is unavailable, the Drive feature remains disabled and the app continues with local storage instead. Cloud restoration may depend on the device/account encryption material available to the installed build.' },
  { title: '7. Geeta Nexus Integration', body: 'Geeta Nexus was previously developed as a standalone spiritual-reading experience and has now been integrated into Nexus Plus for unified accessibility, storage, account and feature management. The integrated experience currently provides Bhagavad Gita reading, chapter navigation, local reading-position history and offline content support where the verified content bundle is available. The Ramcharitmanas selector is reserved for a future verified content library and is not represented as available until such content is actually bundled or connected.' },
  { title: '8. Notes, Drawings, Photos, Audio and Attachments', body: 'Notepad can process text, categories, drawings, images, audio and mixed attachments that you intentionally create or select. The app may copy selected attachments into app-controlled storage so the note can be reopened later. Draft content remains local until you save it. Cloud sync, when enabled, uses the encrypted cloud mechanism described above.' },
  { title: '9. Documents, Document Studio and PDF Tools', body: 'Document Studio, document creator, importer, scanner, reader, summarizer, translator and PDF utilities can process documents and media you select or create. This can include text, page images, PDFs, metadata, scans, converted outputs, annotations and generated documents. Processing may occur locally or through a configured document/API service depending on the feature and build. External processing is limited to the information needed for the requested operation. You are responsible for ensuring you have permission to process the content.' },
  { title: '11. Remote Control and TV Control', body: 'Remote Control features can discover, pair with and control supported computers, TVs and other authorized devices. Depending on the transport, the app may process device name, network address, pairing information, protocol data, commands and connection state. IR, network or vendor-specific control may depend on device hardware and protocol support. Use these features only with devices you own or are expressly authorized to control.' },
  { title: '12. Nearby File Transfer', body: 'Send File can exchange files between compatible devices using supported local-network, wireless or nearby-device transports. The app may process transfer metadata, device identity information, connection state and the files you choose to send or receive. You are responsible for verifying the recipient and destination before confirming a transfer.' },
  { title: '13. Camera, CCTV and Connected-Device Features', body: 'CCTV tools can process camera/recorder configuration, discovery information, network addresses, authentication credentials, session data, live-view data, recordings, playback metadata and control commands for devices you are authorized to use. Security-sensitive camera credentials are intended to remain in protected local storage and on the authorized device/network path required for operation. Discovery results are treated as untrusted until the app completes applicable authorization and compatibility checks. Nexus Plus does not grant permission to access third-party cameras.' },
  { title: '14. Accessibility and Access Focus', body: 'Some Nexus Plus accessibility-related functions can use Android accessibility capabilities to help users with supported device-navigation, access, focus, interaction or assistive workflows. If a feature uses AccessibilityService or another sensitive accessibility API, the app must provide the applicable in-app disclosure, request affirmative user consent where required, and then send the user to Android settings to grant the service. Accessibility data is used only for the disclosed feature purpose and is not intended for unrelated advertising or profiling. Nexus Plus must not use accessibility APIs to bypass Android security controls, prevent users from disabling services, or perform undisclosed autonomous actions.' },
  { title: '15. Microphone, Camera, Photos and Media Permissions', body: 'Microphone access is requested for supported recording, voice, audio-editing, karaoke, voice-over, speech and related features. Camera access is requested for supported camera, QR scanning and document-scanning features. Photo/media access is requested when you intentionally select or save supported media. These permissions should be requested at the relevant feature boundary and can be revoked through Android settings, subject to feature availability.' },
  { title: '16. Audio Editor, Voice Studio, Voice Changer and Text-to-Speech', body: 'Audio features can record, trim, mix, compress, convert, remove silence, apply effects, change speed/pitch, render audio/video, generate speech, use device voices and use supported local voice models. Voice-clone/ONNX functionality, where available in a build, processes the model and source audio needed for the requested operation. You are responsible for having rights and authorization to use source recordings, voice models and generated voice identities.' },
  { title: '17. Discover, RSS, Web Content and External Links', body: 'Nexus Discover may retrieve RSS feeds, article metadata, summaries, thumbnails and links from third-party publishers. Opening external content may connect to the publisher website or other provider and can be governed by that provider’s privacy policy. Nexus Plus does not control third-party content accuracy, retention, tracking or availability.' },
  { title: '18. Nexus Assistant, AI, Vision and Automated Processing', body: 'AI-assisted features may process text, files, documents, images, audio, video, user commands and contextual information required for the requested task. Some operations can use local models or configured backend/provider services. Provider API keys are not intended to be exposed in the mobile UI. Automated results can be incomplete or incorrect and should be independently verified for important decisions.' },
  { title: '  { title: '18A. Live Video Description and On-Device Media Analysis', body: 'When you enable Live Video Description in Media Player, the selected video remains on your Android device and is processed locally by the installed Nexus Plus playback/vision components. The video file, extracted frames and generated visual description text are not uploaded to a Nexus Plus server for this feature. Downloaded local AI/runtime models, when required, are stored in app-controlled device storage and reused after installation. Network access may be used only when a required model or runtime is being downloaded for the first time, and the application uses direct device-to-provider HTTPS downloads rather than routing model files through a Nexus Plus media relay. Once the required local runtime/model is available, video description can operate without an internet connection. TTS output is generated through the selected local Piper voice or Android device speech engine. As with any local software, device compromise or malicious third-party applications could still expose information on the device.' },
  { title: '18B. Media Player URL Playback', body: 'Media Player can accept user-entered trusted direct media URLs for audio or video playback. The app does not intentionally bypass DRM, authentication, paywalls, access controls or copyright protections. Supported YouTube playback uses the applicable official YouTube/YouTube Music handoff or supported provider flow rather than extracting protected streams. URL playback can connect directly to the service named by the user, so the external provider may receive network information such as the device IP address according to that provider’s policies.' },
19. Expense Tracker and Payment Announcer', body: 'Expense Tracker and Payment Announcer can process expense entries, categories, transaction-related text and notifications/messages that you intentionally enable for the feature. Automated detection and classification may be performed locally or through configured services. These are organization/convenience tools and are not banking systems or proof of a completed payment. Financial information should be independently verified with your bank or payment provider.' },
  { title: '20. QR, Calculator, Time, Reminder and Utility Features', body: 'QR tools may process URLs, text, contact information, Wi-Fi configuration or UPI identifiers that you choose to scan or generate. Calculator features process values entered for calculations. Time-announcer, alarms, stopwatch, world clock, reminders and related tools process schedules and preferences needed to provide notifications and announcements. Utility outputs should be reviewed before relying on them for sensitive transactions or deadlines.' },
  { title: '21. Notifications, Firebase and Service Diagnostics', body: 'When configured, Firebase Cloud Messaging can process a push token, platform information, app version and notification delivery information. Analytics or measurement must be enabled only where the installed build and disclosed service configuration support it; the app does not intentionally send Secure Vault plaintext or passwords to analytics.' },
  { title: '22. Network, Device and Security Information', body: 'Depending on the feature, Nexus Plus may process IP/network information, device model, Android version, app/build version, local-network addresses, protocol state, security verification state, crash or diagnostic information and device capability information. This information is used for connectivity, compatibility, security, abuse prevention and feature operation.' },
  { title: '23. App Integrity and Tamper Protection', body: 'Production builds may use release signing, Play Integrity and backend authorization for protected API access. If an integrity capability is not configured, features that depend on it must fall back to their permitted local or limited mode rather than silently bypassing security. Integrity checks must not intentionally corrupt, delete or encrypt user data as a punitive measure. The purpose is access control and service protection.' },
  { title: '24. Data Sharing and Third Parties', body: 'We do not sell personal information or share it with data brokers for targeted advertising. Information can be processed by service providers required for features you use, including Supabase authentication/backend services, Google services, Firebase services, document/media/AI APIs, RSS publishers, connected-device protocols and other integrations selected or configured by the user. Each provider may have its own terms, retention and privacy practices. We disclose relevant categories here and in Play Console Data safety declarations.' },
  { title: '25. Data Retention and Deletion', body: 'Local data can generally be removed through the applicable feature, Android storage controls or app uninstall where appropriate. Account/backend data is retained as reasonably necessary for service operation, security, legal compliance and legitimate operational needs. Account deletion removes the Nexus Plus account and supported backend records as described by the service. Third-party providers may retain data under their own policies and may require separate deletion requests.' },
  { title: '26. Children and Age-Related Use', body: 'Nexus Plus is not designed to target children as its primary audience. We do not knowingly use sensitive data from children for advertising or profiling. Where a build is offered to an audience that includes children, the Play Console Target Audience, Families, Data safety and applicable consent requirements must be completed accurately and the app must comply with the current Google Play Families Policy.' },
  { title: '27. Your Controls and Choices', body: 'You control whether to use optional features, grant Android permissions, connect Google Drive, add passwords/notes, configure remote devices, enable accessibility-related tools, send files, or enable other integrations. You can revoke permissions through Android settings and can stop using optional services. Some features will not function after a required permission or service is revoked.' },
  { title: '28. Security Limitations', body: 'We use reasonable safeguards appropriate to the feature, including encrypted transport where supported, protected device storage, Android Keystore-backed keys, authentication gates, encrypted cloud envelopes and authorization checks. No software, device, network, API, cloud service or authentication system is completely secure. Users should keep Android and Nexus Plus updated and protect device/account credentials.' },
  { title: '29. Changes to this Privacy Policy', body: 'We may update this policy when features, providers, permissions, security practices or legal requirements change. The Last Updated date identifies the version shown in the app. Material changes may also be communicated through the app or official website when appropriate.' },
  { title: '30. Contact', body: 'Nexus Wave Technologies\nFounder: Kuldeep\nWebsite: nexusweb.co.in\nEmail: info@nexusweb.co.in\n\nFor privacy requests, identify the account or feature involved. Never send passwords, recovery codes, API keys, payment credentials or private camera passwords by email.' },
];

export default function PrivacyPolicyScreen() {
  return <LegalDocumentScreen title="Privacy Policy" subtitle="Clear, feature-specific information about data access, permissions, storage, cloud sync, accessibility, connected devices, security and your choices." sections={sections} />;
}
