import { LegalDocumentScreen } from '@/features/app-shell/LegalDocumentScreen';

const sections = [
  { title: '1. Overview', body: 'Last Updated: September 21, 2026\n\nNexus Plus is a multi-utility application developed by Nexus Wave Technologies. Depending on the features you choose, it can provide productivity tools, alarms and reminders, document and media utilities, accessibility features, security tools, financial-assistance tools, camera/CCTV and connected-device features, screen mirroring, remote control, nearby file transfer, AI-assisted workflows, content aggregation and related digital services. We follow data minimization and process information only as reasonably necessary to provide, secure, troubleshoot, and improve the app.' },
  { title: '2. Information we collect or process', body: 'Depending on the features you use, information may include account information such as email address, display name, profile image, authentication identifiers and account status; app preferences and settings; device and app information needed for security, notifications, troubleshooting and compatibility; reminders and records you create; files, photos, audio, video or documents you intentionally select or capture; information needed to configure connected devices or services; and feature-specific content you voluntarily submit. We do not sell personal information or use it for third-party advertising.' },
  { title: '3. Device and connection data', body: 'Supported connected-device features may use local device and connection information needed to discover, pair with, or communicate with devices you are authorized to use. Remote control, screen mirroring, casting, nearby file transfer and CCTV features may require local-network, Bluetooth, Wi-Fi, device-identity or connection information. Network security also depends on your router, operating system and connected devices.' },
  { title: '4. Permissions and their purposes', body: 'Camera: capture photos in supported camera/selfie features and scan QR codes or documents when you explicitly start those workflows. Photos and media: access or save media when you intentionally use a supported feature. Microphone/audio: record or process audio when you explicitly start supported recording or audio features. Notifications: reminders, alarms and push notifications when enabled. Vibration: haptic and notification feedback. Exact alarm/full-screen notification capabilities: supported time-assistance and alarm features, subject to Android rules and your settings. Foreground media playback: continue supported audio/media playback while the app is not in the foreground. Files/documents: access files through the Android system picker when you select them. Biometric/device authentication: protect supported security-sensitive features. Android/Expo may declare technical permissions required by the installed feature set; permissions are not used as authorization to collect unrelated data.' },
  { title: '5. Local storage and protected information', body: 'Some preferences and feature data are stored locally on your device. Security-sensitive values, including selected connected-camera credentials, session information and security metadata, may use device-protected Android secure storage. Audio, document, PDF and generated-output files may be stored in app-controlled storage or locations selected by you. Local storage is not an absolute security guarantee. Protect your device with a strong screen lock, keep Android updated, and do not share sensitive credentials.' },
  { title: '6. Accounts, authentication and cloud services', body: 'Nexus Plus uses authentication and selected cloud backend services for account access and features requiring synchronized data. Backend records may include account identifiers, profile information, device-security information, app settings and feature-specific records. Protected data is designed to require authenticated authorization and applicable backend access controls. Cloud infrastructure is operated by service providers and is therefore also subject to their security and service policies.' },
  { title: '7. Firebase, notifications and analytics', body: 'When notifications are enabled and the relevant Firebase configuration is active, Nexus Plus can use Firebase Cloud Messaging for device push tokens and notification delivery. The app may send a token, platform, app version and update information to its backend for notification management. The app configuration also supports Google Analytics for Firebase measurement. Where analytics is active in a particular build, Google may process measurement information under Google’s applicable policies. Nexus Wave Technologies does not control Google’s independent infrastructure, retention practices or security guarantees.' },
  { title: '8. APIs, AI and third-party providers', body: 'Some features communicate with external APIs and providers. Nexus Plus may act as an interface or aggregation layer between you and those providers. Supported AI functionality can communicate through Nexus Plus backend gateways or other configured providers rather than exposing provider API keys inside the mobile app. Information necessary to fulfil a request may be transmitted to the relevant provider. Each provider controls its own infrastructure, security, processing, retention, availability and terms. We cannot guarantee the security or availability of an independent API provider.' },
  { title: '9. Camera, CCTV and connected-device use', body: 'Nexus Plus provides camera/CCTV tools only for cameras, recorders and connected devices that you own or are expressly authorized to operate. You must not use Nexus Plus to monitor, record, control or access a third party’s camera or connected device without lawful authorization. Users are responsible for complying with applicable privacy, consent, surveillance, recording, property, telecommunications and data-protection laws. The app does not grant surveillance rights. For supported CCTV integrations, the app uses an authorization-first design: camera identity, secure transport and authenticated device communication must be validated before privileged controls are enabled. Network discovery results are treated as untrusted candidate data until authenticated verification succeeds. Unsupported or unverified controls remain disabled rather than being presented as available.' },
  { title: '10. Unauthorized camera use and abuse response', body: 'Unauthorized access or control of cameras, recorders or connected devices is prohibited. We may suspend or restrict access to Nexus Plus services where reasonably necessary to prevent abuse, protect users, investigate security incidents, comply with law, or preserve service integrity. Where we have reliable evidence of misuse through our services, we may begin review and appropriate enforcement as soon as reasonably practicable. Enforcement does not replace law-enforcement or other legal processes.' },
  { title: '11. Remote Control and Screen Mirroring', body: 'Remote Control and Screen Mirroring are intended for authorized TVs, computers, phones, networks and other supported devices. Screen projection uses Android’s screen-capture and media-projection permissions and does not bypass the operating system’s consent controls. Browser-based computer receiving may use a temporary local receiver address on the same network. Control and casting capabilities may depend on device support, pairing, network configuration and available transports such as Wi-Fi, Bluetooth or IR.' },
  { title: '12. Nearby File Transfer', body: 'The Send File feature can use nearby-device permissions and local network or wireless transports to send or receive files between supported devices. File contents are processed only as needed for the transfer you initiate. You are responsible for sending files only to recipients and devices you are authorized to use, and for reviewing the recipient before confirming a transfer.' },
  { title: '13. Expense Tracker and Payment Announcer', body: 'These are convenience and organization tools, not banking or payment systems. Where supported Android permissions or integrations make notification/message content available, transaction-related text may be processed to help identify or announce payment information. Automated classifications can be wrong. Verify important transactions with your bank or payment provider; an app announcement is not proof of successful payment.' },
  { title: '14. Documents, PDF, E-Paper and file processing', body: 'You may select documents, PDFs, images, audio or video for supported utilities including document reading, PDF conversion and page operations, Word-to-PDF conversion through the configured document service, e-paper generation, file organization and protected file handling. If processing is local, content can remain on the device. If a feature requires an external document or AI service, relevant content may be transmitted to complete the request. Do not submit confidential or highly sensitive material to a third-party provider unless you accept that provider’s applicable terms and privacy practices.' },
  { title: '15. Audio Editor, Voice and Text-to-Speech', body: 'Audio features may record, edit, trim, mix, convert, compress, add effects, remove silence, change speed or pitch, and generate speech. Voice generation may use system voices, downloaded local voice models, Piper-based engines or an installed voice-clone/ONNX engine where supported. Generated audio is saved only as needed for the operation and user-requested output. If a voice model, native engine or device capability is unavailable, the relevant feature should report that limitation rather than silently fabricating an output.' },
  { title: '16. Discover and publisher content', body: 'Nexus Discover can retrieve live RSS headlines, summaries and links from publishers. Feed data can contain third-party content and is refreshed from the source when you open or refresh the feature. Nexus Plus does not control publisher content, availability, accuracy, copyright or privacy practices. Opening a full article may take place on the publisher’s website or an embedded browser surface and may be subject to the publisher’s own policies.' },
  { title: '17. QR, Calculator, Time, Reminder and Utility Tools', body: 'QR tools may process text, URLs, WhatsApp data, Wi-Fi information or UPI identifiers that you choose to encode or scan. Calculator and finance utilities may process values you enter for calculations and analysis. Time announcers, clocks and reminders may store schedules and preferences locally or use notification services when enabled. These tools are convenience features and do not replace independent verification of financial, transactional or time-sensitive information.' },
  { title: '18. Security measures', body: 'We use reasonable safeguards appropriate to each feature, including encrypted network transport where supported, Android cleartext-traffic restrictions, authenticated backend access, backend access controls, device-protected storage for selected secrets, authenticated CCTV device sessions, runtime capability verification, short-lived session controls, and device/biometric authentication for supported protected features. We do not rely on a hidden surveillance or “spy” mechanism. No software, device, network, API, cloud service or authentication mechanism can be guaranteed completely secure.' },
  { title: '19. Data sharing', body: 'We do not sell personal information or share it with data brokers for advertising. Information may be processed by providers needed for features you use, including authentication/backend infrastructure, push-notification infrastructure, analytics/measurement where active, AI/document/media/API providers, and other integrations you choose. CCTV connection credentials and camera-control data are intended to remain on the authorized device/network path needed for the feature unless a separately disclosed service requires transmission. Providers operate under their own policies and security practices. Information may also be disclosed when required by applicable law, legal process, fraud prevention, security, or protection of users and services.' },
  { title: '20. Children’s privacy', body: 'Nexus Plus is not designed to solicit personal information from children for profiling or advertising. If you believe a child has provided personal information without appropriate authorization, contact us so we can review the request and take appropriate action.' },
  { title: '21. Account and data deletion', body: 'Nexus Plus provides an in-app “Delete account permanently” control in the Profile screen. After authentication, the deletion request permanently deletes the authenticated Nexus Plus account and its profile record from our backend. The app clears the local authenticated session after successful deletion. Some information may be retained where required by law or reasonably necessary for security, fraud prevention, dispute resolution, or legal compliance. Data held independently by third-party providers is governed by their policies and is not automatically deleted by this app action.' },
  { title: '22. Data retention', body: 'Retention varies by data type and feature. Local data can generally be removed through the relevant feature, Android app-data controls, or uninstalling the application where applicable. Account/backend data is retained only as reasonably necessary for the service, security, legal compliance and legitimate operational purposes, subject to applicable law and provider policies.' },
  { title: '23. Feature availability and deferred capabilities', body: 'Not every feature is available on every device, Android version, build variant, account or network. Some features require an installed native engine, a supported protocol, an external service, or user-granted permissions. Nexus Plus should present unavailable or unverified capabilities as unavailable rather than implying that a restricted capability is operational. Features that are under development or not included in the installed build are not treated as active services for that build.' },
  { title: '24. Your choices and safety guidance', body: 'You can choose whether to grant optional permissions when Android provides that choice and can disable notifications or revoke permissions through Android settings. Review permissions periodically, keep Android and Nexus Plus updated, use a secure device lock, and never share passwords, recovery codes, API keys, payment credentials, or private camera credentials unnecessarily. For connected devices, use strong unique credentials and secure your local network.' },
  { title: '25. Changes to this Privacy Policy', body: 'We may update this policy when features, providers, security practices or applicable legal requirements change. The Last Updated date identifies the current version. Material changes may also be communicated through the app or official website where appropriate.' },
  { title: '26. Contact Us', body: 'Nexus Wave Technologies\nFounder: Kuldeep\nWebsite: nexusweb.co.in\nEmail: info@nexusweb.co.in\n\nFor privacy requests, please describe the account or feature involved. Never send passwords, API keys, payment credentials or other secrets by email.' },
];

export default function PrivacyPolicyScreen() {
  return <LegalDocumentScreen title="Privacy Policy" subtitle="Clear information about Nexus Plus data handling, permissions, security, connected devices, media, documents, third-party services, retention and deletion." sections={sections} />;
}
