import { LegalDocumentScreen } from '@/features/app-shell/LegalDocumentScreen';

const en = [
  { title: '1. Welcome to Nexus Plus', body: 'Last updated: 2 October 2026. This Privacy Policy explains in plain language what information Nexus Plus may process, why it may be used, where it may be stored, how long it may be kept, and what choices and rights you may have.' },
  { title: '2. Information we may process', body: 'Depending on the features you use, Nexus Plus may process account information such as your name, email address, verified contact information and account identifiers; content you create or select such as notes, documents, photos, audio and video; support requests; transaction information needed to verify purchases; device, app, network and security information; notification tokens; preferences; and information required for connected features.' },
  { title: '3. Why we use information', body: 'We use information to provide requested features, authenticate and protect accounts, save settings and content, complete transactions, provide support, prevent abuse and fraud, improve reliability and compatibility, send enabled notifications, meet legal obligations, and operate third-party services that you choose to use.' },
  { title: '4. Sensitive permissions', body: 'Some features may request microphone, camera, media, nearby-device or network access, notifications, contacts, phone or SMS permissions where required for that feature. We aim to request access only when needed. Where platform rules require prominent disclosure and consent, the app should explain what is accessed, why it is needed, and how it is used before access begins.' },
  { title: '5. Files and personal content', body: 'Nexus Plus processes files and content when you ask a feature to open, create, edit, convert, analyze, record, play, share or save them. Some features can process content on the device. Others may use a configured external service when you choose a feature that requires it.' },
  { title: '6. Secure Vault and passwords', body: 'Notes, secure notes, passwords and other secrets you intentionally save may be stored using platform security features. We do not intentionally send Secure Vault plaintext to advertising networks or data brokers.' },
  { title: '7. Google Drive', body: 'Google Drive backup is optional. When enabled, supported backup data may be stored in app-specific Drive storage. Data may be encrypted by the app before upload. Google processes Google Drive data under its own terms and privacy documentation.' },
  { title: '8. Payments and subscriptions', body: 'Paid services may involve subscriptions or usage-based purchases. Payment and transaction information may be processed by the relevant app store, payment provider and systems needed for verification, refunds, entitlement management and fraud prevention. Nexus Plus does not ask you to share your UPI PIN, bank password, OTP or recovery codes with us.' },
  { title: '9. AI, audio, voice and media processing', body: 'Audio, voice, video, image, document and AI-assisted features may process the content you select for the task. Processing may happen on the device or through a configured external provider. Automated results may be incomplete or inaccurate, so important output should be independently checked.' },
  { title: '10. Device connection and file transfer', body: 'Remote control, TV control, CCTV tools and Send File may process device names, connection details, pairing data, commands and files you choose to transfer. Use these features only with devices and accounts you are authorized to access.' },
  { title: '11. Notifications, diagnostics and security', body: 'The app may process push-notification tokens, app version, device information, network information and limited diagnostic data when needed for notifications, compatibility, security, abuse prevention or troubleshooting.' },
  { title: '12. Who may receive information?', body: 'We do not sell personal information to data brokers. Information may be processed by service providers necessary for authentication, hosting and databases, cloud storage, notifications, AI or document processing, payments and connected-device functionality. Providers may have their own privacy policies and retention rules.' },
  { title: '13. International processing', body: 'Some service providers may process information outside your country. Where applicable law requires transfer safeguards, we aim to use appropriate contractual, organizational or other lawful measures.' },
  { title: '14. Retention', body: 'Information is kept only as long as reasonably needed for the relevant purpose, to provide and secure the service, to meet legal, accounting or transaction requirements, or to handle disputes and abuse. Temporary operational data should be removed when it is no longer needed. Some records may legally need to be retained longer.' },
  { title: '15. Your privacy rights and choices', body: 'Depending on your location and applicable law, you may have rights to be informed, access your information, correct it, request deletion, restrict processing, receive a portable copy, object to certain processing, withdraw consent where consent is the legal basis, and complain to a supervisory authority. You can start a request through the account controls or by contacting Nexus Wave Technologies.' },
  { title: '16. Account deletion', body: 'If you create an account, Nexus Plus provides an in-app account deletion option. Deleting the account is intended to remove the account and associated data that we are not legally required to retain. Data held independently by third-party providers is governed by their policies, and legally required records may remain for the required period.' },
  { title: '17. Children', body: 'The service is not intentionally designed to collect personal information from children in violation of applicable law. Where a platform or feature has age requirements, those requirements apply.' },
  { title: '18. Security', body: 'We use reasonable safeguards such as encrypted connections, access controls, protected credentials, secure device storage where supported and authorization checks. No device, app, network or cloud service can guarantee absolute security.' },
  { title: '19. Changes to this policy', body: 'We may update this Privacy Policy when the app, services, data practices, providers, security measures or legal requirements change. The updated date shown in the app identifies the current version.' },
  { title: '20. Contact', body: 'Nexus Wave Technologies\nFounder: Kuldeep\nWebsite: nexusweb.co.in\nEmail: info@nexusweb.co.in' },
];

const hi = [
  { title: '1. Nexus Plus में आपका स्वागत है', body: 'अंतिम अपडेट: 25 सितंबर 2026। Nexus Plus को उपयोगी, सुलभ और समझने में आसान रखने के लिए यह Privacy Policy सरल भाषा में बताती है कि ऐप कौन-सी जानकारी इस्तेमाल कर सकता है, क्यों कर सकता है, कहाँ रखी जा सकती है और आपके पास कौन-से विकल्प हैं।' },
  { title: '2. कौन-सी जानकारी इस्तेमाल हो सकती है?', body: 'आप जिन सुविधाओं का उपयोग करते हैं, उनके अनुसार Nexus Plus आपके खाते की जानकारी जैसे ईमेल और प्रोफ़ाइल जानकारी; आपके द्वारा बनाई या चुनी गई नोट्स, दस्तावेज़, फोटो, ऑडियो और वीडियो; ऐप की सेटिंग और पसंद; सुरक्षा और संगतता के लिए जरूरी डिवाइस जानकारी; और कनेक्टेड सुविधाओं के लिए आपके द्वारा दी गई जानकारी को प्रोसेस कर सकता है।' },
  { title: '3. आपकी फाइलें और निजी सामग्री', body: 'जब आप किसी सुविधा से कोई फाइल खोलते, बनाते, एडिट करते, कन्वर्ट करते, रिकॉर्ड करते, चलाते या सेव करते हैं, तभी Nexus Plus उस सामग्री को प्रोसेस करता है। जो सामग्री आपके डिवाइस पर रहती है, उस पर आपका नियंत्रण रहता है। कुछ सुविधाओं के लिए जरूरी होने पर कॉन्फ़िगर किए गए बाहरी सेवा प्रदाता का उपयोग हो सकता है।' },
  { title: '4. नोट्स, Secure Vault और Password Manager', body: 'आप जिन नोट्स, सुरक्षित नोट्स, पासवर्ड या अन्य रहस्यों को सेव करते हैं, वे उपलब्ध Android सुरक्षा सुविधाओं का उपयोग करके डिवाइस पर रखे जा सकते हैं। संवेदनशील जानकारी के लिए जहाँ समर्थित हो, encryption और Android security mechanisms का उपयोग किया जाता है। हम Secure Vault का plaintext जानबूझकर advertising networks को नहीं भेजते।' },
  { title: '5. Google Drive बैकअप और सिंक', body: 'Google Drive बैकअप वैकल्पिक है। इसे चालू करने पर Nexus Plus समर्थित बैकअप के लिए app-specific Drive storage का उपयोग कर सकता है। Cloud में भेजने से पहले ऐप डेटा को encrypt करता है। Google की अपनी privacy policy और terms लागू होती हैं।' },
  { title: '6. भुगतान, Premium और UPI', body: 'Nexus Plus में Premium membership या अन्य paid digital features उपलब्ध हो सकते हैं। उपलब्ध payment options ऐप में दिखाए जाते हैं। मौजूदा payment flow में UPI के जरिए payment request बनाई जा सकती है। Transaction बनाने और verify करने के लिए जरूरी payment information को Nexus Plus और transaction के लिए उपयोग किए गए payment-related service providers प्रोसेस कर सकते हैं। Nexus Plus आपसे UPI PIN, bank password या OTP शेयर करने के लिए नहीं कहता। Premium access या अन्य entitlement payment की verification के बाद ही activate किया जाता है।' },
  { title: '7. Refund और non-refundable fees', body: 'जहाँ लागू कानून किसी अलग refund right की मांग नहीं करता, वहाँ Nexus Plus Premium, digital credits या अन्य paid digital services के लिए भुगतान की गई fee purchase के बाद non-refundable है। भुगतान पूरा करने से पहले plan, price और included benefits ध्यान से देखें। Failed, duplicate या गलत तरीके से processed payment की उचित स्थिति में समीक्षा और correction की जा सकती है। जहाँ कानूनन refund लागू हो, उसे संबंधित payment provider और लागू कानून के अनुसार handle किया जाएगा।' },
  { title: '8. Geeta Nexus', body: 'Geeta Nexus अब Nexus Plus में integrated है। इसमें Bhagavad Gita सहित उपलब्ध आध्यात्मिक सामग्री और संबंधित सुविधाएँ दी जाती हैं। Reading progress और कुछ preferences डिवाइस पर सेव हो सकती हैं, ताकि आप वहीं से आगे पढ़ सकें।' },
  { title: '9. Accessibility सुविधाएँ', body: 'कुछ सुविधाएँ navigation और assistive functionality देने के लिए Android accessibility service का उपयोग कर सकती हैं। Accessibility data का उपयोग केवल ऐप में बताए गए उद्देश्य के लिए किया जाता है। Nexus Plus Android security controls को bypass करने या service को आपके द्वारा बंद किए जाने से रोकने के लिए accessibility tools का उपयोग नहीं करता।' },
  { title: '10. Microphone, camera और media permissions', body: 'Recording, scanning, voice features, audio editing या media selection जैसी सुविधा की जरूरत होने पर ही microphone, camera या media permission मांगी जाती है। आप इन्हें Android settings में नियंत्रित कर सकते हैं। जरूरी permission न देने पर कुछ सुविधाएँ उपलब्ध नहीं होंगी।' },
  { title: '11. Audio, voice और AI सुविधाएँ', body: 'Audio Editor, voice tools, text-to-speech और AI-assisted features आपके द्वारा चुने गए text, audio, video, image या file को प्रोसेस कर सकते हैं। कुछ processing डिवाइस पर हो सकती है और कुछ configured external services पर निर्भर कर सकती है। Automated results हमेशा पूरी तरह सही हों, यह जरूरी नहीं है, इसलिए महत्वपूर्ण जानकारी को स्वतंत्र रूप से जांचें।' },
  { title: '12. Device connection और file transfer', body: 'Remote control, TV control, CCTV और Send File जैसी सुविधाएँ device name, connection details, pairing data, commands और आपके द्वारा चुनी गई files को प्रोसेस कर सकती हैं। इन सुविधाओं का उपयोग केवल उन्हीं devices और accounts के साथ करें जिनका उपयोग करने का अधिकार आपको है।' },
  { title: '13. Payment announcements और transaction information', body: 'Expense Tracker और Payment Announcer उन transaction-related texts, notifications या messages को प्रोसेस कर सकते हैं जिन्हें आप इस सुविधा के लिए अनुमति देते हैं। ये सुविधाएँ convenience और organization के लिए हैं। कोई announcement अपने आप में यह प्रमाण नहीं है कि bank या payment provider ने transaction पूरा कर दिया है।' },
  { title: '14. Notifications, diagnostics और security', body: 'Notifications, compatibility, security, abuse prevention या troubleshooting के लिए app push-token, app version, device/network information और सीमित diagnostic information प्रोसेस कर सकता है। हम passwords या Secure Vault plaintext को analytics services को जानबूझकर नहीं भेजते।' },
  { title: '15. जानकारी किन्हें मिल सकती है?', body: 'हम आपकी personal information को data brokers को बेचते नहीं हैं और targeted advertising के लिए उपयोग नहीं करते। जिन सुविधाओं का आप उपयोग करते हैं, उनके लिए जरूरी service providers—जैसे authentication, cloud storage, AI/document processing, notifications और connected-device services—जानकारी प्रोसेस कर सकते हैं। उनकी अपनी privacy practices लागू होती हैं।' },
  { title: '16. जानकारी कितने समय तक रखी जाती है?', body: 'Local information को आम तौर पर संबंधित feature, Android storage controls या app uninstall के माध्यम से हटाया जा सकता है। Account और service information को service देने, account security, कानूनी आवश्यकताओं और disputes को handle करने के लिए आवश्यक अवधि तक रखा जा सकता है। Third-party providers अपनी policies के अनुसार जानकारी रख सकते हैं।' },
  { title: '17. आपके विकल्प', body: 'आप तय करते हैं कि कौन-सी optional features इस्तेमाल करनी हैं, कौन-सी permissions देनी हैं, Google Drive connect करना है या नहीं, paid services इस्तेमाल करनी हैं या नहीं, और किन files या devices को connect करना है। Android settings से permissions revoke की जा सकती हैं और optional services का उपयोग कभी भी रोका जा सकता है।' },
  { title: '18. Account deletion और privacy requests', body: 'आप उपलब्ध account controls के माध्यम से supported account deletion या privacy assistance का अनुरोध कर सकते हैं या Nexus Wave Technologies से संपर्क कर सकते हैं। Support request में password, OTP, UPI PIN, recovery code, private camera password या कोई अन्य sensitive secret कभी न भेजें।' },
  { title: '19. Security', body: 'हम जहाँ समर्थित हो वहाँ encrypted connections, protected device storage, Android security features, authentication controls और authorization checks जैसी उचित सुरक्षा उपायों का उपयोग करते हैं। किसी भी device, app, network या cloud service की पूर्ण security की गारंटी नहीं दी जा सकती।' },
  { title: '20. इस policy में बदलाव', body: 'जब app, payment options, providers, security practices या कानूनी आवश्यकताओं में बदलाव होता है, तो हम इस Privacy Policy को अपडेट कर सकते हैं। ऐप में दिखाई गई नई version और उसका updated date वर्तमान policy को दर्शाते हैं।' },
  { title: '21. संपर्क', body: 'Nexus Wave Technologies\nसंस्थापक: Kuldeep\nWebsite: nexusweb.co.in\nEmail: info@nexusweb.co.in' },
];

export default function PrivacyPolicyScreen() {
  return (
    <LegalDocumentScreen
      title="Privacy Policy"
      subtitle="How Nexus Plus handles your information, payments, permissions and privacy choices."
      sections={{ en, hi }}
    />
  );
}
