import { Feather } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { buildProductivityWorkflow, renderEmailDraft } from '@/features/productivity-ai/workflowEngine';

export default function ProductivityAiScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets();
  const [request, setRequest] = useState(''); const [preview, setPreview] = useState<{ subject: string; body: string } | null>(null);
  const generate = () => { const text = request.trim(); if (!text) return; const draft = renderEmailDraft({ purpose: 'email', subject: 'Quick update', keyPoints: [text], language: 'hinglish', tone: 'professional' }); setPreview(draft); buildProductivityWorkflow({ email: { to: '', context: { purpose: 'email', subject: draft.subject, keyPoints: [text], language: 'hinglish' } } }); };
  return <ScrollView style={[styles.root, { backgroundColor: colors.background }]} contentContainerStyle={{ padding: 18, paddingTop: insets.top + 12, paddingBottom: insets.bottom + 28 }}>
    <View style={styles.header}><View style={[styles.icon, { backgroundColor: colors.secondary }]}><Feather name="zap" size={22} color={colors.primary} /></View><View style={styles.copy}><Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>AI Workflow</Text><Text style={[styles.body, { color: colors.mutedForeground }]}>Email, meetings and calendar workflows with a lightweight local composer.</Text></View></View>
    <Text style={[styles.label, { color: colors.foreground }]}>What should Nexus Plus do?</Text>
    <TextInput accessibilityLabel="Describe your productivity task" multiline value={request} onChangeText={setRequest} placeholder="Example: Send Rahul a meeting update for tomorrow at 11 AM" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.card }]} />
    <Pressable accessibilityRole="button" accessibilityLabel="Create message preview" onPress={generate} style={[styles.button, { backgroundColor: colors.primary }]}><Feather name="edit-3" size={18} color={colors.primaryForeground} /><Text style={[styles.buttonText, { color: colors.primaryForeground }]}>Create Message</Text></Pressable>
    {preview ? <View accessibilityLiveRegion="polite" style={[styles.preview, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.previewTitle, { color: colors.foreground }]}>{preview.subject}</Text><Text selectable style={[styles.body, { color: colors.foreground }]}>{preview.body}</Text><Text style={[styles.note, { color: colors.mutedForeground }]}>Sending and calendar changes require an authenticated provider and confirmation according to workflow policy.</Text></View> : null}
    <View style={styles.features}><Feature title="Email Assistant" text="Draft bilingual messages from only the key points you provide." colors={colors} /><Feature title="Meeting Scheduler" text="Build typed meeting actions with attendees, time and agenda." colors={colors} /><Feature title="Calendar Manager" text="List or cancel events through an authenticated calendar provider." colors={colors} /><Feature title="Voice-first" text="Use the device's installed Hindi/English speech recognition and TTS without bundling voice models." colors={colors} /></View>
  </ScrollView>;
}
function Feature({ title, text, colors }: { title: string; text: string; colors: ReturnType<typeof useColors> }) { return <View style={[styles.feature, { borderColor: colors.border }]}><Text style={[styles.featureTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.body, { color: colors.mutedForeground }]}>{text}</Text></View>; }
const styles = StyleSheet.create({ root: { flex: 1 }, header: { flexDirection: 'row', alignItems: 'center', marginBottom: 24 }, icon: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, marginLeft: 12 }, title: { fontSize: 26, fontFamily: 'Inter_700Bold' }, body: { fontSize: 12, lineHeight: 18 }, label: { fontSize: 14, fontFamily: 'Inter_700Bold', marginBottom: 8 }, input: { minHeight: 120, borderWidth: 1, borderRadius: 16, padding: 14, textAlignVertical: 'top', fontSize: 14 }, button: { minHeight: 52, borderRadius: 16, marginTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, buttonText: { fontSize: 14, fontFamily: 'Inter_700Bold' }, preview: { marginTop: 18, padding: 16, borderWidth: 1, borderRadius: 16, gap: 10 }, previewTitle: { fontSize: 16, fontFamily: 'Inter_700Bold' }, note: { fontSize: 11, lineHeight: 16 }, features: { marginTop: 20, gap: 10 }, feature: { borderWidth: 1, borderRadius: 16, padding: 14 }, featureTitle: { fontSize: 14, fontFamily: 'Inter_700Bold', marginBottom: 4 } });
