import { LegalDocumentScreen } from '@/features/app-shell/LegalDocumentScreen';

const sections = [
  { title: '1. Acceptance of Terms', body: 'Last Updated: September 21, 2026\n\nBy downloading, installing, accessing or using Nexus Plus, you agree to these Terms and Conditions and the Privacy Policy. If you do not agree, do not use the application.' },
  { title: '2. Service Scope', body: 'Nexus Plus is a multi-utility application. Depending on the installed build, device and enabled services, it can provide document and PDF tools, e-paper tools, audio/media and voice tools, text-to-speech, reminders, accessibility functions, Secure Vault and Password Manager, file management and encryption, Expense Tracker, Payment Announcer, QR and calculator utilities, Discover/RSS content, AI-assisted tools, nearby file transfer, PC Remote Control, TV Remote Control, casting, and camera/CCTV and connected-device utilities.' },
  { title: '3. License and Intellectual Property', body: 'Nexus Wave Technologies grants you a personal, non-exclusive, non-transferable and revocable license to use Nexus Plus according to these terms. Nexus Plus software, branding, design, original content and associated intellectual property remain owned by Nexus Wave Technologies or applicable licensors. Do not reverse engineer, decompile, modify, redistribute, sublicense or create derivative works from protected components except where applicable law or a license expressly permits it.' },
  { title: '4. Authorized and Lawful Use', body: 'Use Nexus Plus only for lawful purposes and only with accounts, files, computers, networks, cameras, TVs, phones, displays and other devices or services that you own or are expressly authorized to access or control. Do not use the app for unauthorized access, surveillance, credential theft, privacy invasion, security bypass, disruption, unlawful monitoring or interference with third-party services.' },
  { title: '5. Secure Vault and Password Manager', body: 'You are responsible for the accuracy and security of credentials you save in Secure Vault/Password Manager. Do not store secrets you are not authorized to possess. The Vault provides security safeguards but does not make a compromised device or account safe. Protect your Android screen lock and account credentials. Generated passwords should be reviewed before use, and any copy/share action remains your responsibility.' },
  { title: '6. Google Drive Cloud Sync', body: 'Google Drive synchronization is optional and available only when the required production configuration is present and the user authorizes Google Drive. Nexus Plus is designed to use the Google Drive application-data area rather than ordinary Drive folders. Cloud payloads are encrypted before upload. If Drive configuration or authorization is unavailable, the application continues in local-only mode. Google Drive remains a third-party service governed by Google terms and policies.' },
  { title: '7. Geeta Nexus', body: 'Geeta Nexus was previously a standalone spiritual-reading experience and is now integrated into Nexus Plus for unified management. The currently available library is Bhagavad Gita reading and chapter navigation with local progress. Future sacred-text libraries are not represented as available until verified content is integrated.' },
  { title: '8. Documents, PDF and E-Paper', body: 'Document Studio, document creator, importer, scanner, reader, summarizer, translator, PDF tools and e-paper tools process content you select or create. Some operations may use local/native engines; others may depend on configured external services. You are responsible for having the rights and permissions needed to process or distribute source material.' },
  { title: '9. PC Remote Control', body: 'PC Remote Control is intended for your own computer or a computer for which you have explicit permission. You are responsible for pairing, credentials, local-network security, endpoint configuration and commands sent through the connection. Do not use Remote Control to access or manipulate a third-party computer without authorization.' },
  { title: '10. TV Remote Control and Connected Displays', body: 'TV Remote Control, TV app launching, all-apps control, connection setup and related functions are intended for authorized TVs and connected displays. Device compatibility, vendor protocols, network access, IR hardware and other transports may affect availability. You are responsible for the devices and accounts you connect.' },
  { title: '11. Camera, CCTV and Connected Devices', body: 'CCTV and connected-device tools may discover, authenticate, view, record, replay, configure, control, erase or otherwise operate supported devices only when you are authorized to do so. You are solely responsible for complying with privacy, consent, surveillance, recording, telecommunications and data-protection laws. Nexus Plus does not grant surveillance rights.' },
  { title: '12. Accessibility and Access Focus', body: 'Accessibility-related functions are intended to support users with device navigation, focus, interaction or assistive workflows. Where Nexus Plus uses Android AccessibilityService or another sensitive accessibility API, the app must disclose the purpose in-app, obtain required affirmative consent and rely on Android’s permission controls. Do not use accessibility functions to bypass security controls, prevent users from disabling the service, or perform undisclosed autonomous actions.' },
  { title: '13. Audio, Voice and Text-to-Speech', body: 'Audio Editor, Voice Studio, Voice Changer, recording, karaoke, voice-over, effects, trimming, compression, speed/pitch and text-to-speech features may depend on device engines, downloaded models, ONNX files or other configured capabilities. You are responsible for rights to source recordings, voices, scripts and models. Generated or transformed audio should not be used for unlawful impersonation, fraud or unauthorized disclosure.' },
  { title: '14. AI, Vision and Automated Results', body: 'AI, Vision Assist, Assistant, summarization, classification, transcription and other automated results may be incomplete, inaccurate, outdated or inappropriate. Verify important outputs independently. Nexus Plus is not a substitute for professional legal, medical, financial, security or other expert advice.' },
  { title: '15. Discover and Third-Party Content', body: 'Discover/RSS features retrieve content from third-party publishers. The source publisher remains responsible for the content, accuracy, rights, availability and privacy practices of its service. External links may subject you to additional terms and tracking.' },
  { title: '16. Nearby File Transfer and Media Sharing', body: 'Send File and related transfer tools are for devices and recipients you are authorized to use. Verify the destination before sending. You remain responsible for the content transferred and for complying with applicable law and third-party rights.' },
  { title: '17. Expense Tracker and Payment Announcer', body: 'Expense Tracker, Payment Announcer, calculator and related utilities are organizational/convenience features and are not banks, payment processors, financial institutions, or financial advisers. Automated parsing, detection and announcements can be wrong. Verify important transactions with the relevant provider. An announcement is not proof of successful payment.' },
  { title: '18. QR, Reminders, Time and General Utilities', body: 'QR tools may process URLs, contact information, Wi-Fi configuration or UPI identifiers you choose to scan or encode. Reminder, alarm, time, stopwatch and world-clock features depend on Android scheduling and notification behavior. Review important content and schedules before relying on them.' },
  { title: '19. Accounts, Credentials and Security', body: 'You are responsible for protecting your account, device lock, passwords, API keys, camera credentials, payment credentials and other secrets. Do not share them unnecessarily. We may restrict access to protected services for security, abuse prevention, legal compliance or service integrity.' },
  { title: '20. Permissions and User Choice', body: 'Nexus Plus requests Android permissions only for relevant feature operations and does not guarantee that every feature will work if a required permission is denied. Permissions can be revoked through Android settings. Certain sensitive APIs may require a separate in-app disclosure and affirmative consent immediately before the permission or service is requested.' },
  { title: '21. App Integrity and Tamper Protection', body: 'Production releases may use release signing, Play Integrity and backend authorization to protect accounts, synchronized information and privileged API operations. An untrusted, modified or re-signed build may be limited to local or read-only functionality or denied protected access. Integrity enforcement is an access-control measure and must not intentionally corrupt or delete user data.' },
  { title: '22. Availability and Device Compatibility', body: 'Nexus Plus is provided on an “as is” and “as available” basis to the maximum extent permitted by law. Features may depend on Android version, hardware, native libraries, permissions, protocols, network conditions, account configuration and third-party services. We do not guarantee uninterrupted operation or compatibility with every device or service.' },
  { title: '23. User Content and Responsibility', body: 'You remain responsible for files, media, commands, credentials, documents, recordings and other content that you create, upload, capture, transmit or process through Nexus Plus. You represent that you have the required rights and authorization.' },
  { title: '24. Third-Party Services', body: 'Nexus Plus can interact with Supabase, Google, Firebase, RSS publishers, AI/document/media providers, device vendors and other third-party services. Those services have their own terms, privacy policies, retention practices and availability. Your use of a third-party service through Nexus Plus may be subject to that service’s rules.' },
  { title: '25. Account Deletion and Termination', body: 'You may stop using the application at any time. Where available, you may request account deletion through the app account controls or by contacting info@nexusweb.co.in. We may suspend or restrict access when reasonably necessary for security, abuse prevention, legal compliance or material violation of these terms. Third-party data may require separate deletion under the provider’s process.' },
  { title: '26. Security Disclaimer', body: 'We use reasonable technical safeguards, including protected device storage, authentication gates, Android security APIs, encrypted cloud envelopes and authorization checks where applicable. No application, device, network, cloud service or authentication system is completely secure. Keep Android, Nexus Plus and connected devices updated.' },
  { title: '27. Limitation of Liability', body: 'To the maximum extent permitted by applicable law, Nexus Wave Technologies is not liable for indirect, incidental, special or consequential losses arising from use or inability to use the app, third-party services, inaccurate automated results, network or hardware failures, unsupported devices, or unauthorized activity caused by user configuration or credential handling. Nothing excludes a right or remedy that cannot lawfully be excluded.' },
  { title: '28. Changes to These Terms', body: 'We may update these Terms when the app, providers, security practices or legal requirements change. The current version and Last Updated date are shown in the app. Continued use after an update constitutes acceptance to the extent permitted by applicable law.' },
  { title: '29. Contact', body: 'Nexus Wave Technologies\nFounder: Kuldeep\nWebsite: nexusweb.co.in\nEmail: info@nexusweb.co.in\n\nDo not include passwords, recovery codes, API keys, payment credentials or private camera passwords in support requests.' },
];

export default function TermsAndConditionsScreen() {
  return <LegalDocumentScreen title="Terms & Conditions" subtitle="Rules for lawful, safe, secure and responsible use of Nexus Plus and its connected-device capabilities." sections={sections} />;
}
