import { LegalDocumentScreen } from '@/features/app-shell/LegalDocumentScreen';

const en = [
  { title: '1. Acceptance', body: 'Last updated: 25 September 2026. By downloading, installing or using Nexus Plus, you agree to these Terms and the Privacy Policy. If you do not agree, please do not use the app.' },
  { title: '2. About Nexus Plus', body: 'Nexus Plus is a multi-utility Android application. Depending on your device and the enabled services, it can include productivity, document/PDF, media and audio, voice, accessibility, security, file transfer, remote control, AI-assisted and other utilities.' },
  { title: '3. Lawful and authorized use', body: 'Use Nexus Plus only for lawful purposes and only with accounts, files, devices, networks, cameras, TVs and services that you own or are authorized to access. Do not use the app for unauthorized access, surveillance, credential theft, privacy invasion, security bypass or unlawful monitoring.' },
  { title: '4. Your content and responsibility', body: 'You remain responsible for the content you create, upload, record, capture, transmit or process through Nexus Plus. You must have the necessary rights and permissions to use that content.' },
  { title: '5. Secure Vault and Password Manager', body: 'You are responsible for the secrets and credentials you choose to save, and for protecting your device and account credentials. Security features reduce risk but cannot make a compromised device completely safe.' },
  { title: '6. Payments, Premium and UPI', body: 'Nexus Plus may offer Premium memberships, AI credits or other paid digital services. The available payment method is shown in the app. The current purchase flow can create a UPI payment request using the configured payment details. Nexus Plus does not require you to share your UPI PIN, bank password or OTP. Paid access is activated only after the payment is successfully verified through the configured verification process.' },
  { title: '7. Fees and refund policy', body: 'Unless applicable law requires otherwise, fees paid for Premium memberships, AI credits or other paid digital services are non-refundable after purchase. Please confirm the selected plan, price, duration and benefits before making payment. Failed or duplicated transactions may be reviewed and corrected where appropriate. Any legally required refund will be handled according to applicable law and the relevant payment provider process.' },
  { title: '8. Google Drive', body: 'Google Drive backup and sync are optional. When enabled, Nexus Plus can use app-specific Google Drive storage for supported backups. Google’s own terms and privacy policies apply to Google services.' },
  { title: '9. Geeta Nexus', body: 'Geeta Nexus is integrated into Nexus Plus for spiritual reading and related features. Available content is subject to the version of the app and the verified content library included with it.' },
  { title: '10. Accessibility', body: 'Accessibility features are intended to support navigation, focus, interaction and assistive workflows. Where Android AccessibilityService is used, Nexus Plus provides the relevant disclosure and uses Android permission controls. Do not use accessibility features for unauthorized or undisclosed actions.' },
  { title: '11. Audio, voice and AI', body: 'Audio Editor, Voice Studio, text-to-speech, voice processing and AI-assisted tools may depend on device capabilities, downloaded models or configured external services. Automated results may be inaccurate. Verify important information independently.' },
  { title: '12. Remote control, CCTV and file transfer', body: 'Remote control, TV control, CCTV and Send File features are for devices and recipients you are authorized to use. You are responsible for device configuration, credentials, permissions and the content you transfer or access.' },
  { title: '13. Permissions', body: 'Nexus Plus requests Android permissions for relevant features. You may deny or later revoke permissions through Android settings, but features that depend on those permissions may not work.' },
  { title: '14. Third-party services', body: 'Nexus Plus may use or connect to third-party services such as authentication, cloud, notification, AI/document/media and device services. Those services have separate terms, privacy policies and availability.' },
  { title: '15. Availability and compatibility', body: 'Features can depend on Android version, hardware, network conditions, permissions, account configuration and third-party services. We do not guarantee uninterrupted availability or compatibility with every device.' },
  { title: '16. Account deletion and termination', body: 'You can stop using Nexus Plus at any time. Where available, you may request account deletion through the app or by contacting info@nexusweb.co.in. Access may be restricted when reasonably necessary for security, abuse prevention, legal compliance or serious violations of these Terms.' },
  { title: '17. Security', body: 'We use reasonable technical safeguards, but no app, device, network or cloud service can be guaranteed completely secure. Keep Android, Nexus Plus and connected devices updated and protect your credentials.' },
  { title: '18. Changes to these Terms', body: 'We may update these Terms when the app, payment services, providers, security practices or legal requirements change. The current version and update date are shown in the app.' },
  { title: '19. Contact', body: 'Nexus Wave Technologies\nFounder: Kuldeep\nWebsite: nexusweb.co.in\nEmail: info@nexusweb.co.in' },
];

const hi = [
  { title: '1. स्वीकृति', body: 'अंतिम अपडेट: 25 सितंबर 2026। Nexus Plus को डाउनलोड, इंस्टॉल या उपयोग करने पर आप इन Terms और Privacy Policy से सहमत होते हैं। सहमत न होने पर ऐप का उपयोग न करें।' },
  { title: '2. Nexus Plus के बारे में', body: 'Nexus Plus एक multi-utility Android application है। आपके device और enabled services के अनुसार इसमें productivity, document/PDF, media और audio, voice, accessibility, security, file transfer, remote control, AI-assisted और अन्य सुविधाएँ हो सकती हैं।' },
  { title: '3. कानूनी और अधिकृत उपयोग', body: 'Nexus Plus का उपयोग केवल कानूनी उद्देश्यों के लिए और केवल उन्हीं accounts, files, devices, networks, cameras, TVs और services के साथ करें जिनका उपयोग करने का अधिकार आपको है। Unauthorized access, surveillance, credential theft, privacy invasion, security bypass या unlawful monitoring के लिए ऐप का उपयोग न करें।' },
  { title: '4. आपकी सामग्री और जिम्मेदारी', body: 'आप Nexus Plus के माध्यम से बनाई, upload, record, capture, transfer या process की गई सामग्री के लिए जिम्मेदार हैं। उस सामग्री के उपयोग के लिए आवश्यक rights और permissions आपके पास होने चाहिए।' },
  { title: '5. Secure Vault और Password Manager', body: 'आप जिन secrets और credentials को सेव करते हैं और अपने device/account को सुरक्षित रखने की जिम्मेदारी आपकी है। Security features risk को कम करते हैं, लेकिन compromised device को पूरी तरह सुरक्षित बनाने की गारंटी नहीं देते।' },
  { title: '6. Payments, Premium और UPI', body: 'Nexus Plus में Premium membership, AI credits या अन्य paid digital services उपलब्ध हो सकती हैं। उपलब्ध payment method ऐप में दिखाया जाता है। मौजूदा purchase flow configured payment details का उपयोग करके UPI payment request बना सकता है। Nexus Plus आपसे UPI PIN, bank password या OTP शेयर करने के लिए नहीं कहता। Paid access payment की सफल verification के बाद ही activate किया जाता है।' },
  { title: '7. Fees और refund policy', body: 'जहाँ लागू कानून कुछ और न कहता हो, Premium membership, AI credits या अन्य paid digital services के लिए purchase के बाद दी गई fee non-refundable है। Payment से पहले plan, price, duration और benefits ध्यान से जांचें। Failed या duplicate transaction की उचित स्थिति में समीक्षा और correction की जा सकती है। जहाँ कानूनन refund आवश्यक हो, उसे लागू कानून और संबंधित payment provider की प्रक्रिया के अनुसार handle किया जाएगा।' },
  { title: '8. Google Drive', body: 'Google Drive backup और sync optional हैं। इन्हें enable करने पर Nexus Plus supported backups के लिए app-specific Google Drive storage का उपयोग कर सकता है। Google की अपनी terms और privacy policies लागू होती हैं।' },
  { title: '9. Geeta Nexus', body: 'Geeta Nexus को spiritual reading और related features के लिए Nexus Plus में integrate किया गया है। उपलब्ध content ऐप के version और verified content library पर निर्भर करता है।' },
  { title: '10. Accessibility', body: 'Accessibility सुविधाएँ navigation, focus, interaction और assistive workflows में सहायता के लिए हैं। जहाँ Android AccessibilityService का उपयोग होता है, Nexus Plus जरूरी disclosure देता है और Android permission controls का पालन करता है। Unauthorized या undisclosed actions के लिए accessibility features का उपयोग न करें।' },
  { title: '11. Audio, voice और AI', body: 'Audio Editor, Voice Studio, text-to-speech, voice processing और AI-assisted tools device capabilities, downloaded models या configured external services पर निर्भर हो सकते हैं। Automated results गलत हो सकते हैं। महत्वपूर्ण जानकारी को स्वतंत्र रूप से verify करें।' },
  { title: '12. Remote control, CCTV और file transfer', body: 'Remote control, TV control, CCTV और Send File सुविधाएँ उन्हीं devices और recipients के लिए हैं जिनका उपयोग करने की अनुमति आपको है। Device configuration, credentials, permissions और transferred/accessed content की जिम्मेदारी आपकी है।' },
  { title: '13. Permissions', body: 'Nexus Plus relevant features के लिए Android permissions मांगता है। आप Android settings से permission deny या बाद में revoke कर सकते हैं, लेकिन उस permission पर निर्भर feature काम नहीं कर सकता।' },
  { title: '14. Third-party services', body: 'Nexus Plus authentication, cloud, notification, AI/document/media और device services जैसे third-party services का उपयोग या उनसे connection कर सकता है। उनकी अपनी terms, privacy policies और availability लागू होती है।' },
  { title: '15. Availability और compatibility', body: 'Features Android version, hardware, network conditions, permissions, account configuration और third-party services पर निर्भर हो सकती हैं। हर device पर uninterrupted availability या compatibility की गारंटी नहीं है।' },
  { title: '16. Account deletion और termination', body: 'आप किसी भी समय Nexus Plus का उपयोग बंद कर सकते हैं। जहाँ उपलब्ध हो, app के माध्यम से या info@nexusweb.co.in पर संपर्क करके account deletion का अनुरोध किया जा सकता है। Security, abuse prevention, legal compliance या गंभीर terms violation की स्थिति में access सीमित किया जा सकता है।' },
  { title: '17. Security', body: 'हम उचित technical safeguards का उपयोग करते हैं, लेकिन किसी भी app, device, network या cloud service को पूरी तरह secure होने की गारंटी नहीं दी जा सकती। Android, Nexus Plus और connected devices को updated रखें और credentials सुरक्षित रखें।' },
  { title: '18. Terms में बदलाव', body: 'App, payment services, providers, security practices या कानूनी आवश्यकताओं में बदलाव होने पर हम इन Terms को update कर सकते हैं। ऐप में current version और update date दिखाई जाएगी।' },
  { title: '19. संपर्क', body: 'Nexus Wave Technologies\nसंस्थापक: Kuldeep\nWebsite: nexusweb.co.in\nEmail: info@nexusweb.co.in' },
];

export default function TermsAndConditionsScreen() {
  return (
    <LegalDocumentScreen
      title="Terms & Conditions"
      subtitle="Simple, clear terms for using Nexus Plus, its features and paid services."
      sections={{ en, hi }}
    />
  );
}
