import { LegalDocumentScreen } from '@/features/app-shell/LegalDocumentScreen';

const sections = [
  { title: '1. Acceptance of Terms', body: 'Last Updated: September 21, 2026\n\nBy downloading, installing, accessing or using Nexus Plus, you agree to these Terms and Conditions and the Privacy Policy. If you do not agree, do not use the application.' },
  { title: '2. About Nexus Plus', body: 'Nexus Plus is a multi-utility application developed by Nexus Wave Technologies. Depending on device capabilities and enabled services, features may include documents and PDF utilities, e-paper generation, audio and media tools, voice and text-to-speech workflows, reminders and accessibility tools, file management and protection, Expense Tracker, Payment Announcer, QR and calculator utilities, content discovery, AI-assisted utilities, PC Remote Control, Screen Mirroring, nearby file transfer, and camera/CCTV and connected-device tools.' },
  { title: '3. License and Intellectual Property', body: 'Nexus Wave Technologies grants you a personal, non-exclusive, non-transferable and revocable license to use Nexus Plus in accordance with these terms. Nexus Plus software, branding, design, original content and associated intellectual property remain the property of Nexus Wave Technologies or their respective licensors. Except where permitted by applicable law or an applicable license, you must not reverse engineer, decompile, modify, redistribute, sublicense or create derivative works from protected components.' },
  { title: '4. Lawful and Authorized Use', body: 'Use Nexus Plus only for lawful purposes and only with accounts, computers, networks, cameras, files, devices and services that you own or are expressly authorized to access. You must not use the app for unauthorized remote access, surveillance, credential theft, privacy invasion, security bypass, disruption of systems, unlawful monitoring, or interference with third-party services.' },
  { title: '5. PC Remote Control', body: 'PC Remote Control is intended for your own computer or a computer for which you have explicit permission. You are responsible for pairing, credentials, local-network security, endpoint configuration and all activity performed through your authorized connection. Nexus Wave Technologies is not responsible for misuse or unauthorized access caused by your configuration or credentials.' },
  { title: '6. Screen Mirroring and Casting', body: 'Screen Mirroring is intended for authorized displays and computers. Complete-screen and specific-app projection use Android’s media-projection permission and system consent mechanisms. The app does not bypass Android screen-capture restrictions. Media casting and browser-based computer receiving may depend on supported device transports, local-network connectivity, browser support and user-approved permissions.' },
  { title: '7. Nearby File Transfer', body: 'Send File is intended for trusted file transfers between devices you are authorized to use. You are responsible for confirming the recipient and destination before transferring content and for complying with applicable laws and the rights of others. File-transfer availability may depend on Android permissions, local-network or wireless transport support, and device compatibility.' },
  { title: '8. Camera, CCTV and Connected Devices', body: 'You may use camera, CCTV and connected-device features only with equipment that you own or are expressly authorized to operate. Do not attempt to discover, access, monitor, record, control, erase or alter third-party camera systems without lawful authorization. Compliance with privacy, consent, surveillance, recording, property, telecommunications and data-protection laws is your responsibility. Nexus Plus does not grant surveillance rights.' },
  { title: '9. Security Verification and Feature Restrictions', body: 'Supported CCTV and connected-device integrations use authorization gates before privileged functions are enabled. Secure transport, authenticated communication and device identity checks may be required. Discovery information is treated as untrusted until verification succeeds. A camera or network endpoint that cannot pass the required security checks may be blocked from connection or control. Features may be disabled on devices that do not provide a verified compatible protocol or capability.' },
  { title: '10. Unauthorized Camera Use and Abuse Response', body: 'Unauthorized camera control, surveillance, recording, deletion or access is prohibited. We may investigate suspected abuse, suspend or restrict accounts or features, preserve relevant security records where lawful, and cooperate with appropriate authorities or service providers. Enforcement does not replace legal process.' },
  { title: '11. Financial-Assistance Features', body: 'Expense Tracker, Payment Announcer, calculator and related financial utilities are convenience tools. They are not banking services, payment processors, financial institutions, transaction authorization systems or financial advisers. Automated detection, calculations or announcements can be inaccurate. Always verify important financial information with your bank or payment provider. An app announcement is not proof that a transaction completed.' },
  { title: '12. Documents, PDF and E-Paper Tools', body: 'Document reading, PDF operations, conversion, file processing and e-paper generation are provided as utility features. Some conversions or processing may depend on configured external services or installed native engines. You remain responsible for the content and permissions associated with files you process. Do not use the app to process or distribute unlawful, infringing or unauthorized documents.' },
  { title: '13. Audio, Voice and Text-to-Speech Features', body: 'Audio Editor and related voice tools may record, edit, mix, convert, compress, apply effects, remove silence, change speed or pitch, and generate speech. Voice generation may use supported system voices or installed local models and native engines. The app may refuse operations when an engine, model, format or device capability is unavailable. You are responsible for rights to any source recordings and voice models you use.' },
  { title: '14. AI and Automated Results', body: 'AI-generated, automated, summarized, classified or otherwise machine-assisted results may be incomplete, inaccurate, outdated or inappropriate for your circumstances. Verify important information independently. Nexus Plus is not a substitute for professional legal, medical, financial, security or other expert advice.' },
  { title: '15. Discover and Third-Party Content', body: 'Nexus Discover may retrieve RSS headlines, summaries and links from publishers. Publisher content remains the responsibility of its source. Nexus Plus does not guarantee the accuracy, legality, availability, copyright status or continued accessibility of third-party content or websites. Opening an article or external service may subject you to additional terms and privacy policies.' },
  { title: '16. QR, Reminder, Time and General Utility Tools', body: 'QR tools may encode or scan content that you choose to process, including URLs, contact or messaging information, Wi-Fi configuration or UPI identifiers. Reminder and time tools depend on Android notification and scheduling capabilities. You are responsible for reviewing generated QR contents and schedules before relying on them.' },
  { title: '17. Accounts, Credentials and Security', body: 'You are responsible for maintaining the security of your account, device lock, credentials and connected-device secrets. Do not share passwords, recovery codes, API keys, camera credentials or payment credentials unnecessarily. We may restrict access where reasonably necessary for security, abuse prevention, legal compliance or service integrity.' },
  { title: '18. Privacy and Permissions', body: 'Your use of Nexus Plus is also governed by the Privacy Policy, which explains information processing, Android permissions, local storage, authentication, Firebase services, third-party APIs, connected-device handling, audio/document processing, security safeguards, retention and deletion. Permissions are requested for relevant features and may be revoked through device settings, subject to Android functionality.' },
  { title: '19. Accessibility', body: 'Nexus Wave Technologies aims to make Nexus Plus accessible and usable with supported Android accessibility technologies. Accessibility features may depend on Android, device hardware, screen readers, installed services and individual feature implementation. We continuously improve accessibility but cannot guarantee perfect compatibility with every device or assistive technology.' },
  { title: '20. Availability and Device-Dependent Features', body: 'Nexus Plus is provided on an “as is” and “as available” basis to the maximum extent permitted by law. We strive for reliability but do not guarantee uninterrupted operation, error-free behavior, compatibility with every device, or continued availability of a particular feature or third-party service. Some features require specific Android capabilities, native engines, permissions, protocols, network access, external providers or account configuration. Unavailable capabilities may be disabled rather than simulated.' },
  { title: '21. User Content and Responsibility', body: 'You remain responsible for information, files, media, commands, credentials and other content you enter, upload, capture, transmit or use through Nexus Plus. You represent that you have the rights and permissions necessary to use such content and services. Do not upload unlawful, infringing or unauthorized material.' },
  { title: '22. Security Disclaimer', body: 'We use reasonable technical safeguards, but no application, device, network, API, cloud service or authentication mechanism can be guaranteed completely secure. Security also depends on your device, operating system, network, credentials and third-party providers. Keep supported software updated and use appropriate device and account security.' },
  { title: '23. Limitation of Liability', body: 'To the maximum extent permitted by applicable law, Nexus Wave Technologies is not liable for indirect, incidental, special or consequential losses arising from use or inability to use the app, third-party services, inaccurate automated results, network or hardware failures, unsupported devices, unauthorized access caused by user configuration, or misuse of the application. Nothing in these terms excludes a right or remedy that cannot lawfully be excluded.' },
  { title: '24. Account Deletion and Termination', body: 'You may stop using Nexus Plus at any time and may request deletion of your account and associated account data through the account controls provided in the app, where available, or by contacting info@nexusweb.co.in. Deletion may require identity/account verification and may be limited by legal, fraud-prevention or security obligations. Data held independently by third-party providers is governed by their policies. We may suspend or restrict accounts where reasonably necessary for security, abuse prevention, legal compliance or violation of these terms.' },
  { title: '25. Changes to These Terms', body: 'We may revise these Terms when the app, services, providers or legal requirements change. The current version and Last Updated date will be shown in the app and, where appropriate, on our official website. Continued use after an update constitutes acceptance to the extent permitted by applicable law.' },
  { title: '26. Contact Us', body: 'Nexus Wave Technologies\nFounder: Kuldeep\nWebsite: nexusweb.co.in\nEmail: info@nexusweb.co.in\n\nFor support or legal requests, do not include passwords, API keys, payment credentials or other secrets.' },
];

export default function TermsAndConditionsScreen() {
  return <LegalDocumentScreen title="Terms & Conditions" subtitle="Clear rules for safe, lawful, accessible and responsible use of Nexus Plus." sections={sections} />;
}
