import * as Crypto from 'expo-crypto';
import * as SecureStore from 'expo-secure-store';
const KEYS = { configured: 'nexus.remote.protection.configured', salt: 'nexus.remote.protection.salt', verifier: 'nexus.remote.protection.verifier', computerId: 'nexus.remote.protection.computerId', computerName: 'nexus.remote.protection.computerName', agentUrl: 'nexus.remote.protection.agentUrl', failedAttempts: 'nexus.remote.protection.failedAttempts', lockUntil: 'nexus.remote.protection.lockUntil' };
const MAX_ATTEMPTS = 5; const LOCK_MS = 30_000;
async function hashPassword(password: string, salt: string) { return Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256, `${salt}:${password}`); }
export async function isRemoteComputerProtectionConfigured() { return (await SecureStore.getItemAsync(KEYS.configured)) === '1'; }
export async function configureRemoteComputerProtection(password: string, computerId: string, computerName: string, agentUrl: string) { if (password.length < 8) throw new Error('Protection Password must contain at least 8 characters.'); if (!computerId || !agentUrl) throw new Error('A paired computer agent is required before protection can be enabled.'); const salt = Crypto.getRandomBytes(16); const saltText = Array.from(salt).map((value) => value.toString(16).padStart(2, '0')).join(''); const verifier = await hashPassword(password, saltText); await SecureStore.setItemAsync(KEYS.salt, saltText); await SecureStore.setItemAsync(KEYS.verifier, verifier); await SecureStore.setItemAsync(KEYS.computerId, computerId); await SecureStore.setItemAsync(KEYS.computerName, computerName || 'Paired computer'); await SecureStore.setItemAsync(KEYS.agentUrl, agentUrl.trim()); await SecureStore.setItemAsync(KEYS.failedAttempts, '0'); await SecureStore.deleteItemAsync(KEYS.lockUntil); await SecureStore.setItemAsync(KEYS.configured, '1'); }
export async function verifyRemoteComputerProtection(password: string) { if (!(await isRemoteComputerProtectionConfigured())) return false; const lockUntil = Number(await SecureStore.getItemAsync(KEYS.lockUntil) || '0'); if (Date.now() < lockUntil) throw new Error('Protection Password is temporarily locked. Please try again shortly.'); const salt = await SecureStore.getItemAsync(KEYS.salt); const verifier = await SecureStore.getItemAsync(KEYS.verifier); if (!salt || !verifier) throw new Error('Protection data is incomplete. Pair the computer again.'); const candidate = await hashPassword(password, salt); if (candidate === verifier) { await SecureStore.setItemAsync(KEYS.failedAttempts, '0'); await SecureStore.deleteItemAsync(KEYS.lockUntil); return true; } const attempts = Number(await SecureStore.getItemAsync(KEYS.failedAttempts) || '0') + 1; await SecureStore.setItemAsync(KEYS.failedAttempts, String(attempts)); if (attempts >= MAX_ATTEMPTS) { await SecureStore.setItemAsync(KEYS.failedAttempts, '0'); await SecureStore.setItemAsync(KEYS.lockUntil, String(Date.now() + LOCK_MS)); } return false; }
export async function getProtectedComputer(): Promise<{ computerId: string; computerName: string; agentUrl: string } | null> { const computerId = await SecureStore.getItemAsync(KEYS.computerId); const agentUrl = await SecureStore.getItemAsync(KEYS.agentUrl); if (!computerId || !agentUrl) return null; return { computerId, computerName: (await SecureStore.getItemAsync(KEYS.computerName)) || 'Paired computer', agentUrl }; }
export async function clearRemoteComputerProtection() { await Promise.all(Object.values(KEYS).map((key) => SecureStore.deleteItemAsync(key))); }
let unlocked = false; export function isRemoteComputerSessionUnlocked() { return unlocked; } export function setRemoteComputerSessionUnlocked(value: boolean) { unlocked = value; }
