import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { useRadioPlayer } from '@/features/online-radio/RadioPlayerContext';

export default function NowPlayingScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { station, player, favorites, toggleFavorite } = useRadioPlayer();
  if (!station) return <View style={[styles.empty,{backgroundColor:colors.background}]}><MaterialCommunityIcons name="radio-tower" size={48} color={colors.primary}/><Text style={[styles.emptyTitle,{color:colors.foreground}]}>No station playing</Text><Text style={[styles.emptyText,{color:colors.mutedForeground}]}>Choose a station from the browser first.</Text><Pressable accessibilityRole="button" onPress={()=>router.push('/online-radio/stations' as never)} style={[styles.button,{backgroundColor:colors.primary}]}><Text style={{color:colors.primaryForeground,fontFamily:'Inter_700Bold'}}>Browse stations</Text></Pressable></View>;
  const favorite=favorites.includes(station.id);
  return <ScrollView style={[styles.screen,{backgroundColor:colors.background}]} contentContainerStyle={{paddingTop:insets.top+20,paddingBottom:insets.bottom+40}}>
    <View style={styles.center}><View style={[styles.art,{backgroundColor:colors.secondary}]}><MaterialCommunityIcons name="radio-tower" size={58} color={colors.primary}/></View><Text accessibilityRole="header" style={[styles.title,{color:colors.foreground}]}>{station.name}</Text><Text style={[styles.meta,{color:colors.mutedForeground}]}>{station.city} • {station.language} • {station.category}</Text></View>
    <View style={styles.controls}><Pressable accessibilityRole="button" accessibilityLabel="Previous station" onPress={player.previous} style={[styles.control,{borderColor:colors.border}]}><Feather name="skip-back" size={23} color={colors.foreground}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={player.state.isPlaying?'Pause radio':'Play radio'} onPress={player.toggle} style={[styles.mainControl,{backgroundColor:colors.primary}]}><Feather name={player.state.isPlaying?'pause':'play'} size={28} color={colors.primaryForeground}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Next station" onPress={player.next} style={[styles.control,{borderColor:colors.border}]}><Feather name="skip-forward" size={23} color={colors.foreground}/></Pressable></View>
    <View style={styles.controls}><Pressable accessibilityRole="button" accessibilityLabel={favorite?'Remove from favorites':'Add to favorites'} onPress={()=>toggleFavorite(station.id)} style={[styles.wide,{borderColor:colors.border}]}><Feather name={favorite?'heart':'heart'} size={18} color={favorite?colors.primary:colors.foreground}/><Text style={{color:colors.foreground,fontFamily:'Inter_600SemiBold'}}>{favorite?'Favorite':'Add to favorites'}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Stop radio" onPress={player.pause} style={[styles.wide,{borderColor:colors.border}]}><Feather name="square" size={17} color={colors.foreground}/><Text style={{color:colors.foreground,fontFamily:'Inter_600SemiBold'}}>Stop</Text></Pressable></View>
  </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:24},emptyTitle:{marginTop:14,fontSize:20,fontFamily:'Inter_700Bold'},emptyText:{marginTop:5,fontSize:13,textAlign:'center'},button:{marginTop:20,minHeight:46,borderRadius:14,paddingHorizontal:18,alignItems:'center',justifyContent:'center'},center:{paddingHorizontal:20,alignItems:'center'},art:{width:150,height:150,borderRadius:40,alignItems:'center',justifyContent:'center'},title:{marginTop:20,fontSize:23,textAlign:'center',fontFamily:'Inter_700Bold'},meta:{marginTop:5,fontSize:12},controls:{paddingHorizontal:20,marginTop:28,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:12},control:{width:52,height:52,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},mainControl:{width:66,height:66,borderRadius:22,alignItems:'center',justifyContent:'center'},wide:{minHeight:46,borderRadius:14,borderWidth:1,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:7}});
