import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import * as Notifications from 'expo-notifications';
import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { AccessibilityInfo, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { VOICE_CATALOG } from '@/features/voice-library/voiceCatalog';
import { getInstalledVoices, type InstalledVoice } from '@/features/voice-library/voiceStore';
import { configureReminderNotifications, scheduleReminder, rescheduleReminder } from './reminderScheduler';
import { deleteReminder, loadReminders, setReminderEnabled, snoozeReminder } from './reminderBackend';
import { upsertReminder } from './reminderStore';
import { speakReminder } from './reminderVoice';
import type { ReminderItem, ReminderScheduleKind } from './reminderTypes';
const PRESETS = ['5', '15', '30', '60'];
const MODES: { id: ReminderScheduleKind; label: string }[] = [{ id: 'delay', label: 'After delay' }, { id: 'at', label: 'Custom time' }, { id: 'daily', label: 'Daily' }, { id: 'weekly', label: 'Weekly' }, { id: 'interval', label: 'Repeat interval' }];
function pad(v: number) { return String(v).padStart(2, '0'); }
function nextTime() { const d = new Date(); d.setSeconds(0, 0); d.setMinutes(0); d.setHours(d.getHours() + 1); return d; }
function reminderTime(r: ReminderItem) { const d = new Date(r.scheduledFor); return Number.isNaN(d.getTime()) ? nextTime() : d; }
export default function ReminderScreen() {
 const colors=useColors(); const insets=useSafeAreaInsets(); const [title,setTitle]=useState(''); const [body,setBody]=useState(''); const [delayMinutes,setDelayMinutes]=useState('5'); const [language,setLanguage]=useState<'en-US'|'hi-IN'>('en-US'); const [voiceId,setVoiceId]=useState<string>(); const [installed,setInstalled]=useState<InstalledVoice[]>([]); const [reminders,setReminders]=useState<ReminderItem[]>([]); const [busy,setBusy]=useState(false); const [voiceStatus,setVoiceStatus]=useState(''); const [mode,setMode]=useState<ReminderScheduleKind>('delay'); const [customTime,setCustomTime]=useState(nextTime()); const [repeatEvery,setRepeatEvery]=useState('30'); const [editingId,setEditingId]=useState<string|null>(null);
 useEffect(()=>{void configureReminderNotifications().catch(()=>undefined); void getInstalledVoices().then(setInstalled).catch(()=>undefined); void loadReminders().then(setReminders).catch(()=>undefined);},[]);
 useEffect(()=>{const s=Notifications.addNotificationReceivedListener(n=>{const d=n.request.content.data as {type?:string;title?:string;body?:string;language?:string;voiceId?:string|null};if(d.type!=='nexus-reminder')return;const text=[d.title,d.body].filter(Boolean).join('. ');if(text){void speakReminder(text,d.language||'en-US',d.voiceId||undefined);AccessibilityInfo.announceForAccessibility(`Reminder: ${text}`);}});return()=>s.remove();},[]);
 const matchingVoices=useMemo(()=>installed.filter(v=>v.language.toLowerCase().startsWith(language.slice(0,2).toLowerCase())),[installed,language]);
 const preview=async()=>{const result=await speakReminder([title.trim(),body.trim()].filter(Boolean).join('. ')||'This is your Nexus Plus reminder.',language,voiceId);setVoiceStatus(result.mode==='piper'?`Downloaded voice: ${result.voice?.name??'selected voice'}`:'System TTS fallback is active');};
 const reset=()=>{setEditingId(null);setTitle('');setBody('');setDelayMinutes('5');setMode('delay');setRepeatEvery('30');setCustomTime(nextTime());};
 const save=async()=>{if(busy)return;setBusy(true);try{if(editingId){const old=reminders.find(r=>r.id===editingId);if(!old)return;const replacement=await rescheduleReminder(old,{title,body,delayMinutes,language,voiceId,scheduleKind:mode,scheduledFor:['at','daily','weekly'].includes(mode)?customTime.toISOString():undefined,repeatEveryMinutes:mode==='interval'?Math.max(1,Number.parseInt(repeatEvery,10)||30):undefined});setReminders(await upsertReminder({...replacement,id:old.id,createdAt:old.createdAt}));reset();AccessibilityInfo.announceForAccessibility('Reminder updated.');}else{const r=await scheduleReminder({title,body,delayMinutes,language,voiceId,scheduleKind:mode,scheduledFor:['at','daily','weekly'].includes(mode)?customTime.toISOString():undefined,repeatEveryMinutes:mode==='interval'?Math.max(1,Number.parseInt(repeatEvery,10)||30):undefined});setReminders(await upsertReminder(r));reset();AccessibilityInfo.announceForAccessibility(`Reminder scheduled for ${r.scheduledAt}.`);}}catch(e){AccessibilityInfo.announceForAccessibility(e instanceof Error?e.message:'Reminder could not be saved.');}finally{setBusy(false);}};
 const edit=(r:ReminderItem)=>{setEditingId(r.id);setTitle(r.title);setBody(r.body);setDelayMinutes(String(r.delayMinutes));setLanguage(r.language==='hi-IN'?'hi-IN':'en-US');setVoiceId(r.voiceId);setMode(r.scheduleKind);setRepeatEvery(String(r.repeatEveryMinutes||30));setCustomTime(reminderTime(r));};
 const toggle=async(r:ReminderItem)=>setReminders(await setReminderEnabled(r,!r.enabled));
 const snooze=async(r:ReminderItem)=>setReminders(await snoozeReminder(r,10));
 const remove=async(r:ReminderItem)=>setReminders(await deleteReminder(r));
 const adjust=(m:number)=>setCustomTime(d=>new Date(d.getTime()+m*60000));
 return <ScrollView style={[styles.screen,{backgroundColor:colors.background}]} contentContainerStyle={{paddingTop:insets.top+16,paddingBottom:insets.bottom+40}} keyboardShouldPersistTaps="handled">
  <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={()=>router.back()} style={[styles.back,{borderColor:colors.border}]}><Feather name="arrow-left" size={20} color={colors.foreground}/></Pressable><View style={{flex:1}}><Text accessibilityRole="header" style={[styles.title,{color:colors.foreground}]}>My Reminders</Text><Text style={{color:colors.mutedForeground}}>Plan tasks, schedules and voice alerts</Text></View></View>
  <View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><View style={styles.heading}><MaterialCommunityIcons name="bell-ring-outline" size={22} color={colors.primary}/><Text style={[styles.cardTitle,{color:colors.foreground}]}>{editingId?'Edit reminder':'Create reminder'}</Text></View>
   <TextInput accessibilityLabel="Reminder title" value={title} onChangeText={setTitle} placeholder="Reminder title" placeholderTextColor={colors.mutedForeground} style={[styles.input,{color:colors.foreground,borderColor:colors.border}]}/><TextInput accessibilityLabel="Reminder message" value={body} onChangeText={setBody} placeholder="Message (optional)" placeholderTextColor={colors.mutedForeground} multiline style={[styles.input,styles.message,{color:colors.foreground,borderColor:colors.border}]}/>
   <Text style={[styles.label,{color:colors.foreground}]}>Schedule type</Text><View style={styles.chips}>{MODES.map(x=><Pressable key={x.id} accessibilityRole="radio" accessibilityState={{selected:mode===x.id}} onPress={()=>setMode(x.id)} style={[styles.chip,{borderColor:colors.border,backgroundColor:mode===x.id?colors.primary:colors.background}]}><Text style={{color:mode===x.id?colors.primaryForeground:colors.foreground}}>{x.label}</Text></Pressable>)}</View>
   {mode==='delay'&&<><Text style={[styles.label,{color:colors.foreground}]}>Delay in minutes</Text><TextInput accessibilityLabel="Delay in minutes" value={delayMinutes} onChangeText={v=>setDelayMinutes(v.replace(/[^0-9]/g,''))} keyboardType="number-pad" style={[styles.input,{color:colors.foreground,borderColor:colors.border}]}/><View style={styles.chips}>{PRESETS.map(p=><Pressable key={p} onPress={()=>setDelayMinutes(p)} style={[styles.chip,{borderColor:colors.border,backgroundColor:delayMinutes===p?colors.primary:colors.background}]}><Text style={{color:delayMinutes===p?colors.primaryForeground:colors.foreground}}>{p} min</Text></Pressable>)}</View></>}
   {(mode==='at'||mode==='daily'||mode==='weekly')&&<><Text style={[styles.label,{color:colors.foreground}]}>Custom time</Text><View style={styles.time}><Text style={[styles.timeValue,{color:colors.foreground}]}>{pad(customTime.getHours())}:{pad(customTime.getMinutes())}</Text><Pressable accessibilityRole="button" accessibilityLabel="15 minutes earlier" onPress={()=>adjust(-15)} style={[styles.small,{borderColor:colors.border}]}><Text style={{color:colors.foreground}}>−15</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="15 minutes later" onPress={()=>adjust(15)} style={[styles.small,{borderColor:colors.border}]}><Text style={{color:colors.foreground}}>+15</Text></Pressable></View></>}
   {mode==='interval'&&<><Text style={[styles.label,{color:colors.foreground}]}>Repeat every N minutes</Text><TextInput accessibilityLabel="Repeat interval" value={repeatEvery} onChangeText={v=>setRepeatEvery(v.replace(/[^0-9]/g,''))} keyboardType="number-pad" style={[styles.input,{color:colors.foreground,borderColor:colors.border}]}/></>}
   <Text style={[styles.label,{color:colors.foreground}]}>Language</Text><View style={styles.chips}>{(['en-US','hi-IN'] as const).map(x=><Pressable key={x} accessibilityRole="radio" accessibilityState={{selected:language===x}} onPress={()=>setLanguage(x)} style={[styles.chip,{borderColor:colors.border,backgroundColor:language===x?colors.primary:colors.background}]}><Text style={{color:language===x?colors.primaryForeground:colors.foreground}}>{x==='hi-IN'?'Hindi':'English'}</Text></Pressable>)}</View>
   <Text style={[styles.label,{color:colors.foreground}]}>Downloaded voice</Text>{matchingVoices.length===0?<Text style={{color:colors.mutedForeground,fontSize:11}}>No matching downloaded voice. System TTS will be used.</Text>:matchingVoices.map(v=><Pressable key={v.id} accessibilityRole="radio" accessibilityState={{selected:voiceId===v.id}} onPress={()=>setVoiceId(v.id)} style={[styles.voice,{borderColor:colors.border}]}><View style={{flex:1}}><Text style={[styles.voiceName,{color:colors.foreground}]}>{v.name}</Text><Text style={{color:colors.mutedForeground,fontSize:10}}>{v.languageName} · {v.quality} · downloaded</Text></View><Feather name={voiceId===v.id?'check-circle':'circle'} size={20} color={colors.primary}/></Pressable>)}
   <Pressable accessibilityRole="button" onPress={()=>void preview()} style={[styles.secondary,{borderColor:colors.border}]}><Feather name="volume-2" size={17} color={colors.foreground}/><Text style={{color:colors.foreground}}>Preview voice</Text></Pressable>{!!voiceStatus&&<Text accessibilityRole="status" style={{color:colors.primary,fontSize:11}}>{voiceStatus}</Text>}
   <View style={styles.action}><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void save()} style={[styles.primary,{backgroundColor:colors.primary,opacity:busy?.55:1}]}><Text style={{color:colors.primaryForeground,fontFamily:'Inter_700Bold'}}>{busy?'Saving…':editingId?'Update reminder':'Schedule reminder'}</Text></Pressable>{editingId&&<Pressable onPress={reset} style={[styles.cancel,{borderColor:colors.border}]}><Text style={{color:colors.foreground}}>Cancel</Text></Pressable>}</View>
  </View>
  <View style={styles.section}><Text style={[styles.sectionTitle,{color:colors.foreground}]}>Active reminders</Text>{reminders.length===0?<Text style={{color:colors.mutedForeground}}>No active reminders.</Text>:reminders.map(r=><View key={r.id} style={[styles.row,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[styles.rtitle,{color:colors.foreground}]}>{r.title}</Text>{!!r.body&&<Text style={{color:colors.mutedForeground,fontSize:11}}>{r.body}</Text>}<Text style={{color:colors.primary,fontSize:10}}>{r.enabled?'Enabled':'Disabled'} · {r.scheduleKind} · {r.scheduledAt}</Text><View style={styles.chips}><Pressable onPress={()=>edit(r)} style={[styles.mini,{borderColor:colors.border}]}><Text style={{color:colors.foreground}}>Edit</Text></Pressable><Pressable onPress={()=>void toggle(r)} style={[styles.mini,{borderColor:colors.border}]}><Text style={{color:colors.foreground}}>{r.enabled?'Disable':'Enable'}</Text></Pressable><Pressable onPress={()=>void snooze(r)} style={[styles.mini,{borderColor:colors.border}]}><Text style={{color:colors.foreground}}>Snooze 10m</Text></Pressable><Pressable onPress={()=>void remove(r)} style={[styles.mini,{borderColor:colors.border}]}><Text style={{color:colors.foreground}}>Delete</Text></Pressable></View></View>)}</View>
 </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1},header:{flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:20,marginBottom:16},back:{width:44,height:44,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center'},title:{fontSize:28,fontFamily:'Inter_700Bold'},card:{marginHorizontal:20,borderRadius:20,borderWidth:1,padding:16,gap:10},heading:{flexDirection:'row',alignItems:'center',gap:9},cardTitle:{fontSize:18,fontFamily:'Inter_700Bold'},input:{minHeight:48,borderWidth:1,borderRadius:13,paddingHorizontal:13,fontSize:14},message:{minHeight:82,textAlignVertical:'top',paddingTop:12},label:{fontSize:12,fontFamily:'Inter_700Bold',marginTop:3},chips:{flexDirection:'row',gap:7,flexWrap:'wrap'},chip:{minHeight:40,borderRadius:20,borderWidth:1,paddingHorizontal:13,alignItems:'center',justifyContent:'center'},time:{flexDirection:'row',alignItems:'center',gap:8},timeValue:{fontSize:28,fontFamily:'Inter_700Bold',minWidth:90},small:{minHeight:40,borderRadius:12,borderWidth:1,paddingHorizontal:12,alignItems:'center',justifyContent:'center'},voice:{minHeight:60,borderRadius:13,borderWidth:1,padding:12,flexDirection:'row',alignItems:'center'},voiceName:{fontSize:13,fontFamily:'Inter_700Bold'},secondary:{minHeight:46,borderRadius:13,borderWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},action:{flexDirection:'row',gap:8},primary:{minHeight:48,borderRadius:13,flex:1,alignItems:'center',justifyContent:'center'},cancel:{minHeight:48,borderRadius:13,borderWidth:1,paddingHorizontal:16,alignItems:'center',justifyContent:'center'},section:{marginTop:26,paddingHorizontal:20,gap:9},sectionTitle:{fontSize:19,fontFamily:'Inter_700Bold'},row:{borderRadius:15,borderWidth:1,padding:13,gap:5},rtitle:{fontSize:14,fontFamily:'Inter_700Bold'},mini:{minHeight:38,borderRadius:11,borderWidth:1,paddingHorizontal:11,alignItems:'center',justifyContent:'center'}});
