import { createAudioPlayer } from 'expo-audio';

// Add the real file at this exact path before building the APK.
// Supported extensions can be .mp3, .m4a, or .wav; the import below is generated by Metro.
export const SELFIE_SHUTTER_ASSET_NAME = 'selfie_shutter_nexus_01';

export async function playSelfieShutter(asset: number): Promise<void> {
  try {
    const player = createAudioPlayer(asset);
    player.volume = 1;
    player.play();
  } catch {
    // Capturing must never fail just because a custom shutter sound is unavailable.
  }
}
