import { Feather } from '@expo/vector-icons';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import type { FileManagerEntry } from '../FileManagerTypes';

export function FileManagerDeleteSheet({ entry, visible, onClose, onDelete }: { entry: FileManagerEntry | null; visible: boolean; onClose: () => void; onDelete: (entry: FileManagerEntry) => Promise<void> }) {
  const colors = useColors();
  const submit = async () => { if (!entry) return; await onDelete(entry); onClose(); };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose} accessibilityViewIsModal><View style={styles.backdrop}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} accessibilityLabel="Cancel delete" /><View style={[styles.sheet, { backgroundColor: colors.background, borderColor: colors.border }]}><View style={styles.handle} /><View style={[styles.icon, { backgroundColor: colors.secondary }]}><Feather name="trash-2" size={22} color={colors.destructive} /></View><Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>Delete item?</Text><Text style={[styles.body, { color: colors.mutedForeground }]}>{entry?.name ?? ''}{'\n'}This action cannot be undone.</Text><View style={styles.actions}><Pressable accessibilityRole="button" onPress={onClose} style={[styles.cancel, { borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: '700' }}>Cancel</Text></Pressable><Pressable accessibilityRole="button" onPress={submit} style={[styles.delete, { backgroundColor: colors.destructive }]}><Text style={{ color: colors.destructiveForeground, fontWeight: '700' }}>Delete</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' }, sheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, padding: 16, paddingBottom: 26 }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: '#888', opacity: 0.45, marginBottom: 15 }, icon: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 17, fontWeight: '700', marginTop: 10 }, body: { fontSize: 11, lineHeight: 17, marginTop: 5 }, actions: { flexDirection: 'row', gap: 9, marginTop: 16 }, cancel: { flex: 1, minHeight: 44, borderWidth: 1, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, delete: { flex: 1, minHeight: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' } });
