-- AI Audio Description catalog.
-- Basic is available on free accounts with a small monthly allowance.
-- Advanced is premium/credit based and uses higher-cost multimodal processing.

insert into public.premium_feature_catalog
(feature_code,feature_name,access_type,min_tier,credit_cost,is_active,description)
values
('audio_description_basic','Audio Description — Basic','FREE',1,4,true,
 'Create a concise accessibility-focused description of important video scenes and actions.'),
('audio_description_advanced','Audio Description — Advanced','CREDIT_BASED',2,12,true,
 'Create detailed scene-by-scene audio description with timestamps and richer visual context.')
on conflict (feature_code) do update set
  feature_name=excluded.feature_name,
  access_type=excluded.access_type,
  min_tier=excluded.min_tier,
  credit_cost=excluded.credit_cost,
  is_active=true,
  description=excluded.description;

create table if not exists public.audio_description_usage (
  usage_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check(mode in ('basic','advanced')),
  credits_charged integer not null check(credits_charged>0),
  video_duration_seconds integer,
  language text,
  provider text not null default 'gemini',
  created_at timestamptz not null default now()
);

alter table public.audio_description_usage enable row level security;
drop policy if exists "users can read own audio description usage" on public.audio_description_usage;
create policy "users can read own audio description usage"
on public.audio_description_usage for select to authenticated
using (auth.uid()=user_id);

create or replace function public.consume_audio_description_credits(
  p_mode text,
  p_video_duration_seconds integer default null
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  required_credits integer;
  current_balance integer;
  is_premium_user boolean;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_mode not in ('basic','advanced') then raise exception 'AUDIO_DESCRIPTION_MODE_INVALID'; end if;

  required_credits := case when p_mode='advanced' then 12 else 4 end;

  select exists(
    select 1 from public.user_subscriptions
    where user_id=auth.uid() and status='ACTIVE' and expires_at>now()
  ) into is_premium_user;

  if p_mode='advanced' and not is_premium_user then
    raise exception 'PREMIUM_REQUIRED';
  end if;

  select balance into current_balance
  from public.user_ai_credits
  where user_id=auth.uid()
  for update;

  if current_balance is null then current_balance := 0; end if;
  if current_balance < required_credits then
    raise exception 'INSUFFICIENT_CREDITS';
  end if;

  update public.user_ai_credits
  set balance=balance-required_credits,
      lifetime_used=coalesce(lifetime_used,0)+required_credits,
      updated_at=now()
  where user_id=auth.uid();

  insert into public.ai_credit_transactions(user_id,credit_plan_id,delta,reason,reference_id,metadata)
  values(
    auth.uid(),null,-required_credits,'AUDIO_DESCRIPTION',
    gen_random_uuid()::text,
    jsonb_build_object('mode',p_mode,'videoDurationSeconds',p_video_duration_seconds,'provider','gemini')
  );

  insert into public.audio_description_usage(user_id,mode,credits_charged,video_duration_seconds)
  values(auth.uid(),p_mode,required_credits,p_video_duration_seconds);

  return current_balance-required_credits;
end;
$$;

revoke all on function public.consume_audio_description_credits(text,integer) from public;
grant execute on function public.consume_audio_description_credits(text,integer) to authenticated;

