-- Subscription bundles let users buy more monthly credits upfront.
-- Existing subscription_plans remains the canonical entitlement table for the original 3 plans.

create table if not exists public.subscription_credit_bundles (
  bundle_id bigint generated by default as identity primary key,
  bundle_code text not null unique,
  bundle_name text not null,
  duration_days integer not null default 30 check(duration_days>0),
  price_inr numeric not null check(price_inr>0),
  included_credits integer not null check(included_credits>0),
  tier_level integer not null check(tier_level between 1 and 3),
  blocks_ads boolean not null default true,
  unlocks_premium_features boolean not null default true,
  is_active boolean not null default true,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.subscription_credit_bundles enable row level security;
drop policy if exists "public can read active bundles" on public.subscription_credit_bundles;
create policy "public can read active bundles"
on public.subscription_credit_bundles
for select to anon, authenticated
using (is_active=true);

insert into public.subscription_credit_bundles
(bundle_code,bundle_name,duration_days,price_inr,included_credits,tier_level,blocks_ads,unlocks_premium_features,is_active,description)
values
('creator_monthly','Creator',30,399,900,2,true,true,true,'Monthly membership with a larger included credit allowance.'),
('studio_monthly','Studio',30,799,2000,3,true,true,true,'Monthly membership for heavy AI, audio and video creation.'),
('creator_max_monthly','Creator Max',30,1499,5000,3,true,true,true,'High-capacity monthly membership for very heavy AI and video use.')
on conflict(bundle_code) do update set
  bundle_name=excluded.bundle_name,
  duration_days=excluded.duration_days,
  price_inr=excluded.price_inr,
  included_credits=excluded.included_credits,
  tier_level=excluded.tier_level,
  blocks_ads=excluded.blocks_ads,
  unlocks_premium_features=excluded.unlocks_premium_features,
  is_active=true,
  description=excluded.description,
  updated_at=now();

-- Bundle orders use the same payment_orders table and UPI verification flow.
create or replace function public.create_subscription_bundle_order(
  p_bundle_code text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  b public.subscription_credit_bundles%rowtype;
  v_id uuid;
  v_upi text;
  v_name text;
  v_provider text;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;

  select * into b
  from public.subscription_credit_bundles
  where bundle_code=p_bundle_code and is_active=true;

  if b.bundle_id is null then raise exception 'BUNDLE_NOT_FOUND'; end if;

  select setting_value into v_upi
  from public.payment_settings
  where setting_key='upi_id' and is_active=true;
  select setting_value into v_name
  from public.payment_settings
  where setting_key='payment_receiver_name' and is_active=true;
  select setting_value into v_provider
  from public.payment_settings
  where setting_key='payment_provider' and is_active=true;

  if v_upi is null then raise exception 'PAYMENT_NOT_CONFIGURED'; end if;

  insert into public.payment_orders(
    user_id,product_type,plan_code,amount_inr,upi_id,provider,status,provider_payload
  )
  values(
    auth.uid(),'PREMIUM',b.bundle_code,b.price_inr,v_upi,
    coalesce(v_provider,'UPI_MANUAL'),'PENDING',
    jsonb_build_object(
      'catalogType','SUBSCRIPTION_CREDIT_BUNDLE',
      'bundleCode',b.bundle_code,
      'includedCredits',b.included_credits,
      'durationDays',b.duration_days,
      'tierLevel',b.tier_level
    )
  )
  returning order_id into v_id;

  return jsonb_build_object(
    'orderId',v_id,
    'productType','PREMIUM',
    'planCode',b.bundle_code,
    'amountInr',b.price_inr,
    'includedCredits',b.included_credits,
    'durationDays',b.duration_days,
    'upiId',v_upi,
    'receiverName',coalesce(v_name,'Nexus Plus'),
    'provider',coalesce(v_provider,'UPI_MANUAL'),
    'status','PENDING'
  );
end;
$$;

revoke all on function public.create_subscription_bundle_order(text) from public;
grant execute on function public.create_subscription_bundle_order(text) to authenticated;

-- Verify/fulfil a bundle through the same admin UPI approval process.
create or replace function public.admin_verify_payment(
  p_order_id uuid,
  p_approved boolean,
  p_payment_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  o public.payment_orders%rowtype;
  sp public.subscription_plans%rowtype;
  cp public.credit_plans%rowtype;
  b public.subscription_credit_bundles%rowtype;
  v_start timestamptz;
  v_expiry timestamptz;
begin
  if not public.is_admin_user() then raise exception 'ADMIN_REQUIRED'; end if;

  select * into o from public.payment_orders where order_id=p_order_id for update;
  if o.order_id is null then raise exception 'ORDER_NOT_FOUND'; end if;
  if o.status='PAID' then
    return jsonb_build_object('orderId',o.order_id,'status','PAID','productType',o.product_type,'planCode',o.plan_code);
  end if;

  if not p_approved then
    update public.payment_orders
    set status='REJECTED',
        payment_reference=coalesce(p_payment_reference,payment_reference),
        verified_at=now(),
        verified_by=auth.uid(),
        failure_reason='Payment was rejected by an administrator'
    where order_id=o.order_id;
    return jsonb_build_object('orderId',o.order_id,'status','REJECTED');
  end if;

  if o.product_type='AI_CREDITS' then
    if not exists(
      select 1 from public.user_subscriptions
      where user_id=o.user_id and status='ACTIVE' and expires_at>now()
    ) then raise exception 'ACTIVE_SUBSCRIPTION_REQUIRED'; end if;

    select * into cp from public.credit_plans
    where plan_code=o.plan_code and is_active=true and plan_code like 'credit_topup_%';
    if cp.credit_plan_id is null then raise exception 'PLAN_NOT_FOUND'; end if;

    insert into public.user_ai_credits(user_id,balance,lifetime_purchased,lifetime_used,updated_at)
    values(o.user_id,cp.credits_offered,cp.credits_offered,0,now())
    on conflict(user_id) do update set
      balance=public.user_ai_credits.balance+excluded.balance,
      lifetime_purchased=public.user_ai_credits.lifetime_purchased+excluded.lifetime_purchased,
      updated_at=now();

    insert into public.ai_credit_transactions(user_id,credit_plan_id,delta,reason,reference_id,metadata)
    values(o.user_id,cp.credit_plan_id,cp.credits_offered,'AI_CREDIT_TOPUP',o.order_id::text,
      jsonb_build_object('topupPlan',cp.plan_code));
  else
    select * into b from public.subscription_credit_bundles
    where bundle_code=o.plan_code and is_active=true;

    if b.bundle_id is not null then
      v_start := now();
      select max(expires_at) into v_start
      from public.user_subscriptions
      where user_id=o.user_id and status='ACTIVE' and expires_at>now();

      v_start := coalesce(v_start,now());
      v_expiry := v_start + make_interval(days=>b.duration_days);

      insert into public.user_subscriptions(
        user_id,plan_id,status,starts_at,expires_at,gateway,gateway_subscription_id,auto_pay_enabled
      )
      select o.user_id,p.plan_id,'ACTIVE',v_start,v_expiry,'UPI_MANUAL',o.order_id::text,false
      from public.subscription_plans p
      where p.tier_level=b.tier_level and p.is_active=true
      order by p.tier_level desc
      limit 1;

      insert into public.user_ai_credits(user_id,balance,lifetime_purchased,lifetime_used,updated_at)
      values(o.user_id,b.included_credits,b.included_credits,0,now())
      on conflict(user_id) do update set
        balance=public.user_ai_credits.balance+excluded.balance,
        lifetime_purchased=public.user_ai_credits.lifetime_purchased+excluded.lifetime_purchased,
        updated_at=now();

      insert into public.ai_credit_transactions(user_id,credit_plan_id,delta,reason,reference_id,metadata)
      values(o.user_id,null,b.included_credits,'SUBSCRIPTION_BUNDLE_INCLUDED',o.order_id::text,
        jsonb_build_object('bundleCode',b.bundle_code,'tierLevel',b.tier_level));

      update public.profiles
      set is_premium=true,
          premium_until=greatest(coalesce(premium_until,'epoch'::timestamptz),v_expiry),
          role=case when role='admin'::app_role then role else 'premium'::app_role end,
          updated_at=now()
      where user_id=o.user_id;
    else
      select * into sp from public.subscription_plans
      where plan_code=o.plan_code and is_active=true;
      if sp.plan_id is null then raise exception 'PLAN_NOT_FOUND'; end if;

      v_start := now();
      select max(expires_at) into v_start
      from public.user_subscriptions
      where user_id=o.user_id and status='ACTIVE' and expires_at>now();
      v_start := coalesce(v_start,now());
      v_expiry := v_start + make_interval(days=>sp.duration_days);

      insert into public.user_subscriptions(
        user_id,plan_id,status,starts_at,expires_at,gateway,gateway_subscription_id,auto_pay_enabled
      ) values(o.user_id,sp.plan_id,'ACTIVE',v_start,v_expiry,'UPI_MANUAL',o.order_id::text,false);

      insert into public.user_ai_credits(user_id,balance,lifetime_purchased,lifetime_used,updated_at)
      values(o.user_id,sp.included_credits,sp.included_credits,0,now())
      on conflict(user_id) do update set
        balance=public.user_ai_credits.balance+excluded.balance,
        lifetime_purchased=public.user_ai_credits.lifetime_purchased+excluded.lifetime_purchased,
        updated_at=now();

      insert into public.ai_credit_transactions(user_id,credit_plan_id,delta,reason,reference_id,metadata)
      values(o.user_id,null,sp.included_credits,'MONTHLY_PLAN_INCLUDED',o.order_id::text,
        jsonb_build_object('planCode',sp.plan_code,'planTier',sp.tier_level));

      update public.profiles
      set is_premium=true,
          premium_until=greatest(coalesce(premium_until,'epoch'::timestamptz),v_expiry),
          role=case when role='admin'::app_role then role else 'premium'::app_role end,
          updated_at=now()
      where user_id=o.user_id;
    end if;
  end if;

  update public.payment_orders
  set status='PAID',payment_reference=coalesce(p_payment_reference,payment_reference),
      paid_at=now(),verified_at=now(),verified_by=auth.uid(),failure_reason=null
  where order_id=o.order_id;

  return jsonb_build_object('orderId',o.order_id,'status','PAID','productType',o.product_type,'planCode',o.plan_code);
end;
$$;
