-- Nexus Plus Premium billing foundation.
-- Razorpay secrets/webhook signing secrets must remain server-side.
-- Run this migration in the Supabase project.

create table if not exists public.subscription_plans (
  plan_id bigint generated by default as identity primary key,
  plan_code text unique not null,
  plan_name text not null,
  tier_level integer not null check (tier_level between 1 and 3),
  description text,
  price_inr numeric(10,2) not null check (price_inr >= 0),
  duration_days integer not null check (duration_days > 0),
  blocks_ads boolean not null default true,
  unlocks_premium_features boolean not null default false,
  is_auto_pay_supported boolean not null default true,
  razorpay_plan_id text unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.subscription_plans enable row level security;
drop policy if exists "public can read active subscription plans" on public.subscription_plans;
create policy "public can read active subscription plans"
  on public.subscription_plans
  for select
  to anon, authenticated
  using (is_active = true);

insert into public.subscription_plans
  (plan_code, plan_name, tier_level, description, price_inr, duration_days, blocks_ads, unlocks_premium_features, is_auto_pay_supported)
values
  ('lifeline_monthly', 'Lifeline', 1, 'Ad-free Nexus Plus with essential member perks.', 49, 30, true, false, true),
  ('super_monthly', 'Super', 2, 'Premium toolkit access for everyday power users.', 149, 30, true, true, true),
  ('pro_monthly', 'Pro', 3, 'Full Premium access for intensive media and AI workflows.', 399, 30, true, true, true)
on conflict (plan_code) do update set
  plan_name = excluded.plan_name,
  tier_level = excluded.tier_level,
  description = excluded.description,
  price_inr = excluded.price_inr,
  duration_days = excluded.duration_days,
  blocks_ads = excluded.blocks_ads,
  unlocks_premium_features = excluded.unlocks_premium_features,
  is_auto_pay_supported = excluded.is_auto_pay_supported,
  updated_at = now();

create table if not exists public.user_subscriptions (
  subscription_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_id bigint not null references public.subscription_plans(plan_id),
  auto_pay_enabled boolean not null default false,
  gateway text,
  gateway_customer_id text,
  gateway_subscription_id text unique,
  gateway_mandate_id text,
  status text not null check (status in ('ACTIVE','PAUSED','CANCELLED','EXPIRED','CREATED','PENDING')) default 'PENDING',
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists user_subscriptions_user_idx on public.user_subscriptions(user_id, status, expires_at desc);

alter table public.user_subscriptions enable row level security;
drop policy if exists "users can read their subscriptions" on public.user_subscriptions;
create policy "users can read their subscriptions"
  on public.user_subscriptions
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "users cannot write subscriptions directly" on public.user_subscriptions;
-- No INSERT/UPDATE policy is intentionally provided. Service-role/server code owns entitlement mutation.

create table if not exists public.payment_transactions (
  transaction_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_id bigint references public.subscription_plans(plan_id),
  subscription_id uuid references public.user_subscriptions(subscription_id) on delete set null,
  gateway text not null,
  gateway_order_id text unique,
  gateway_payment_id text unique,
  gateway_signature text,
  amount_inr numeric(10,2) not null check (amount_inr >= 0),
  currency text not null default 'INR',
  status text not null check (status in ('CREATED','AUTHORIZED','CAPTURED','FAILED','REFUNDED','PARTIAL_REFUND')) default 'CREATED',
  failure_code text,
  failure_reason text,
  raw_event jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_transactions_user_idx on public.payment_transactions(user_id, created_at desc);
create index if not exists payment_transactions_subscription_idx on public.payment_transactions(subscription_id);

alter table public.payment_transactions enable row level security;
drop policy if exists "users can read their payment history" on public.payment_transactions;
create policy "users can read their payment history"
  on public.payment_transactions
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Server-side RPC contract: app can request a checkout, but cannot grant itself Premium.
create or replace function public.create_premium_checkout(p_plan_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  plan_row public.subscription_plans;
begin
  select * into plan_row
  from public.subscription_plans
  where plan_code = p_plan_code and is_active = true;

  if not found then
    raise exception 'PREMIUM_PLAN_NOT_FOUND';
  end if;

  -- Actual Razorpay order/subscription creation must be performed by a trusted server/Edge Function.
  -- The RPC therefore returns validated product metadata and an explicit pending state.
  return jsonb_build_object(
    'planCode', plan_row.plan_code,
    'planName', plan_row.plan_name,
    'amountInr', plan_row.price_inr,
    'durationDays', plan_row.duration_days,
    'status', 'PENDING_SERVER_CHECKOUT'
  );
end;
$$;

revoke all on function public.create_premium_checkout(text) from public;
grant execute on function public.create_premium_checkout(text) to authenticated;

create or replace function public.get_my_premium_entitlement()
returns jsonb
language sql
security invoker
set search_path = public
as $$
  select coalesce((
    select jsonb_build_object(
      'status', s.status,
      'planCode', p.plan_code,
      'expiresAt', s.expires_at,
      'blocksAds', p.blocks_ads,
      'unlocksPremiumFeatures', p.unlocks_premium_features
    )
    from public.user_subscriptions s
    join public.subscription_plans p on p.plan_id = s.plan_id
    where s.user_id = auth.uid()
      and s.status = 'ACTIVE'
      and s.expires_at > now()
    order by s.expires_at desc
    limit 1
  ), jsonb_build_object(
    'status', null,
    'planCode', null,
    'expiresAt', null,
    'blocksAds', false,
    'unlocksPremiumFeatures', false
  ));
$$;

revoke all on function public.get_my_premium_entitlement() from public;
grant execute on function public.get_my_premium_entitlement() to authenticated;
