-- Dynamic UPI Premium billing model.
-- Admin/Supabase Dashboard owns plans and merchant UPI details.
-- The mobile client can read active plans and create a pending payment intent only.
-- Premium activation must be performed by a trusted verification service after UTR reconciliation.

create table if not exists public.app_subscription_plans (
  plan_id bigint generated by default as identity primary key,
  app_id uuid references public.applications(app_id) on delete cascade,
  plan_name text not null,
  amount numeric(10,2) not null check (amount > 0),
  upi_id text not null check (length(trim(upi_id)) >= 3),
  merchant_name text default 'Nexus Wave',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists app_subscription_plans_active_idx
  on public.app_subscription_plans(is_active, amount);

alter table public.app_subscription_plans enable row level security;
drop policy if exists "Active subscription plans are readable" on public.app_subscription_plans;
create policy "Active subscription plans are readable"
  on public.app_subscription_plans
  for select
  to authenticated
  using (is_active = true);

create table if not exists public.payment_transactions (
  transaction_id uuid default gen_random_uuid() primary key,
  app_id uuid references public.applications(app_id) on delete cascade,
  plan_id bigint not null references public.app_subscription_plans(plan_id),
  user_id uuid references auth.users(id) on delete cascade,
  utr_number text unique,
  amount_paid numeric(10,2) not null check (amount_paid > 0),
  payment_status text not null default 'PENDING' check (payment_status in ('PENDING','SUCCESS','FAILED')),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_transactions_user_idx
  on public.payment_transactions(user_id, created_at desc);

alter table public.payment_transactions enable row level security;
drop policy if exists "Users can create pending payment transactions" on public.payment_transactions;
create policy "Users can create pending payment transactions"
  on public.payment_transactions
  for insert
  to authenticated
  with check (auth.uid() = user_id and payment_status = 'PENDING' and utr_number is null);

drop policy if exists "Users can view own payment transactions" on public.payment_transactions;
create policy "Users can view own payment transactions"
  on public.payment_transactions
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Users must never be able to self-upgrade by writing SUCCESS, UTR, verified_at, or changing amount.
-- There is intentionally no authenticated UPDATE policy. A trusted verification worker owns those writes.

create or replace function public.create_upi_payment_transaction(p_plan_id bigint, p_app_id uuid default null)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  plan_row public.app_subscription_plans;
  new_tx public.payment_transactions;
begin
  select * into plan_row
  from public.app_subscription_plans
  where plan_id = p_plan_id
    and is_active = true;

  if not found then
    raise exception 'PREMIUM_PLAN_NOT_FOUND';
  end if;

  insert into public.payment_transactions (app_id, plan_id, user_id, amount_paid, payment_status)
  values (p_app_id, plan_row.plan_id, auth.uid(), plan_row.amount, 'PENDING')
  returning * into new_tx;

  return jsonb_build_object(
    'transactionId', new_tx.transaction_id,
    'planId', plan_row.plan_id,
    'amount', plan_row.amount,
    'upiId', plan_row.upi_id,
    'merchantName', coalesce(plan_row.merchant_name, 'Nexus Wave'),
    'status', new_tx.payment_status
  );
end;
$$;

revoke all on function public.create_upi_payment_transaction(bigint, uuid) from public;
grant execute on function public.create_upi_payment_transaction(bigint, uuid) to authenticated;

-- IMPORTANT: Do not auto-activate Premium from a client-controlled SUCCESS row.
-- The final trigger is intentionally replaced by a trusted verification function contract.
create or replace function public.verify_and_activate_premium(p_transaction_id uuid, p_utr text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  tx public.payment_transactions;
  plan_row public.app_subscription_plans;
begin
  select * into tx from public.payment_transactions where transaction_id = p_transaction_id for update;
  if not found then raise exception 'PAYMENT_TRANSACTION_NOT_FOUND'; end if;
  if tx.utr_number is not null then raise exception 'PAYMENT_ALREADY_VERIFIED'; end if;

  select * into plan_row from public.app_subscription_plans where plan_id = tx.plan_id;
  if not found then raise exception 'PREMIUM_PLAN_NOT_FOUND'; end if;

  -- This function is a server-side verification contract. It MUST only be executable
  -- by a trusted role/service that has already reconciled the UTR against the UPI payment.
  update public.payment_transactions
     set utr_number = nullif(trim(p_utr), ''),
         payment_status = 'SUCCESS',
         verified_at = now(),
         updated_at = now()
   where transaction_id = tx.transaction_id;

  return jsonb_build_object('success', true, 'transactionId', tx.transaction_id, 'status', 'SUCCESS');
end;
$$;

revoke all on function public.verify_and_activate_premium(uuid, text) from public;
-- Grant this function only to your trusted verification role/service in Supabase.

comment on column public.app_subscription_plans.upi_id is 'Merchant UPI VPA controlled by Admin/Supabase Dashboard; never hard-code in the mobile app.';
comment on column public.payment_transactions.utr_number is 'UPI UTR/reference recorded only after trusted payment reconciliation.';
