import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useRef, useState } from 'react';
import { Alert, BackHandler, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import QRCode from 'react-native-qrcode-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';

type Tab = 'text' | 'url' | 'wifi' | 'upi' | 'whatsapp';
type WifiSecurity = 'WPA' | 'WPA2' | 'WPA3' | 'WPA3-Enterprise';
type QRTheme = { foreground: string; background: string };
type QRCodeWithDataUrl = QRCode & { toDataURL: (callback: (data: string) => void) => void };
const BUSINESS_CATEGORIES = ['Groceries', 'Restaurant & Food', 'Cafe & Bakery', 'Retail', 'Clothing & Fashion', 'Electronics', 'Pharmacy', 'Medical', 'Education', 'Travel', 'Hotel & Stay', 'Salon & Beauty', 'Fitness & Gym', 'Home Services', 'Automotive', 'Fuel', 'Utilities', 'Professional Services', 'Freelance Services', 'Online Store', 'Donations', 'Other'];
const COLOR_PALETTE: Array<{ name: string; value: string }> = [['Black', '#000000'], ['White', '#FFFFFF'], ['Navy Blue', '#0B1F3A'], ['Dark Blue', '#123C73'], ['Blue', '#2563EB'], ['Sky Blue', '#0EA5E9'], ['Teal', '#0F766E'], ['Green', '#16A34A'], ['Dark Green', '#14532D'], ['Lime', '#65A30D'], ['Yellow', '#EAB308'], ['Orange', '#F97316'], ['Red', '#DC2626'], ['Maroon', '#7F1D1D'], ['Pink', '#DB2777'], ['Rose', '#E11D48'], ['Purple', '#7C3AED'], ['Deep Purple', '#4C1D95'], ['Violet', '#8B5CF6'], ['Indigo', '#4338CA'], ['Brown', '#92400E'], ['Slate', '#334155'], ['Gray', '#6B7280'], ['Silver', '#9CA3AF'], ['Cream', '#FFF7ED']].map(([name, value]) => ({ name, value }));
const tabs: Array<{ key: Tab; label: string; icon: string }> = [{ key: 'text', label: 'Text', icon: 'text' }, { key: 'url', label: 'URL', icon: 'link-variant' }, { key: 'whatsapp', label: 'WhatsApp', icon: 'whatsapp' }, { key: 'wifi', label: 'Wi‑Fi', icon: 'wifi' }, { key: 'upi', label: 'UPI', icon: 'currency-inr' }];
const escapeWifi = (value: string) => value.replace(/([\\;,\":])/g, '\\$1');
const BUSINESS_MODE_KEY = '@nexus-plus/qr-upi-business-mode';

export default function QRGeneratorScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const qrRef = useRef<QRCode>(null);
  const [tab, setTab] = useState<Tab>('text'); const [text, setText] = useState(''); const [ssid, setSsid] = useState(''); const [password, setPassword] = useState(''); const [security, setSecurity] = useState<WifiSecurity>('WPA2'); const [hidden, setHidden] = useState(false); const [enterpriseIdentity, setEnterpriseIdentity] = useState('');
  const [upiId, setUpiId] = useState(''); const [upiName, setUpiName] = useState(''); const [amount, setAmount] = useState(''); const [description, setDescription] = useState(''); const [businessMode, setBusinessMode] = useState(false); const [businessCategory, setBusinessCategory] = useState('Groceries'); const [businessModeLoaded, setBusinessModeLoaded] = useState(false);
  const [whatsappNumber, setWhatsappNumber] = useState(''); const [whatsappMessage, setWhatsappMessage] = useState(''); const [qrTheme, setQrTheme] = useState<QRTheme>({ foreground: '#000000', background: '#FFFFFF' }); const [size, setSize] = useState(240); const [quietZone, setQuietZone] = useState(12);
  const [generated, setGenerated] = useState(false); const [generatedValue, setGeneratedValue] = useState(''); const [generatedTheme, setGeneratedTheme] = useState<QRTheme>({ foreground: '#000000', background: '#FFFFFF' }); const [generatedSize, setGeneratedSize] = useState(240); const [generatedQuietZone, setGeneratedQuietZone] = useState(12);
  useFocusEffect(useCallback(() => { let active = true; AsyncStorage.getItem(BUSINESS_MODE_KEY).then((stored) => { if (!active) return; setBusinessMode(stored === 'true'); setBusinessModeLoaded(true); }).catch(() => active && setBusinessModeLoaded(true)); return () => { active = false; }; }, []));
  const requiredInputsReady = useMemo(() => { if (tab === 'text') return Boolean(text.trim()); if (tab === 'url') return /^https?:\/\/.+/i.test(text.trim()); if (tab === 'wifi') return Boolean(ssid.trim()) && Boolean(password) && Boolean(security); if (tab === 'upi') return Boolean(upiId.trim()) && Boolean(upiName.trim()) && Boolean(amount.trim()) && Number(amount) > 0 && (!businessMode || Boolean(businessCategory)); return /^\d{8,15}$/.test(whatsappNumber.replace(/\D/g, '')); }, [tab, text, ssid, password, security, upiId, upiName, amount, businessMode, businessCategory, whatsappNumber]);
  const value = useMemo(() => { if (!requiredInputsReady) return ''; if (tab === 'text' || tab === 'url') return text.trim(); if (tab === 'wifi') { const auth = security === 'WPA3-Enterprise' ? 'WPA2-EAP' : security; const identity = security === 'WPA3-Enterprise' && enterpriseIdentity.trim() ? `;E:${escapeWifi(enterpriseIdentity.trim())}` : ''; return `WIFI:T:${auth};S:${escapeWifi(ssid.trim())};P:${escapeWifi(password)};H:${hidden ? 'true' : 'false'}${identity};;`; } if (tab === 'upi') { const params = new URLSearchParams({ pa: upiId.trim(), pn: upiName.trim(), am: amount.trim(), cu: 'INR' }); if (description.trim()) params.set('tn', description.trim()); if (businessMode && businessCategory) params.set('mc', businessCategory); return `upi://pay?${params.toString()}`; } const digits = whatsappNumber.replace(/\D/g, ''); return `https://wa.me/${digits}${whatsappMessage.trim() ? `?text=${encodeURIComponent(whatsappMessage.trim())}` : ''}`; }, [requiredInputsReady, tab, text, ssid, password, security, hidden, enterpriseIdentity, upiId, upiName, amount, description, businessMode, businessCategory, whatsappNumber, whatsappMessage]);
  const clearAll = () => { setText(''); setSsid(''); setPassword(''); setEnterpriseIdentity(''); setUpiId(''); setUpiName(''); setAmount(''); setDescription(''); setWhatsappNumber(''); setWhatsappMessage(''); setSecurity('WPA2'); setHidden(false); setBusinessCategory('Groceries'); setQrTheme({ foreground: '#000000', background: '#FFFFFF' }); setSize(240); setQuietZone(12); setGenerated(false); setGeneratedValue(''); setGeneratedTheme({ foreground: '#000000', background: '#FFFFFF' }); setGeneratedSize(240); setGeneratedQuietZone(12); };
  const openEditorForRegenerate = () => { setGenerated(false); setGeneratedValue(''); setQrTheme(generatedTheme); setSize(generatedSize); setQuietZone(generatedQuietZone); };
  const validateAndGenerate = () => { if (!requiredInputsReady) return; if (qrTheme.foreground === qrTheme.background) return Alert.alert('Choose contrasting colors', 'QR color and background color must be different.'); setGeneratedValue(value); setGeneratedTheme(qrTheme); setGeneratedSize(size); setGeneratedQuietZone(quietZone); setGenerated(true); };
  const toggleBusinessMode = async () => { const next = !businessMode; setBusinessMode(next); try { await AsyncStorage.setItem(BUSINESS_MODE_KEY, String(next)); } catch { /* preference remains in memory */ } };
  const getQrPng = async () => { if (!generatedValue || !qrRef.current) throw new Error('QR code is not ready.'); return new Promise<string>((resolve, reject) => { let settled = false; const finish = (fn: (value: string) => void, value: string) => { if (!settled) { settled = true; clearTimeout(timer); fn(value); } }; const timer = setTimeout(() => finish(reject, 'Timed out while rendering the QR code.'), 5000); const ref = qrRef.current as QRCodeWithDataUrl; ref.toDataURL((data: string) => finish(resolve, data)); }); };
  const downloadQr = async () => { try { const base64 = await getQrPng(); const directory = FileSystem.documentDirectory; if (!directory) throw new Error('Device storage is unavailable.'); const fileUri = `${directory}nexus-plus-qr-${Date.now()}.png`; await FileSystem.writeAsStringAsync(fileUri, base64, { encoding: FileSystem.EncodingType.Base64 }); Alert.alert('QR code downloaded', 'The QR code PNG has been saved in Nexus Plus app storage.'); } catch (error) { Alert.alert('Download failed', error instanceof Error ? error.message : 'Could not save the QR code.'); } };
  const shareQr = async () => { try { const base64 = await getQrPng(); const directory = FileSystem.documentDirectory; if (!directory) throw new Error('Device storage is unavailable.'); const fileUri = `${directory}nexus-plus-qr-share-${Date.now()}.png`; await FileSystem.writeAsStringAsync(fileUri, base64, { encoding: FileSystem.EncodingType.Base64 }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(fileUri, { mimeType: 'image/png', dialogTitle: 'Share QR code' }); else await Share.share({ title: 'Nexus Plus QR code', message: generatedValue }); } catch (error) { Alert.alert('Share failed', error instanceof Error ? error.message : 'Could not share the QR code.'); } };
  useFocusEffect(useCallback(() => { const subscription = BackHandler.addEventListener('hardwareBackPress', () => { if (generated) { clearAll(); return true; } return false; }); return () => subscription.remove(); }, [generated]));
  return null;
}
