import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useRef, useState } from 'react';
import { Alert, BackHandler, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import QRCode from 'react-native-qrcode-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';

type Tab = 'text' | 'url' | 'wifi' | 'upi' | 'whatsapp';
type WifiSecurity = 'WPA' | 'WPA2' | 'WPA3' | 'WPA3-Enterprise';
type QRTheme = { foreground: string; background: string };

const BUSINESS_CATEGORIES = ['Groceries', 'Restaurant & Food', 'Cafe & Bakery', 'Retail', 'Clothing & Fashion', 'Electronics', 'Pharmacy', 'Medical', 'Education', 'Travel', 'Hotel & Stay', 'Salon & Beauty', 'Fitness & Gym', 'Home Services', 'Automotive', 'Fuel', 'Utilities', 'Professional Services', 'Freelance Services', 'Online Store', 'Donations', 'Other'];
const COLOR_PALETTE: Array<{ name: string; value: string }> = [['Black', '#000000'], ['White', '#FFFFFF'], ['Navy Blue', '#0B1F3A'], ['Dark Blue', '#123C73'], ['Blue', '#2563EB'], ['Sky Blue', '#0EA5E9'], ['Teal', '#0F766E'], ['Green', '#16A34A'], ['Dark Green', '#14532D'], ['Lime', '#65A30D'], ['Yellow', '#EAB308'], ['Orange', '#F97316'], ['Red', '#DC2626'], ['Maroon', '#7F1D1D'], ['Pink', '#DB2777'], ['Rose', '#E11D48'], ['Purple', '#7C3AED'], ['Deep Purple', '#4C1D95'], ['Violet', '#8B5CF6'], ['Indigo', '#4338CA'], ['Brown', '#92400E'], ['Slate', '#334155'], ['Gray', '#6B7280'], ['Silver', '#9CA3AF'], ['Cream', '#FFF7ED']].map(([name, value]) => ({ name, value }));
const tabs: Array<{ key: Tab; label: string; icon: string }> = [{ key: 'text', label: 'Text', icon: 'text' }, { key: 'url', label: 'URL', icon: 'link-variant' }, { key: 'whatsapp', label: 'WhatsApp', icon: 'whatsapp' }, { key: 'wifi', label: 'Wi‑Fi', icon: 'wifi' }, { key: 'upi', label: 'UPI', icon: 'currency-inr' }];
const escapeWifi = (value: string) => value.replace(/([\\;,\":])/g, '\\$1');
const BUSINESS_MODE_KEY = '@nexus-plus/qr-upi-business-mode';

export default function QRGeneratorScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const qrRef = useRef<QRCode>(null);
  const [tab, setTab] = useState<Tab>('text');
  const [text, setText] = useState(''); const [ssid, setSsid] = useState(''); const [password, setPassword] = useState(''); const [security, setSecurity] = useState<WifiSecurity>('WPA2'); const [hidden, setHidden] = useState(false); const [enterpriseIdentity, setEnterpriseIdentity] = useState('');
  const [upiId, setUpiId] = useState(''); const [upiName, setUpiName] = useState(''); const [amount, setAmount] = useState(''); const [description, setDescription] = useState(''); const [businessMode, setBusinessMode] = useState(false); const [businessCategory, setBusinessCategory] = useState('Groceries'); const [businessModeLoaded, setBusinessModeLoaded] = useState(false);
  const [whatsappNumber, setWhatsappNumber] = useState(''); const [whatsappMessage, setWhatsappMessage] = useState('');
  const [qrTheme, setQrTheme] = useState<QRTheme>({ foreground: '#000000', background: '#FFFFFF' }); const [size, setSize] = useState(240); const [quietZone, setQuietZone] = useState(12);
  const [generated, setGenerated] = useState(false); const [generatedValue, setGeneratedValue] = useState(''); const [generatedTheme, setGeneratedTheme] = useState<QRTheme>({ foreground: '#000000', background: '#FFFFFF' }); const [generatedSize, setGeneratedSize] = useState(240); const [generatedQuietZone, setGeneratedQuietZone] = useState(12);

  useFocusEffect(useCallback(() => { let active = true; AsyncStorage.getItem(BUSINESS_MODE_KEY).then((stored) => { if (!active) return; setBusinessMode(stored === 'true'); setBusinessModeLoaded(true); }).catch(() => active && setBusinessModeLoaded(true)); return () => { active = false; }; }, []));

  const requiredInputsReady = useMemo(() => {
    if (tab === 'text') return Boolean(text.trim());
    if (tab === 'url') return /^https?:\/\/.+/i.test(text.trim());
    if (tab === 'wifi') return Boolean(ssid.trim()) && Boolean(password) && Boolean(security);
    if (tab === 'upi') return Boolean(upiId.trim()) && Boolean(upiName.trim()) && Boolean(amount.trim()) && Number(amount) > 0 && (!businessMode || Boolean(businessCategory));
    return /^\d{8,15}$/.test(whatsappNumber.replace(/\D/g, ''));
  }, [tab, text, ssid, password, security, upiId, upiName, amount, businessMode, businessCategory, whatsappNumber]);

  const value = useMemo(() => {
    if (!requiredInputsReady) return '';
    if (tab === 'text' || tab === 'url') return text.trim();
    if (tab === 'wifi') {
      const auth = security === 'WPA3-Enterprise' ? 'WPA2-EAP' : security;
      const identity = security === 'WPA3-Enterprise' && enterpriseIdentity.trim() ? `;E:${escapeWifi(enterpriseIdentity.trim())}` : '';
      return `WIFI:T:${auth};S:${escapeWifi(ssid.trim())};P:${escapeWifi(password)};H:${hidden ? 'true' : 'false'}${identity};;`;
    }
    if (tab === 'upi') {
      const params = new URLSearchParams({ pa: upiId.trim(), pn: upiName.trim(), am: amount.trim(), cu: 'INR' });
      if (description.trim()) params.set('tn', description.trim());
      if (businessMode && businessCategory) params.set('mc', businessCategory);
      return `upi://pay?${params.toString()}`;
    }
    const digits = whatsappNumber.replace(/\D/g, '');
    return `https://wa.me/${digits}${whatsappMessage.trim() ? `?text=${encodeURIComponent(whatsappMessage.trim())}` : ''}`;
  }, [requiredInputsReady, tab, text, ssid, password, security, hidden, enterpriseIdentity, upiId, upiName, amount, description, businessMode, businessCategory, whatsappNumber, whatsappMessage]);

  const clearAll = () => { setText(''); setSsid(''); setPassword(''); setEnterpriseIdentity(''); setUpiId(''); setUpiName(''); setAmount(''); setDescription(''); setWhatsappNumber(''); setWhatsappMessage(''); setSecurity('WPA2'); setHidden(false); setBusinessCategory('Groceries'); setQrTheme({ foreground: '#000000', background: '#FFFFFF' }); setSize(240); setQuietZone(12); setGenerated(false); setGeneratedValue(''); setGeneratedTheme({ foreground: '#000000', background: '#FFFFFF' }); setGeneratedSize(240); setGeneratedQuietZone(12); };
  const openEditorForRegenerate = () => { setGenerated(false); setGeneratedValue(''); setQrTheme(generatedTheme); setSize(generatedSize); setQuietZone(generatedQuietZone); };

  const validateAndGenerate = () => { if (!requiredInputsReady) return; if (qrTheme.foreground === qrTheme.background) return Alert.alert('Choose contrasting colors', 'QR color and background color must be different.'); setGeneratedValue(value); setGeneratedTheme(qrTheme); setGeneratedSize(size); setGeneratedQuietZone(quietZone); setGenerated(true); };
  const toggleBusinessMode = async () => { const next = !businessMode; setBusinessMode(next); try { await AsyncStorage.setItem(BUSINESS_MODE_KEY, String(next)); } catch { /* preference remains in memory */ } };

  const getQrPng = async () => { if (!generatedValue || !qrRef.current) throw new Error('QR code is not ready.'); return new Promise<string>((resolve, reject) => { let settled = false; const finish = (fn: (value: string) => void, value: string) => { if (!settled) { settled = true; clearTimeout(timer); fn(value); } }; const timer = setTimeout(() => finish(reject, 'Timed out while rendering the QR code.'), 5000); qrRef.current?.toDataURL((data) => finish(resolve, data)); }); };
  const downloadQr = async () => { try { const base64 = await getQrPng(); const directory = FileSystem.documentDirectory; if (!directory) throw new Error('Device storage is unavailable.'); const fileUri = `${directory}nexus-plus-qr-${Date.now()}.png`; await FileSystem.writeAsStringAsync(fileUri, base64, { encoding: FileSystem.EncodingType.Base64 }); Alert.alert('QR code downloaded', 'The QR code PNG has been saved in Nexus Plus app storage.'); } catch (error) { Alert.alert('Download failed', error instanceof Error ? error.message : 'Could not save the QR code.'); } };
  const shareQr = async () => { try { const base64 = await getQrPng(); const directory = FileSystem.documentDirectory; if (!directory) throw new Error('Device storage is unavailable.'); const fileUri = `${directory}nexus-plus-qr-share-${Date.now()}.png`; await FileSystem.writeAsStringAsync(fileUri, base64, { encoding: FileSystem.EncodingType.Base64 }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(fileUri, { mimeType: 'image/png', dialogTitle: 'Share QR code' }); else await Share.share({ title: 'Nexus Plus QR code', message: generatedValue }); } catch (error) { Alert.alert('Share failed', error instanceof Error ? error.message : 'Could not share the QR code.'); } };
  useFocusEffect(useCallback(() => { const subscription = BackHandler.addEventListener('hardwareBackPress', () => { if (generated) { clearAll(); return true; } return false; }); return () => subscription.remove(); }, [generated]));

  if (generated) return <View style={[styles.resultScreen, { backgroundColor: colors.background, paddingTop: insets.top + 12, paddingBottom: insets.bottom + 20 }]}><View style={styles.resultHeader}><Pressable accessibilityRole="button" accessibilityLabel="Back to QR code generator" onPress={clearAll} style={[styles.iconButton, { borderColor: colors.border, backgroundColor: colors.card }]}><Feather name="arrow-left" size={21} color={colors.foreground} /></Pressable><Text accessibilityRole="header" style={[styles.resultTitle, { color: colors.foreground }]}>Generated QR Code</Text><View style={{ width: 46 }} /></View><View style={[styles.resultCard, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.resultHint, { color: colors.mutedForeground }]}>Your QR code is ready.</Text><View style={{ padding: generatedQuietZone, backgroundColor: generatedTheme.background, borderRadius: 14 }} accessible accessibilityLabel="Generated QR code"><QRCode ref={qrRef} value={generatedValue} size={generatedSize} backgroundColor={generatedTheme.background} color={generatedTheme.foreground} quietZone={0} ecl="H" /></View><View style={styles.resultActions}><ActionButton icon="download" label="Download" onPress={downloadQr} colors={colors} /><ActionButton icon="share-2" label="Share" onPress={shareQr} colors={colors} /><ActionButton icon="refresh-cw" label="Regenerate" onPress={openEditorForRegenerate} colors={colors} /></View></View></View>;

  const generateDisabled = !businessModeLoaded || !requiredInputsReady || qrTheme.foreground === qrTheme.background;
  return <ScrollView style={[styles.screen, { backgroundColor: colors.background }]} contentContainerStyle={{ paddingTop: insets.top + 12, paddingBottom: insets.bottom + 60 }} keyboardShouldPersistTaps="handled"><View style={styles.header}><MaterialCommunityIcons name="qrcode-edit" size={30} color={colors.primary} /><View style={styles.copy}><Text accessibilityRole="header" style={[styles.title, { color: colors.foreground }]}>QR Code Generator</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Enter data, choose options, then generate your QR code.</Text></View></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{tabs.map((item) => <Pressable key={item.key} accessibilityRole="tab" accessibilityState={{ selected: tab === item.key }} accessibilityLabel={`Generate ${item.label} QR code`} onPress={() => setTab(item.key)} style={[styles.tab, { borderColor: colors.border, backgroundColor: tab === item.key ? colors.primary : colors.card }]}><MaterialCommunityIcons name={item.icon as never} size={15} color={tab === item.key ? colors.primaryForeground : colors.foreground} /><Text style={{ color: tab === item.key ? colors.primaryForeground : colors.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 12 }}>{item.label}</Text></Pressable>)}</ScrollView><View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}>
    {(tab === 'text' || tab === 'url') && <Field label={tab === 'text' ? 'Text' : 'URL'} value={text} onChangeText={setText} placeholder={tab === 'text' ? 'Type any text' : 'https://example.com'} colors={colors} multiline autoCapitalize={tab === 'url' ? 'none' : 'sentences'} keyboardType={tab === 'url' ? 'url' : 'default'} />}
    {tab === 'wifi' && <><Field label="Network name (SSID)" value={ssid} onChangeText={setSsid} placeholder="My Wi‑Fi" colors={colors} /><Field label="Password" value={password} onChangeText={setPassword} placeholder="Wi‑Fi password" colors={colors} secure /><Text style={[styles.label, { color: colors.foreground }]}>Security</Text><View style={styles.securityRow}>{(['WPA', 'WPA2', 'WPA3', 'WPA3-Enterprise'] as WifiSecurity[]).map((item) => <Pressable key={item} accessibilityRole="radio" accessibilityState={{ selected: security === item }} onPress={() => setSecurity(item)} style={[styles.security, { borderColor: security === item ? colors.primary : colors.border, backgroundColor: security === item ? colors.secondary : colors.background }]}><Text style={{ color: colors.foreground, fontSize: 11 }}>{item}</Text></Pressable>)}</View>{security === 'WPA3-Enterprise' && <Field label="Enterprise identity" value={enterpriseIdentity} onChangeText={setEnterpriseIdentity} placeholder="Identity" colors={colors} />}<Pressable accessibilityRole="switch" accessibilityState={{ checked: hidden }} onPress={() => setHidden((current) => !current)} style={[styles.switchRow, { borderColor: colors.border }]}><Text style={[styles.switchText, { color: colors.foreground }]}>Hidden network</Text><Text style={{ color: colors.primary, fontFamily: 'Inter_700Bold' }}>{hidden ? 'On' : 'Off'}</Text></Pressable></>}
    {tab === 'upi' && <><Field label="UPI ID" value={upiId} onChangeText={setUpiId} placeholder="name@upi" colors={colors} autoCapitalize="none" /><Field label="UPI Name" value={upiName} onChangeText={setUpiName} placeholder="Receiver name" colors={colors} /><Field label="Amount (INR)" value={amount} onChangeText={setAmount} placeholder="Required amount" colors={colors} keyboardType="decimal-pad" /><Field label="Description / Note (optional)" value={description} onChangeText={setDescription} placeholder="What is this payment for?" colors={colors} multiline /><Pressable accessibilityRole="switch" accessibilityState={{ checked: businessMode }} onPress={toggleBusinessMode} style={[styles.businessToggle, { borderColor: colors.border, backgroundColor: businessMode ? colors.secondary : colors.background }]}><View style={{ flex: 1 }}><Text style={[styles.switchText, { color: colors.foreground }]}>Business / Merchant QR</Text><Text style={[styles.businessHint, { color: colors.mutedForeground }]}>Off = personal UPI. On = merchant mode with category.</Text></View><Text style={{ color: colors.primary, fontFamily: 'Inter_700Bold' }}>{businessMode ? 'On' : 'Off'}</Text></Pressable>{businessMode && <><Text style={[styles.label, { color: colors.foreground }]}>Business category (required)</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.securityRow}>{BUSINESS_CATEGORIES.map((item) => <Pressable key={item} accessibilityRole="radio" accessibilityState={{ selected: businessCategory === item }} onPress={() => setBusinessCategory(item)} style={[styles.security, { borderColor: businessCategory === item ? colors.primary : colors.border, backgroundColor: businessCategory === item ? colors.secondary : colors.background }]}><Text style={{ color: colors.foreground, fontSize: 11 }}>{item}</Text></Pressable>)}</ScrollView></>}</>}
    {tab === 'whatsapp' && <><Field label="WhatsApp number" value={whatsappNumber} onChangeText={setWhatsappNumber} placeholder="91XXXXXXXXXX" colors={colors} keyboardType="phone-pad" /><Field label="Message (optional)" value={whatsappMessage} onChangeText={setWhatsappMessage} placeholder="Hello" colors={colors} multiline /></>}
    <Text style={[styles.label, { color: colors.foreground }]}>QR appearance</Text><View style={styles.paletteGrid}>{COLOR_PALETTE.map((item) => <Pressable key={`fg-${item.name}`} accessibilityRole="radio" accessibilityState={{ selected: qrTheme.foreground === item.value }} accessibilityLabel={`QR color ${item.name}`} onPress={() => setQrTheme((theme) => ({ ...theme, foreground: item.value }))} style={[styles.swatch, { backgroundColor: item.value, borderColor: qrTheme.foreground === item.value ? colors.primary : colors.border }]} />)}</View><Text style={[styles.label, { color: colors.foreground }]}>Background color</Text><View style={styles.paletteGrid}>{COLOR_PALETTE.map((item) => <Pressable key={`bg-${item.name}`} accessibilityRole="radio" accessibilityState={{ selected: qrTheme.background === item.value }} accessibilityLabel={`QR background ${item.name}`} onPress={() => setQrTheme((theme) => ({ ...theme, background: item.value }))} style={[styles.swatch, { backgroundColor: item.value, borderColor: qrTheme.background === item.value ? colors.primary : colors.border }]} />)}</View><Text style={[styles.label, { color: colors.foreground }]}>Size: {size}px</Text><View style={styles.stepRow}><ActionButton icon="minus" label="Decrease size" onPress={() => setSize((current) => Math.max(120, current - 20))} colors={colors} /><Text style={[styles.stepValue, { color: colors.foreground }]}>{size}</Text><ActionButton icon="plus" label="Increase size" onPress={() => setSize((current) => Math.min(640, current + 20))} colors={colors} /></View><Text style={[styles.label, { color: colors.foreground }]}>Quiet zone: {quietZone}px</Text><View style={styles.stepRow}><ActionButton icon="minus" label="Decrease quiet zone" onPress={() => setQuietZone((current) => Math.max(0, current - 2))} colors={colors} /><Text style={[styles.stepValue, { color: colors.foreground }]}>{quietZone}</Text><ActionButton icon="plus" label="Increase quiet zone" onPress={() => setQuietZone((current) => Math.min(48, current + 2))} colors={colors} /></View><Pressable accessibilityRole="button" accessibilityState={{ disabled: generateDisabled }} accessibilityLabel="Generate QR code" onPress={validateAndGenerate} disabled={generateDisabled} style={[styles.generate, { backgroundColor: generateDisabled ? colors.muted : colors.primary }]}><Feather name="check-circle" size={19} color={colors.primaryForeground} /><Text style={[styles.generateText, { color: colors.primaryForeground }]}>Generate QR Code</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Clear all QR code fields" onPress={clearAll} style={[styles.clearButton, { borderColor: colors.border }]}><Text style={[styles.clearText, { color: colors.foreground }]}>Clear all</Text></Pressable></View></ScrollView>;
}

function Field({ label, value, onChangeText, placeholder, colors, multiline, secure, keyboardType, autoCapitalize }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; colors: ReturnType<typeof useColors>; multiline?: boolean; secure?: boolean; keyboardType?: 'default' | 'url' | 'phone-pad' | 'decimal-pad'; autoCapitalize?: 'none' | 'sentences' }) { return <View style={styles.field}><Text style={[styles.label, { color: colors.foreground }]}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.mutedForeground} multiline={multiline} secureTextEntry={secure} keyboardType={keyboardType} autoCapitalize={autoCapitalize} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background, minHeight: multiline ? 86 : undefined }]} /></View>; }

function ActionButton({ icon, label, onPress, colors }: { icon: React.ComponentProps<typeof Feather>['name']; label: string; onPress: () => void; colors: ReturnType<typeof useColors> }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[styles.actionButton, { borderColor: colors.border, backgroundColor: colors.card }]}><Feather name={icon} size={18} color={colors.primary} /></Pressable>; }

const styles = StyleSheet.create({ screen: { flex: 1 }, resultScreen: { flex: 1, paddingHorizontal: 18 }, resultHeader: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }, iconButton: { width: 46, height: 46, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, resultTitle: { fontSize: 18, fontFamily: 'Inter_700Bold' }, resultCard: { borderRadius: 20, borderWidth: 1, padding: 18, alignItems: 'center' }, resultHint: { alignSelf: 'stretch', fontSize: 12, marginBottom: 14 }, resultActions: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', marginTop: 18 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14 }, copy: { flex: 1 }, title: { fontSize: 24, fontFamily: 'Inter_700Bold', marginBottom: 4 }, subtitle: { fontSize: 12, lineHeight: 17 }, tabs: { gap: 8, paddingBottom: 12 }, tab: { minHeight: 42, paddingHorizontal: 12, borderRadius: 14, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 6 }, form: { borderRadius: 20, borderWidth: 1, padding: 16, gap: 10 }, field: { gap: 7 }, label: { fontSize: 12, fontFamily: 'Inter_700Bold' }, input: { borderWidth: 1, borderRadius: 13, paddingHorizontal: 12, paddingVertical: 11, fontSize: 13 }, securityRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' }, security: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 9 }, switchRow: { borderWidth: 1, borderRadius: 14, padding: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, switchText: { fontSize: 12, fontFamily: 'Inter_700Bold' }, businessToggle: { borderWidth: 1, borderRadius: 14, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, businessHint: { fontSize: 10, lineHeight: 14, marginTop: 3 }, paletteGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, swatch: { width: 30, height: 30, borderRadius: 15, borderWidth: 2 }, stepRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 15 }, stepValue: { minWidth: 60, textAlign: 'center', fontSize: 14, fontFamily: 'Inter_700Bold' }, actionButton: { minWidth: 44, minHeight: 44, borderRadius: 13, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, generate: { minHeight: 50, borderRadius: 15, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', marginTop: 6 }, generateText: { fontSize: 13, fontFamily: 'Inter_700Bold' }, clearButton: { minHeight: 46, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, clearText: { fontSize: 13, fontFamily: 'Inter_700Bold' } });
